import type { CaseDef } from "../types";
import { mcq, o } from "../templates";

export const MEDICINE_1: CaseDef[] = [
  {
    id: "med-hf", rotation: "medicine", title: "Breathless with swollen legs", level: 2, setting: "Medical ward admission, Kenyatta-level referral hospital", tags: ["heart failure", "hypertension", "diabetes", "renal", "oedema"],
    involved: ["Cardiovascular", "Renal / urinary", "Endocrine / metabolic", "Respiratory"],
    vignette: "A 62-year-old man with hypertension and diabetes is brought in with progressive shortness of breath over 3 weeks. He now sleeps on three pillows and has noticed that both his legs and his shoes feel tight.",
    hsets: ["core"], esets: ["general", "cvs", "resp", "abd"],
    hx: {
      onset: "About three weeks ago, getting steadily worse.", prog: "At first only on climbing stairs; now he gets breathless walking from the bed to the toilet.",
      sev: "He used to farm; now cannot walk 50 metres without stopping.", agg: "Worse lying flat and on exertion; better sitting up.",
      sob: "Needs three pillows. Wakes at night gasping for breath and has to sit at the window — most nights this week.", cough: "A dry cough at night, no sputum. Once pink-tinged froth.",
      swell: "Both ankles and legs swollen for about two weeks, worse in the evening; abdomen feels bloated.", cp: "No chest pain, but a dull heaviness on exertion a few months ago that he ignored.",
      palp: "Occasional awareness of a fast heartbeat.", fever: "No fever.", wt: "Appetite poor; clothes tighter — he thinks he has gained weight (fluid).",
      gu: "Passing less urine than before, no pain. Urine looks a bit frothy.", pmh: "Hypertension for 10 years, diabetes for 8 years. Stopped attending clinic 18 months ago.",
      drugs: "Takes ‘a tablet for pressure’ when he remembers; diclofenac from the chemist for knee pain. No other medicines.", fh: "Father died suddenly of ‘heart problems’ at 58.",
      alc: "Drinks a few traditional brews at weekends.", smoke: "Stopped smoking 5 years ago, 20 pack-years.", occ: "Subsistence farmer; lives with wife.",
      adm: "No previous admissions.", allergy: "No known allergies.", sex: "Married, HIV negative 2 years ago.",
    },
    hxKey: ["sob", "swell", "cp", "pmh", "drugs", "gu", "cough", "alc"],
    ex: {
      vit: "BP 168/98 mmHg, pulse 104/min, RR 26/min, SpO₂ 91% on room air, temperature 36.8 °C, weight 88 kg (was 80 kg).", pulse: "104/min, regular, small volume.",
      face: "Mild pallor; no jaundice.", neck: "JVP raised at 6 cm above the sternal angle (sitting at 45°), hepatojugular reflux positive.", oed: "Pitting oedema to the knees bilaterally; sacral oedema.",
      hands: "Cool peripheries; no clubbing.", apex: "Apex beat displaced to the 6th space, anterior axillary line; no thrills.", hs: "Third heart sound (gallop) at the apex; soft pansystolic murmur at the apex.",
      bases: "Bibasal fine crackles to mid-zones.", rr: "Tachypnoeic, sitting forward, speaking in short sentences.", chest: "Dull to percussion at the right base.", breath: "Reduced breath sounds right base with fine crackles bilaterally.",
      liv: "Tender smooth hepatomegaly 3 cm below the costal margin.", asc: "Shifting dullness positive — mild ascites.", hydr: "Looks overloaded, not dry.", nutr: "Overweight (BMI 29).",
      abdp: "Soft; RUQ tender liver edge.",
    },
    exKey: ["vit", "neck", "hs", "bases", "oed", "apex", "liv"],
    ix: [
      { id: "ecg", group: "Bedside", label: "12-lead ECG", result: "Sinus tachycardia 104/min. LVH voltage criteria with strain pattern (ST depression and T-wave inversion V5–V6). Old Q waves V1–V3. QRS 100 ms.", meaning: "LV hypertrophy from long-standing hypertension; old Q waves suggest a previous anterior infarct (silent in a diabetic) — ischaemic cardiomyopathy is likely.", use: "key" },
      { id: "cxr", group: "Imaging", label: "Chest X-ray", result: "Cardiomegaly (cardiothoracic ratio 0.62). Upper-lobe diversion, Kerley B lines, bilateral perihilar ‘bat-wing’ opacities, small bilateral pleural effusions (right > left).", meaning: "Pulmonary venous congestion and interstitial/alveolar oedema with an enlarged heart — cardiogenic pulmonary oedema.", use: "key" },
      { id: "echo", group: "Imaging", label: "Echocardiogram (bedside)", result: "Dilated LV, EF 28%. Global hypokinesia with akinetic anterior wall. Moderate functional mitral regurgitation. Dilated IVC with <50% collapse. No pericardial effusion.", meaning: "Systolic (HFrEF) failure. Anterior wall akinesia supports ischaemic aetiology. MR is functional (annular dilatation).", use: "key" },
      { id: "uec", group: "Blood", label: "Urea, electrolytes, creatinine", result: "Na 131 mmol/L (low), K 4.9, urea 14.2 mmol/L (high), creatinine 168 µmol/L (high; baseline unknown), eGFR 38.", meaning: "Hyponatraemia from neurohormonal water retention. Raised urea/creatinine: cardiorenal syndrome (low output + venous congestion) ± diabetic nephropathy ± NSAID effect.", use: "key" },
      { id: "fbc", group: "Blood", label: "Full blood count", result: "Hb 10.8 g/dL (normocytic), WBC 9.2, platelets 245.", meaning: "Mild normocytic anaemia: chronic disease/renal. Anaemia can worsen heart failure and should be sought and treated.", use: "useful" },
      { id: "glu", group: "Blood", label: "Random glucose / HbA1c", result: "RBS 14.8 mmol/L, HbA1c 10.2%.", meaning: "Poorly controlled diabetes: a driver of vascular disease and nephropathy.", use: "useful" },
      { id: "trop", group: "Blood", label: "Troponin / BNP (NT-proBNP)", result: "Troponin mildly raised (2× ULN, flat). NT-proBNP 8,200 pg/mL.", meaning: "NT-proBNP markedly raised supports heart failure; mild flat troponin = myocardial strain/chronic injury, not an acute infarct.", use: "useful" },
      { id: "urine", group: "Blood", label: "Urinalysis and urine albumin:creatinine", result: "Protein 2+, glucose 3+, no blood, no nitrites. ACR 85 mg/mmol.", meaning: "Significant albuminuria: diabetic nephropathy — another reason for oedema and for the kidney to fail with heart failure.", use: "useful" },
      { id: "lft", group: "Blood", label: "Liver function tests", result: "ALT 62, ALP 180, bilirubin 28 µmol/L, albumin 31 g/L.", meaning: "Congestive hepatopathy (raised enzymes, mild jaundice) and low albumin from nephropathy/poor nutrition.", use: "useful" },
      { id: "ct", group: "Imaging", label: "CT pulmonary angiogram", result: "Not performed.", meaning: "", use: "low", note: "No pleuritic pain, no risk factors for PE and a clear alternative explanation — a CTPA adds radiation and contrast nephrotoxicity in a patient with eGFR 38." },
      { id: "lp", group: "Other", label: "Lumbar puncture", result: "Not indicated.", meaning: "", use: "low", note: "Nothing suggests meningitis. Always ask what a test could change." },
    ],
    interpret: [
      mcq("hf-i1", "interpretation", "Looking at the chest X-ray and the echo together, what is the best interpretation?", [
        o("Cardiogenic pulmonary oedema from left ventricular systolic failure", true, "Cardiomegaly, upper-lobe diversion, Kerley B lines and bilateral effusions plus an EF of 28% are classic."),
        o("Community-acquired pneumonia", false, "Pneumonia produces focal consolidation and fever; this patient has diffuse, symmetrical congestion and no fever."),
        o("Primary pulmonary hypertension", false, "Would give a prominent pulmonary artery with oligaemic lung fields, not pulmonary oedema."),
        o("Large pericardial effusion with tamponade", false, "The echo shows no effusion."),
      ], ["Is the abnormality focal or diffuse? Unilateral or bilateral?", "Kerley B lines are fluid in interlobular septa.", "What does a dilated LV with EF 28% do to pressure in the pulmonary veins?", "Think: ‘cardiomegaly + upper-lobe diversion + effusions + low EF’."], "Raised left atrial pressure is transmitted back to the pulmonary veins → fluid moves into interstitium and alveoli → congestion on X-ray and orthopnoea/PND clinically.", { after: "echo" }),
      mcq("hf-i2", "interpretation", "Na 131, urea 14.2, creatinine 168 with ACR 85. Which statements are correct? (select all)", [
        o("Hyponatraemia reflects neurohormonal activation with water retention (ADH, RAAS)", true, "Poor perfusion activates RAAS, sympathetic system and ADH → water retained in excess of sodium."),
        o("The kidney injury may be ‘cardiorenal’ — low output and venous congestion reduce renal perfusion", true, "Renal venous pressure also rises with right-sided congestion."),
        o("Long-standing diabetes could be contributing, and diclofenac may make it worse", true, "NSAIDs inhibit prostaglandin-mediated afferent dilatation and cause sodium retention — dangerous in HF and CKD."),
        o("This proves intrinsic renal failure, so heart failure treatment is irrelevant", false, "Treating the heart (decongestion, afterload reduction) often improves kidney function in this setting."),
      ], ["Think about what the failing heart does to the kidney’s blood supply.", "What do ADH and aldosterone do to water and sodium?", "Which over-the-counter drug listed in the history harms both heart and kidney?", "Cardiorenal syndrome — the heart and kidney fail together."], "Always ask whether the kidney is a victim of the heart, a cause of the fluid overload, or both — it changes which drugs are safe (ACE inhibitors, spironolactone, NSAIDs).", { after: "uec" }),
    ],
    ddx: [
      { name: "Congestive heart failure (HFrEF) — hypertensive/ischaemic cardiomyopathy", aliases: ["heart failure", "cardiac failure", "chf", "congestive cardiac failure", "hfref", "cardiomyopathy", "left ventricular failure", "lvf"], tier: "likely", why: "Orthopnoea + PND + bilateral oedema + raised JVP + displaced apex with S3: the whole picture of venous congestion (lungs and systemic).", for: ["Orthopnoea, PND, nocturnal cough", "Raised JVP, third heart sound, displaced apex, bibasal crackles", "Years of untreated hypertension and diabetes; ischaemic risk"], against: ["No fever or chest pain (argues against infection / acute MI as the primary event)"], separate: { ask: "Orthopnoea and PND with an exertional tempo", exam: "JVP, S3, displaced apex, bibasal crackles", ix: "Echo (EF) and NT-proBNP; CXR" } },
      { name: "Nephrotic / renal causes of oedema (diabetic nephropathy, CKD, AKI)", aliases: ["renal failure", "nephrotic", "ckd", "kidney disease", "diabetic nephropathy", "aki", "nephritic", "renal disease"], tier: "possible", why: "Diabetic for 8 years, frothy urine, rising creatinine — sodium and water retention cause oedema and even pulmonary oedema.", for: ["Frothy urine, diabetes, albuminuria 85", "Raised creatinine"], against: ["Orthopnoea with raised JVP and S3 means pump failure, not just salt retention", "Renal oedema usually starts around the eyes and legs, JVP is not typically raised in nephrotic syndrome"], separate: { ask: "Facial puffiness in the morning, frothy urine", exam: "JVP, S3, oedema pattern (periorbital in nephrotic)", ix: "ACR/urine protein, albumin, echo" } },
      { name: "Chronic liver disease / cirrhosis with ascites", aliases: ["cirrhosis", "liver disease", "liver failure", "portal hypertension", "ascites", "hepatic"], tier: "possible", why: "Ascites, hepatomegaly, jaundice and leg oedema can result from low albumin and portal hypertension; he drinks traditional brews.", for: ["Ascites, mild jaundice, alcohol history", "Low albumin"], against: ["Liver here is smooth and tender and the JVP is raised — a congested liver, not a shrunken one", "No stigmata (spider naevi, palmar erythema)"], separate: { ask: "Alcohol quantity, previous jaundice, haematemesis", exam: "JVP (high in cardiac, normal/low in cirrhosis), spider naevi, liver texture and size", ix: "LFTs/INR, ultrasound liver, echo" } },
      { name: "Pulmonary embolism / pneumonia / COPD (respiratory causes of breathlessness)", aliases: ["pulmonary embolism", "pe", "pneumonia", "copd", "asthma", "lung disease", "respiratory"], tier: "dangerous", why: "Breathlessness has respiratory causes too, and PE is dangerous. Smoking history and an effusion keep these alive until excluded.", for: ["Smoker for 20 pack-years", "Hypoxia, tachypnoea"], against: ["Orthopnoea/PND + bilateral oedema + high JVP are cardiac", "No fever, no pleuritic pain, no productive cough"], separate: { ask: "Fever, sputum, pleuritic pain, leg pain, immobility", exam: "Focal chest signs, unilateral leg swelling, JVP", ix: "CXR, D-dimer/CTPA if indicated, echo" } },
    ],
    event: { when: "after-ix", title: "He is getting worse", text: "While you review the results he becomes more distressed. He is sitting bolt upright, coughing frothy pink sputum, and cannot complete a sentence.", vitals: "BP 190/110, pulse 128/min, RR 38/min, SpO₂ 82% on room air, bilateral crackles to the apices.", q: mcq("hf-ev", "emergency", "What do you do NOW? (select all appropriate immediate actions)", [
      o("Sit him upright, give high-flow oxygen and get IV access", true, "ABC: hypoxia is the immediate threat; sitting up reduces venous return and work of breathing."),
      o("IV furosemide (loop diuretic) and a nitrate if BP allows", true, "Diuretic decongests; nitrates reduce preload/afterload and help in hypertensive pulmonary oedema."),
      o("Consider non-invasive ventilation (CPAP) if available and still hypoxic", true, "CPAP recruits alveoli, improves oxygenation and reduces intubation."),
      o("Give a 1-litre normal saline bolus because the BP is high and the kidney is injured", false, "Fluid would drown him; this is fluid overload."),
      o("Send him for CT first to ‘confirm the cause’", false, "Stabilisation first. The diagnosis is already clear enough to treat."),
    ], ["Airway, Breathing, Circulation — which is failing?", "Pulmonary oedema is excess fluid in the lungs; which drugs remove fluid and reduce preload?", "He is hypertensive at 190/110 — a vasodilator is helpful.", "Sit up, oxygen, furosemide IV, nitrate, CPAP; no fluids."], "In acute pulmonary oedema, treat first, investigate second. Diagnosis comes second to stabilisation.") },
    dx: { q: mcq("hf-dx", "pathophysiology", "What is the best working diagnosis?", [
      o("Acute decompensated heart failure (HFrEF) from hypertensive/ischaemic cardiomyopathy, with cardiorenal syndrome and diabetic nephropathy", true, "Fits every strand: congestion, low EF, old Q waves, hypertension, diabetes, rising creatinine."),
      o("Nephrotic syndrome", false, "Proteinuria is moderate and the congestion is cardiac."),
      o("Decompensated alcoholic cirrhosis", false, "Hepatic congestion explains the liver findings; JVP and echo show cardiac cause."),
      o("Community-acquired pneumonia with sepsis", false, "No fever, no focal signs."),
    ], ["Which single diagnosis explains the lungs, legs, liver, kidney and the ECG?", "What is the commonest cause of HFrEF worldwide?", "EF 28% + anterior akinesia + old Q waves.", "Ischaemic/hypertensive cardiomyopathy with decompensated HFrEF."], "Think of heart failure as a syndrome with a cause: here hypertension and probable silent MI. Always name the cause, the precipitant (non-adherence, NSAIDs, infection, arrhythmia) and the complications (cardiorenal).") },
    mgmt: mcq("hf-mx", "management", "Once stable, which long-term steps are appropriate? (select all)", [
      o("Stop diclofenac and counsel against NSAIDs", true, "NSAIDs cause fluid retention, hypertension and kidney injury."),
      o("Diuretic to reach euvolaemia, with daily weights, fluid and salt restriction", true, "Decongestion relieves symptoms; weight is the monitoring tool."),
      o("Start an ACE inhibitor/ARB, beta-blocker and a mineralocorticoid antagonist at low dose once stable, monitoring K⁺ and creatinine", true, "Guideline therapy for HFrEF reduces mortality; start low, titrate, check renal function."),
      o("Treat the cause: statin/antiplatelet if ischaemic, control BP and glucose, evaluate for revascularisation", true, "Cause-directed treatment prevents progression."),
      o("Give a calcium-channel blocker (verapamil) for blood pressure", false, "Non-dihydropyridine CCBs are negatively inotropic and harmful in HFrEF."),
      o("Restart regular NSAIDs for his knee pain because it is a quality-of-life issue", false, "Use paracetamol; NSAIDs worsen both heart and kidney."),
    ], ["Which drug in his history made things worse?", "Which drug classes have a proven mortality benefit in HFrEF?", "What would you check after starting an ACE inhibitor in a patient with eGFR 38?", "Stop NSAID; diuretic; ACEI/ARB + beta-blocker + MRA; treat cause."], "HFrEF therapy rests on four pillars (ACEI/ARNI, beta-blocker, MRA, SGLT2 inhibitor) plus diuretics for symptoms. Always re-check potassium and creatinine."),
    consultant: [
      mcq("hf-c1", "pathophysiology", "Why does a failing left ventricle cause leg oedema?", [
        o("Reduced output activates RAAS and ADH → sodium and water retention, plus raised venous pressure from right-sided congestion", true, "Starling forces: raised hydrostatic pressure plus plasma volume expansion."),
        o("Low albumin from the liver is the only cause", false, "Albumin is mildly low but is not the primary mechanism here."),
        o("Lymphatics are destroyed by the heart", false, "No."),
        o("Venous valves fail because of hypertension", false, "Not the mechanism."),
      ], ["Think about what the kidney ‘sees’ when cardiac output falls.", "Which hormones retain salt and water?", "Hydrostatic pressure in veins also rises.", "Neurohormonal activation + venous congestion."], "Heart failure is a circulatory–neurohormonal syndrome, not just a weak pump."),
      mcq("hf-c2", "consultant", "What would kill this patient first, and what else are you worried about? (select all)", [
        o("Acute pulmonary oedema with respiratory failure", true, "The immediate danger."),
        o("Hyperkalaemia from AKI and ACE inhibitors/spironolactone", true, "Life-threatening arrhythmia."),
        o("Ventricular arrhythmia / sudden cardiac death (EF 28%)", true, "A leading cause of death in HFrEF."),
        o("Hypoglycaemia from poorly controlled diabetes treatment", false, "He is hyperglycaemic; not the first threat."),
      ], ["Which organ system fails fastest?", "What does the ECG/EF risk?", "Which electrolyte rises when the kidney fails and you add RAAS blockers?", "Respiratory failure, arrhythmia, hyperkalaemia."], "The consultant’s question ‘what would kill him first?’ is about prioritising. Oxygenation, then rhythm, then metabolic derangement."),
      mcq("hf-c3", "consultant", "Which finding best separates cardiac from nephrotic oedema at the bedside?", [
        o("JVP: raised in cardiac failure, usually normal or low in nephrotic syndrome", true, "Nephrotic oedema is from low oncotic pressure/salt retention with a flat JVP."),
        o("Pitting vs non-pitting oedema", false, "Both pit."),
        o("Presence of fever", false, "Not discriminating."),
        o("Age of the patient", false, "Not discriminating."),
      ], ["Which neck vein measurement tells you about right heart pressure?", "Nephrotic patients are often intravascularly depleted.", "JVP.", "JVP raised = cardiac."], "A good clinician always measures the JVP: it is the single most informative sign for the cause of oedema."),
    ],
    chain: { risk: "Long-standing hypertension, diabetes, smoking, silent MI, NSAIDs, non-adherence", patho: "Pressure/volume overload and myocardial loss → low output → RAAS/ADH/sympathetic activation → salt and water retention, raised filling pressures", symptoms: "Exertional dyspnoea, orthopnoea, PND, oedema, fatigue", signs: "Raised JVP, S3, displaced apex, bibasal crackles, hepatomegaly, ascites, oedema", ix: "ECG (LVH, old Q), CXR (cardiomegaly, congestion), echo (EF 28%), NT-proBNP, U&E (cardiorenal)", dx: "Decompensated HFrEF — hypertensive/ischaemic cardiomyopathy", mx: "Oxygen, IV diuretic ± nitrate, CPAP if needed → ACEI/ARB, beta-blocker, MRA, treat cause", comp: "Pulmonary oedema, arrhythmia, hyperkalaemia, cardiorenal syndrome, sudden death" },
    mustKnow: [
      "Orthopnoea + PND + raised JVP + S3 = left heart failure until proven otherwise.",
      "Always ask what precipitated decompensation: non-adherence, NSAIDs, infection, arrhythmia, ischaemia, anaemia, excess salt.",
      "BNP/NT-proBNP is raised in HF; a normal value makes HF unlikely.",
      "Acute pulmonary oedema: sit up, oxygen, IV furosemide, nitrate, CPAP — no fluids.",
      "Avoid NSAIDs and non-dihydropyridine calcium-channel blockers in HFrEF.",
      "HFrEF drug classes with mortality benefit: ACEI/ARB/ARNI, beta-blocker, MRA, SGLT2 inhibitor.",
      "Cardiorenal syndrome: check urea, creatinine and potassium before and after every change.",
    ],
    thinkIf: [["Orthopnoea + PND + bilateral oedema", "Cardiac failure/congestion — then ask why (ischaemia, hypertension, valve, cardiomyopathy)."], ["Oedema with a normal JVP and frothy urine", "Nephrotic syndrome (low albumin/proteinuria)."], ["Oedema + ascites + spider naevi", "Chronic liver disease/portal hypertension."]],
    revise: "heart failure",
  },
  {
    id: "med-acs", rotation: "medicine", title: "Crushing chest pain in a diabetic", level: 2, setting: "Emergency department", tags: ["chest pain", "acute coronary syndrome", "ECG", "emergency"], emergency: true,
    involved: ["Cardiovascular", "Endocrine / metabolic"],
    vignette: "A 55-year-old man, a long-distance truck driver with diabetes, arrives sweaty and pale after 90 minutes of central chest tightness that started while he was resting at a roadside. He describes it as ‘a heavy stone on my chest’.",
    hsets: ["core"], esets: ["general", "cvs", "resp", "abcde"],
    hx: {
      onset: "Sudden, 90 minutes ago, at rest.", prog: "Constant and getting worse; not relieved by lying still.", sev: "10/10; he is frightened and drenched in sweat.", agg: "Not affected by breathing or movement; not relieved by antacids he took.",
      cp: "Central heaviness spreading to the left arm and jaw. Nausea and sweating. Previous episodes of exertional tightness for 2 months that eased with rest.", sob: "Slightly breathless with the pain.", palp: "Feels lightheaded.", cough: "No cough.",
      gi: "Nausea; vomited once.", pmh: "Type 2 diabetes for 10 years, hypertension.", drugs: "Metformin; occasional amlodipine. No aspirin.", smoke: "Smokes 15 cigarettes a day for 30 years.", alc: "Social drinker.",
      fh: "Brother had a heart attack at 49.", occ: "Truck driver — long sedentary hours, irregular meals.", fever: "None.", sex: "HIV status unknown.", allergy: "No known allergies.",
    },
    hxKey: ["cp", "onset", "pmh", "drugs", "smoke", "fh", "sob", "allergy"],
    hxExtra: [{ id: "tearing", group: "Presenting complaint", label: "Is the pain tearing and radiating to the back? Any difference between arm BPs?", def: "No. It is a heavy, squeezing pain; no tearing sensation or back pain.", why: "Aortic dissection must be considered before anticoagulating." }],
    ex: {
      vit: "BP 98/64 mmHg (right arm; left arm 96/62), pulse 112/min regular, RR 24/min, SpO₂ 94% on room air, temperature 36.7 °C, glucose 13.2 mmol/L.", gcs: "Alert but anxious.", hands: "Cold, clammy peripheries.",
      pulse: "112/min, regular, low volume.", neck: "JVP not elevated.", hs: "Normal heart sounds, no murmurs.", apex: "Normal.", bases: "Clear lung bases.", oed: "None.", rr: "Mildly tachypnoeic.", breath: "Clear.", sacral: "No oedema; peripheral pulses present and symmetrical.",
      A: "Patent, talking.", B: "RR 24, SpO₂ 94%.", C: "Cool, clammy, BP 98/64, HR 112, capillary refill 3 s.", D: "Alert, glucose 13.2.", E: "No other injuries.",
    },
    exKey: ["vit", "hs", "bases", "neck", "pulse"],
    ix: [
      { id: "ecg", group: "Bedside", label: "12-lead ECG (immediately)", result: "Sinus tachycardia 112/min. ST elevation 4 mm in V2–V5 and I, aVL with reciprocal ST depression in II, III, aVF. Hyperacute T waves V2–V4.", meaning: "Acute anterior (anterolateral) STEMI — LAD occlusion. The ECG within 10 minutes is the decisive test; do not wait for troponin.", use: "key" },
      { id: "trop", group: "Blood", label: "Troponin (high-sensitivity)", result: "Troponin I 0.8 ng/mL at 90 min (rising).", meaning: "Myocyte necrosis beginning; troponin may be normal in the first hours of STEMI so it never delays treatment when the ECG is diagnostic.", use: "key" },
      { id: "cxr", group: "Imaging", label: "Chest X-ray (portable)", result: "Normal cardiac size, clear lung fields, normal mediastinal width.", meaning: "No pulmonary oedema yet; mediastinum normal (argues against aortic dissection).", use: "useful" },
      { id: "uec", group: "Blood", label: "U&E, creatinine, K⁺", result: "Na 137, K 4.1, creatinine 98 µmol/L.", meaning: "Baseline renal function and potassium before thrombolysis/ACE inhibitor and for contrast.", use: "useful" },
      { id: "lipid", group: "Blood", label: "Lipids, HbA1c", result: "LDL 4.8 mmol/L, HbA1c 9.4%.", meaning: "High risk profile — secondary prevention targets.", use: "useful" },
      { id: "echo", group: "Imaging", label: "Bedside echo", result: "Anterior wall hypokinesia, EF ~40%, no pericardial effusion, no aortic root dilatation.", meaning: "Regional wall motion abnormality matches the ECG; excludes tamponade/dissection signs.", use: "useful" },
      { id: "ddimer", group: "Blood", label: "D-dimer", result: "Not done.", meaning: "", use: "low", note: "With an ECG showing STEMI this would only delay reperfusion." },
      { id: "ct", group: "Imaging", label: "CT chest angiogram", result: "Not done.", meaning: "", use: "low", note: "Not indicated here — no features of dissection or PE; reperfusion cannot wait." },
    ],
    interpret: [mcq("acs-i1", "interpretation", "The ECG shows ST elevation in V2–V5, I and aVL with reciprocal changes in the inferior leads. What is your interpretation and priority?", [
      o("Anterior STEMI — reperfuse immediately (primary PCI or thrombolysis) without waiting for troponin", true, "Time is myocardium. Every minute of occlusion kills muscle."),
      o("NSTEMI — wait for troponin then decide", false, "ST elevation = STEMI; troponin is not needed to act."),
      o("Pericarditis — give NSAIDs", false, "Diffuse concave ST elevation with PR depression, no reciprocal changes."),
      o("Benign early repolarisation — discharge", false, "Not with 90 minutes of ischaemic pain and reciprocal change."),
    ], ["Are the ST changes localised to one coronary territory, and are there reciprocal changes?", "V2–V5 plus I and aVL looks like which artery?", "Does the patient’s pain history support ischaemia?", "Anterior STEMI = LAD occlusion: reperfusion now."], "Reciprocal ST depression adds specificity for occlusion MI. If primary PCI is not available within 120 min, give thrombolysis (e.g. tenecteplase) unless contraindicated.", { after: "ecg" })],
    ddx: [
      { name: "Acute ST-elevation myocardial infarction (anterior)", aliases: ["stemi", "myocardial infarction", "mi", "heart attack", "acute coronary syndrome", "acs", "acute mi", "ischaemic chest pain"], tier: "likely", why: "Classic ischaemic pain with autonomic features in a diabetic smoker with strong risk profile and prior stable angina.", for: ["Heavy central pain radiating to arm and jaw", "Sweating, nausea, hypotension", "Diabetes, smoking, hypertension, family history"], against: ["Nothing really against once the ECG is seen"], separate: { ask: "Character, radiation, associated sweating, prior exertional pain", exam: "Perfusion, JVP, new murmur, symmetrical pulses", ix: "ECG within 10 minutes; troponin" } },
      { name: "Acute aortic dissection", aliases: ["aortic dissection", "dissection", "thoracic aortic dissection"], tier: "dangerous", why: "Sudden severe chest pain in a hypertensive man. Missing it and giving thrombolysis/anticoagulants can be fatal.", for: ["Sudden severe pain, hypertension"], against: ["Not tearing, no back pain, equal arm BPs, normal mediastinum"], separate: { ask: "Tearing/radiating to back, neurological symptoms", exam: "Pulse deficit, arm BP difference, aortic regurgitation murmur", ix: "CXR mediastinum, echo aortic root, CT angiography if suspicion" } },
      { name: "Pulmonary embolism", aliases: ["pe", "pulmonary embolism"], tier: "dangerous", why: "A long-distance driver is a risk group for DVT/PE; PE can cause chest pain, hypotension and tachycardia.", for: ["Prolonged immobility, tachycardia, hypotension"], against: ["Not pleuritic, no calf signs, ECG shows STEMI with reciprocal change"], separate: { ask: "Pleuritic pain, haemoptysis, leg swelling", exam: "Unilateral leg swelling, raised JVP", ix: "ECG pattern, CTPA/echo, D-dimer if low probability" } },
      { name: "Acute pericarditis / myocarditis", aliases: ["pericarditis", "myocarditis"], tier: "possible", why: "Chest pain with ST elevation can be pericarditis; usually in younger patients after a viral illness.", for: ["ST elevation"], against: ["Localised ST elevation with reciprocal changes, no rub, no postural pain"], separate: { ask: "Pain better leaning forward, recent viral illness", exam: "Pericardial friction rub", ix: "ECG pattern (diffuse concave ST, PR depression), echo" } },
    ],
    event: { when: "after-ix", title: "He collapses", text: "While you arrange reperfusion he suddenly becomes unresponsive. You find no pulse; the monitor shows a chaotic irregular rhythm with no organised complexes.", vitals: "Unresponsive, not breathing normally, no carotid pulse. Monitor: ventricular fibrillation.", q: mcq("acs-ev", "emergency", "What do you do NOW?", [
      o("Call for help, start CPR and defibrillate as soon as available (200 J biphasic)", true, "VF is a shockable rhythm — CPR bridges until the shock; early defibrillation is the most important determinant of survival."),
      o("Give IV amiodarone and wait for it to work", false, "Drugs are secondary; shock first."),
      o("Check troponin to confirm the infarct", false, "No role in cardiac arrest."),
      o("Place a CT order for the head in case of stroke", false, "Treat the arrest first."),
    ], ["Is this a rhythm that a shock can fix?", "Which comes first in VF: drugs, shock or tests?", "Chest compressions continue between shocks.", "CPR + immediate defibrillation, then adrenaline/amiodarone per ALS."], "VF after STEMI is common in the first hours. Treat the arrest and then return to reperfusion once ROSC is achieved.") },
    dx: { q: mcq("acs-dx", "pathophysiology", "What is the best working diagnosis?", [
      o("Acute anterior STEMI due to LAD occlusion, complicated by ventricular fibrillation", true, "Plaque rupture → thrombus → occlusion → transmural infarction and electrical instability."),
      o("Unstable angina", false, "ST elevation and troponin rise indicate infarction."),
      o("Aortic dissection", false, "Not supported."),
      o("Costochondritis", false, "No chest-wall tenderness; ECG is diagnostic."),
    ], ["What does ST elevation mean?", "Which coronary artery supplies the anterior wall?", "Plaque rupture with thrombus = ?", "Anterior STEMI (LAD)."], "STEMI is a clinical + ECG diagnosis. Reperfusion within 90 minutes of arrival (PCI) or 30 minutes (thrombolysis) saves muscle."),
    },
    mgmt: mcq("acs-mx", "management", "Which immediate actions are appropriate for STEMI? (select all)", [
      o("Aspirin 300 mg chewed plus a second antiplatelet (e.g. clopidogrel/ticagrelor)", true, "Dual antiplatelet therapy reduces re-occlusion."),
      o("Reperfusion: primary PCI if available within 120 min, otherwise thrombolysis if no contraindication", true, "Restore flow quickly."),
      o("Anticoagulation (heparin/enoxaparin), oxygen only if SpO₂ <90%, IV opioid for pain and an anti-emetic", true, "Standard supportive STEMI bundle."),
      o("Atorvastatin 80 mg and plan beta-blocker/ACE inhibitor once stable", true, "Early secondary prevention."),
      o("Give routine high-flow oxygen to everyone with chest pain", false, "Unnecessary if SpO₂ ≥90%; may be harmful."),
      o("Give an IV beta-blocker now because HR is 112", false, "He is hypotensive and may be in early cardiogenic shock — avoid."),
    ], ["Think antiplatelet, reperfusion, anticoagulation.", "What dangerous drug class do you avoid in hypotension?", "Oxygen is for hypoxia, not for chest pain itself.", "Aspirin + P2Y12, reperfusion, heparin, statin; avoid IV beta-blocker in shock."], "Time-critical STEMI bundle: ECG ≤10 min, reperfusion ≤90 min (PCI) / ≤30 min (lysis)."),
    consultant: [
      mcq("acs-c1", "consultant", "Which are contraindications to thrombolysis? (select all)", [
        o("Previous haemorrhagic stroke or active internal bleeding", true, "Fibrinolysis would cause catastrophic bleeding."),
        o("Suspected aortic dissection", true, "Lysis worsens dissection/bleeding."),
        o("Severe uncontrolled hypertension (>180/110)", true, "Risk of intracranial haemorrhage."),
        o("Diabetes mellitus", false, "Not a contraindication."),
      ], ["Which condition would bleed on a clot-busting drug?", "Why did you check both arm BPs?", "Think of intracranial bleeding risk.", "Bleeding, dissection, severe hypertension."], "Always run a contraindication checklist before lysis."),
      mcq("acs-c2", "pathophysiology", "What causes the typical sequence of events?", [
        o("Atherosclerotic plaque rupture exposes thrombogenic material → platelet and fibrin thrombus occludes the coronary artery", true, "That is the final common pathway of STEMI."),
        o("Coronary spasm without plaque", false, "Possible but uncommon (e.g. cocaine)."),
        o("Embolus from the left atrium", false, "Rare cause."),
        o("Left ventricular hypertrophy alone", false, "Predisposes to ischaemia but not the acute occlusion."),
      ], ["What is in the artery wall of a 55-year-old smoker with diabetes?", "What happens when a plaque cap tears?", "Platelets + fibrin.", "Plaque rupture + thrombus."], "ACS is a thrombotic complication of atherosclerosis."),
      mcq("acs-c3", "consultant", "What complications of an anterior STEMI are you worried about? (select all)", [
        o("Ventricular arrhythmias (VF/VT)", true, "Commonest early cause of death."),
        o("Acute heart failure / cardiogenic shock", true, "Large anterior infarcts lose pump function."),
        o("Mechanical complications: papillary muscle rupture, VSD, free wall rupture (days later)", true, "Presents as new murmur or sudden collapse."),
        o("Pericarditis (Dressler syndrome) weeks later", true, "Autoimmune pericarditis."),
      ], ["Think in time frames: minutes, days, weeks.", "What happens to dead muscle at day 3–7?", "A new pansystolic murmur after an MI means?", "Arrhythmia, failure, mechanical, pericarditis."], "Timeline of complications is a classic ward-round question."),
    ],
    chain: { risk: "Diabetes, smoking, hypertension, dyslipidaemia, family history, sedentary job", patho: "Plaque rupture → thrombus → LAD occlusion → transmural ischaemia and necrosis", symptoms: "Crushing central pain to arm/jaw, sweating, nausea, dyspnoea", signs: "Pallor, sweating, tachycardia, hypotension, S3 in failure", ix: "ECG: ST elevation V2–V5 with reciprocal change; rising troponin; echo wall-motion abnormality", dx: "Anterior STEMI", mx: "Aspirin + P2Y12, reperfusion, heparin, analgesia, statin; treat VF with defibrillation", comp: "VF, cardiogenic shock, mechanical complications, Dressler" },
    mustKnow: [
      "STEMI is diagnosed on ECG within 10 minutes — do not wait for troponin.",
      "Time is muscle: PCI door-to-balloon ≤90 min; thrombolysis door-to-needle ≤30 min.",
      "Diabetics may present with atypical or painless MI.",
      "Always exclude aortic dissection before anticoagulation/lysis (pain character, arm BP difference, CXR).",
      "VF is treated with immediate defibrillation, not drugs first.",
      "Avoid IV beta-blockers in hypotension or signs of heart failure.",
      "Secondary prevention: antiplatelets, statin, ACE inhibitor, beta-blocker, glycaemic control, smoking cessation.",
    ],
    thinkIf: [["Heavy central chest pain + sweating + ST elevation", "STEMI — reperfuse now."], ["Tearing chest pain radiating to the back, unequal arm BPs", "Aortic dissection until excluded."], ["Pleuritic chest pain + tachycardia + risk factor for DVT", "Pulmonary embolism."]],
    revise: "myocardial infarction",
  },
];
