import type { CaseDef } from "../types";
import { mcq, o } from "../templates";

export const PSYCH_2: CaseDef[] = [
  {
    id: "ps-mania", rotation: "psychiatry", title: "No sleep for a week, spending everything, and ‘chosen by God’", level: 2, setting: "Psychiatric emergency", tags: ["bipolar disorder", "mania", "risk assessment", "mood stabilisers"],
    involved: ["Psychiatric"],
    vignette: "A 29-year-old woman is brought by her husband. For ten days she has hardly slept, talks non-stop, has withdrawn all their savings to ‘start an empire’, and says God has chosen her to heal the nation.",
    hsets: ["psych"], esets: ["general", "mse"],
    hx: {
      pc: "She says she has never felt better and doesn’t need sleep.", onset: "About 10 days; escalating each day.", mood: "Elated and irritable; very energetic; overspending, sexually disinhibited.", sleep: "Sleeping 1–2 hours a night and not tired.", psychosis: "Believes she has special powers; hears God’s voice affirming her mission.",
      cog: "Oriented, no fever or headache; no head injury.", subst: "No alcohol, no khat, no stimulants.", meds: "No medications; no thyroid disease; no steroids.", "risk-self": "Denies suicidal thoughts but takes dangerous risks (walking in traffic).", "risk-other": "Irritable and verbally aggressive when challenged.",
      past: "Treated for depression 4 years ago for 6 months; one previous episode of ‘too much energy’ 2 years ago that she didn’t report.", fam: "Her father had bipolar disorder.", pers: "Teacher; married with a 2-year-old child; no trauma.", collat: "Husband says she has been vulgar, giving money to strangers and neglecting the child.", anx: "No anxiety.",
    },
    hxKey: ["mood", "sleep", "past", "fam", "subst", "meds", "risk-other", "collat"],
    ex: {
      vit: "BP 122/76, pulse 100, RR 18, SpO₂ 99%, temperature 36.9 °C, glucose normal.", gcs: "Alert.", neck: "No goitre.", hands: "Fine tremor; warm hands.", nutr: "Thin from not eating.",
      "m-app": "Brightly dressed, theatrical make-up, restless, uninhibited and intrusive.", "m-speech": "Pressured, loud, rapid; difficult to interrupt.", "m-mood": "Elevated and expansive; labile with irritability.", "m-form": "Flight of ideas with clang associations; distractible.", "m-content": "Grandiose delusions (chosen by God), over-valued plans; no suicidal ideas.",
      "m-perc": "Mood-congruent auditory hallucinations (God’s voice).", "m-cog": "Oriented, but distractible; poor concentration.", "m-ins": "No insight; judgment severely impaired.",
    },
    exKey: ["m-mood", "m-speech", "m-form", "m-content", "m-ins", "vit"],
    ix: [
      { id: "med", group: "Blood", label: "Exclude organic causes: glucose, FBC, U&E, TFT, calcium, HIV, urine drug screen, pregnancy test", result: "All normal; TSH normal; urine drug screen negative; pregnancy test negative.", meaning: "No medical or substance cause for mania.", use: "key" },
      { id: "baseline", group: "Blood", label: "Baseline before lithium/valproate: U&E, creatinine, TFT, calcium, LFT, FBC, ECG", result: "Normal baseline; creatinine 70 µmol/L.", meaning: "Needed to start mood stabilisers safely.", use: "key" },
      { id: "scales", group: "Bedside", label: "Mania rating (YMRS) and risk assessment", result: "YMRS 36 (severe mania); high risk of harm to self (risk-taking), child neglect, and financial/sexual vulnerability.", meaning: "Needs admission.", use: "key" },
      { id: "ct", group: "Imaging", label: "CT brain", result: "Not done.", meaning: "", use: "low", note: "No focal signs, no head injury, first-degree relative with bipolar — not indicated." },
      { id: "eeg", group: "Other", label: "EEG", result: "Not done.", meaning: "", use: "low", note: "Not indicated." },
    ],
    interpret: [mcq("ma-i1", "interpretation", "Elevated mood, reduced need for sleep, pressured speech, flight of ideas, grandiosity, risky behaviour for 10 days, previous depression, father with bipolar disorder. Diagnosis?", [
      o("Bipolar I disorder, current episode manic with psychotic features", true, "Mania ≥1 week with functional impairment/psychosis."), o("Schizophrenia", false, "Mood-congruent psychosis with elevated mood."), o("Major depression", false, "No."), o("Substance-induced mania", false, "Screen negative."),
    ], ["How long?", "Which mood?", "Is it mood-congruent?", "Bipolar mania."], "A single manic episode defines bipolar I.", { after: "med" })],
    ddx: [
      { name: "Bipolar I disorder — manic episode with psychotic features", aliases: ["bipolar", "bipolar disorder", "mania", "manic episode", "bipolar i", "hypomania"], tier: "likely", why: "Elevated/irritable mood, grandiosity, pressured speech, decreased need for sleep, flight of ideas, risky behaviour, family history and past depression.", for: ["Classic manic syndrome, family history, past depression"], against: ["None"], separate: { ask: "Duration, previous episodes", exam: "MSE, mood congruence", ix: "Exclude organic causes" } },
      { name: "Schizophrenia / schizoaffective disorder", aliases: ["schizophrenia", "schizoaffective", "psychosis"], tier: "possible", why: "Psychotic symptoms can occur in mania; schizophrenia has a different course and affect.", for: ["Delusions, hallucinations"], against: ["Mood-congruent psychosis with elevated mood, family history"], separate: { ask: "Mood episodes", exam: "Affect", ix: "Longitudinal" } },
      { name: "Substance-induced (amphetamine, khat, steroids) or organic mania (thyrotoxicosis, HIV, frontal lobe lesion, epilepsy)", aliases: ["substance induced", "thyrotoxicosis", "hiv", "steroid induced", "organic mania", "stimulants", "frontal lobe"], tier: "dangerous", why: "Treatable causes must be excluded.", for: ["Hyperactivity, warm hands, tremor"], against: ["Normal TFT, negative drug screen"], separate: { ask: "Substances, drugs, head injury", exam: "Goitre, tremor, neurology", ix: "TFT, drug screen, HIV, CT if focal" } },
      { name: "Postpartum or puerperal psychosis / ADHD / personality disorder", aliases: ["postpartum psychosis", "puerperal psychosis", "adhd", "personality disorder"], tier: "possible", why: "She has a young child; ask about timing.", for: ["Young child"], against: ["2-year-old, 10-day onset, past episodes"], separate: { ask: "Timing with birth", exam: "Confusion", ix: "Clinical" } },
    ],
    event: { when: "after-exam", title: "Escalation on the ward", text: "On the ward she becomes aggressive, tries to leave to ‘save the nation’, and threatens a nurse. She refuses all medication.", vitals: "HR 120, BP 150/94, no signs of intoxication.", q: mcq("ma-ev", "emergency", "What is the safest approach? (select all)", [
      o("Verbal de-escalation and low-stimulation environment first; assess capacity; detain under the Mental Health Act if she lacks capacity and is a risk", true, "Legal, least restrictive."), o("If urgent sedation is needed: oral/IM lorazepam ± an antipsychotic (e.g. olanzapine or haloperidol) with monitoring of vital signs", true, "Rapid tranquillisation."), o("Start a mood stabiliser (lithium or valproate, avoid valproate in women of child-bearing age unless on contraception) plus an antipsychotic", true, "Definitive therapy."), o("Allow her to leave because she is ‘a free person’", false, "Unsafe."),
    ], ["What is the legal framework?", "What is least restrictive?", "What treats mania?", "De-escalate, assess capacity, sedate if needed, mood stabiliser."], "Document capacity and risk reasons.") },
    dx: { q: mcq("ma-dx", "pathophysiology", "What is the pathophysiology and typical long-term course?", [
      o("Dysregulation of monoamines/second messengers with strong genetic contribution; recurrent episodes of mania and depression requiring long-term prophylaxis", true, "Chronic relapsing."), o("A single stress reaction", false, "No."), o("A purely learned behaviour", false, "No."), o("Infection of the brain", false, "No."),
    ], ["Is it genetic?", "Is it recurrent?", "What prevents relapse?", "Mood stabilisers."], "Lifetime risk of recurrence is very high."),
    },
    mgmt: mcq("ma-mx", "management", "Select correct management.", [
      o("Acute mania: antipsychotic (olanzapine/quetiapine/haloperidol) ± benzodiazepine for sleep/agitation; stop antidepressants", true, "Control symptoms."), o("Start a mood stabiliser (lithium or valproate/carbamazepine) with monitoring (lithium levels, renal/thyroid function, teratogenic risk counselling)", true, "Long-term prophylaxis."), o("Admit for safety, involve family, protect finances/child; psychoeducation, sleep hygiene, early warning signs plan", true, "Whole-person care."), o("Review after discharge: relapse prevention, adherence, contraception counselling, treat depressive episodes carefully", true, "Follow-up."),
      o("Give antidepressants alone", false, "Can trigger mania."), o("Stop all medication once symptoms resolve", false, "High relapse."),
    ], ["What controls acute mania?", "What prevents recurrence?", "What can precipitate mania?", "Antipsychotic, mood stabiliser, psychoeducation."], "Lithium: narrow therapeutic index — check levels, U&E and TFT."),
    consultant: [
      mcq("ma-c1", "consultant", "Compare mania and hypomania; list DSM criteria (select all true).", [
        o("Mania: ≥1 week of elevated/irritable mood with ≥3 symptoms (grandiosity, decreased sleep, pressured speech, flight of ideas, distractibility, increased activity, risky behaviour) causing marked impairment/psychosis", true, "Mania."), o("Hypomania: ≥4 days, no marked impairment or psychosis", true, "Hypomania."), o("Bipolar I requires at least one manic episode; bipolar II hypomania + depression", true, "Classification."), o("Mania is just a good mood", false, "No."),
      ], ["Duration?", "Impairment?", "Psychosis?", "First three."], "Always ask about previous hypomania."),
      mcq("ma-c2", "pathophysiology", "What are important lithium side effects and toxicity (select all)?", [
        o("Tremor, polyuria (nephrogenic diabetes insipidus), hypothyroidism, weight gain", true, "Common."), o("Toxicity (>1.5 mmol/L): coarse tremor, ataxia, vomiting, confusion, seizures — worsened by dehydration, NSAIDs and ACE inhibitors", true, "Serious."), o("Teratogenic (Ebstein anomaly)", true, "Counsel."), o("No monitoring is needed", false, "Must monitor."),
      ], ["Which organs?", "What worsens toxicity?", "Which malformation?", "First three."], "Interactions matter."),
      mcq("ma-c3", "consultant", "What would harm this patient?", [
        o("Risky behaviour, financial ruin, sexual vulnerability and exploitation", true, "Social risks."), o("Neglect of the child and relationship breakdown", true, "Family risks."), o("Switch to severe depression and suicide after mania", true, "Next phase."), o("Non-adherence and relapse", true, "Chronic risk."),
      ], ["What risks in mania?", "Who is vulnerable?", "What comes after?", "All."], "Manage the whole family."),
    ],
    chain: { risk: "Family history, previous depression, sleep deprivation, antidepressants", patho: "Dysregulated monoamine/second-messenger systems; strong genetic loading", symptoms: "Elated/irritable mood, reduced sleep, overspending, grandiose ideas", signs: "Pressured speech, flight of ideas, distractibility, lack of insight, mood-congruent psychosis", ix: "Exclude organic/substance causes; YMRS; baseline for lithium/valproate", dx: "Bipolar I disorder — manic episode with psychotic features", mx: "Admit, antipsychotic ± benzodiazepine, mood stabiliser, psychoeducation, legal safeguards", comp: "Harm from risk-taking, relapse, depression, suicide" },
    mustKnow: ["Mania = elevated/irritable mood ≥1 week + reduced need for sleep, grandiosity, pressured speech, flight of ideas, risk-taking.", "Always exclude organic/substance causes (thyroid, drugs, HIV, steroids).", "Avoid antidepressant monotherapy in bipolar disorder.", "Lithium: monitor levels, renal and thyroid function; toxicity risk with dehydration/NSAIDs.", "Valproate is teratogenic: counsel women.", "Assess capacity and use the Mental Health Act when needed.", "Support family and protect dependants."],
    thinkIf: [["Elevated mood + decreased need for sleep + pressured speech", "Mania."], ["Low mood + past hypomania", "Bipolar depression."], ["Fluctuating consciousness + acute onset", "Delirium instead."]],
    revise: "bipolar disorder",
  },
  {
    id: "ps-dts", rotation: "psychiatry", title: "Shaking and seeing things on the third day in hospital", level: 3, setting: "Surgical ward — day 3 after admission", tags: ["alcohol withdrawal", "delirium tremens", "Wernicke", "seizures"], emergency: true,
    involved: ["Psychiatric", "Toxic / drug-related", "Neurological", "Gastrointestinal / hepatobiliary"],
    vignette: "A 45-year-old man was admitted to the surgical ward with a fractured leg. On the third night he becomes agitated, sweaty and tremulous, says there are insects crawling on the walls and does not know where he is.",
    hsets: ["psych"], esets: ["general", "mse", "neuro"],
    hx: {
      pc: "Terrified; talks to people who aren’t there.", onset: "Started tonight, 60 hours after his last drink (before the accident).", mood: "Frightened and irritable.", sleep: "No sleep for 2 nights.", psychosis: "Vivid visual hallucinations of insects and snakes; tactile hallucinations.", cog: "Disoriented to time and place; fluctuating.",
      subst: "Drinks 12 bottles of beer and spirits daily for 15 years; last drink 3 days ago; had withdrawal seizures once before; denies other drugs.", meds: "Receiving analgesia (opioids) and IV fluids with dextrose; no thiamine given; no regular medication.", "risk-self": "No suicidal ideas expressed.", "risk-other": "Striking out at staff because he believes he is being attacked.",
      past: "Previous admission for alcohol withdrawal seizures; no psychiatric illness.", fam: "Father an alcoholic.", pers: "Builder; lost his job; separated.", collat: "Brother says he drinks every morning and gets ‘the shakes’ if he stops; he has had chronic dyspepsia and vomited this evening.",
    },
    hxKey: ["subst", "onset", "cog", "psychosis", "past", "meds", "collat"],
    ex: {
      vit: "BP 168/104, pulse 128/min, RR 24/min, SpO₂ 95%, temperature 38.3 °C, glucose 5.0 mmol/L.", gcs: "GCS 14; fluctuating.", hands: "Coarse tremor of the hands, sweaty palms.", face: "Flushed with spider naevi; mild jaundice; hepatomegaly 3 cm on palpation, no ascites.", hydr: "Dehydrated.", mouth: "Dry mouth, ketotic breath.",
      "m-app": "Agitated, sweating, picking at the air.", "m-speech": "Rapid, shaky, incoherent.", "m-mood": "Fearful, anxious.", "m-form": "Disorganised.", "m-content": "Persecutory misinterpretations.", "m-perc": "Visual and tactile hallucinations (insects, snakes).", "m-cog": "Disoriented to time and place; attention markedly impaired.", "m-ins": "No insight.",
      cn: "Eye movements: horizontal nystagmus, bilateral lateral rectus weakness.", tone: "Brisk reflexes; ataxic gait (unable to stand unaided).", mening: "Neck supple.", sens: "Reduced vibration sense in the feet.", speech: "Tremulous speech.",
    },
    exKey: ["vit", "hands", "m-cog", "m-perc", "cn", "tone"],
    ix: [
      { id: "glu", group: "Bedside", label: "Glucose, ketones, ECG", result: "Glucose 5.0; ketones 1+; ECG sinus tachycardia, prolonged QT.", meaning: "Alcoholic ketosis; QT prolonged (low K/Mg).", use: "key" },
      { id: "uec", group: "Blood", label: "U&E, Mg, phosphate, calcium, LFT, FBC, INR", result: "Na 129, K 2.9, Mg 0.5 mmol/L (low), phosphate low; AST 180, ALT 86, GGT high, MCV 108, platelets 90, INR 1.5, albumin 28.", meaning: "Electrolyte depletion and alcohol-related liver disease (macrocytosis, thrombocytopenia).", use: "key" },
      { id: "ct", group: "Imaging", label: "CT head (if head injury, focal signs or fits)", result: "Mild cerebral atrophy; no haemorrhage.", meaning: "Excludes subdural haematoma in a patient who has fallen.", use: "useful" },
      { id: "capacity", group: "Bedside", label: "CIWA-Ar score (withdrawal severity)", result: "CIWA-Ar 29 (severe).", meaning: "Severe withdrawal: delirium tremens.", use: "key" },
      { id: "udrug", group: "Blood", label: "Blood alcohol, urine drug screen", result: "Alcohol undetectable; screen negative.", meaning: "He is in withdrawal, not intoxicated.", use: "useful" },
      { id: "mri", group: "Imaging", label: "MRI brain first", result: "Not done.", meaning: "", use: "low", note: "Not needed to start treatment. Give thiamine and treat first." },
    ],
    interpret: [mcq("dt-i1", "interpretation", "Day 3 after last drink: agitation, sweating, tremor, tachycardia, fever, visual hallucinations, disorientation. Plus nystagmus, lateral rectus palsy and ataxia. What is the dual diagnosis?", [
      o("Delirium tremens (severe alcohol withdrawal) and Wernicke encephalopathy (thiamine deficiency) — a double emergency", true, "DTs: 48–96 h; Wernicke: ophthalmoplegia, ataxia, confusion."), o("Schizophrenia", false, "Acute, organic."), o("Alcoholic hallucinosis only", false, "No clouding of consciousness in hallucinosis."), o("Cerebellar stroke", false, "No."),
    ], ["Timing since last drink?", "Which triad?", "Which vitamin?", "DTs + Wernicke."], "Give high-dose IV thiamine BEFORE glucose.", { after: "capacity" })],
    ddx: [
      { name: "Delirium tremens (severe alcohol withdrawal) with Wernicke encephalopathy", aliases: ["delirium tremens", "dts", "alcohol withdrawal", "alcohol withdrawal delirium", "wernicke", "wernicke encephalopathy", "withdrawal", "delirium"], tier: "likely", why: "Heavy daily drinking stopped abruptly with autonomic hyperactivity, tremor, hallucinations and disorientation; ocular signs and ataxia suggest Wernicke.", for: ["60 h since last drink, autonomic hyperactivity, tremor, hallucinations, disorientation, nystagmus, ataxia"], against: ["None"], separate: { ask: "Last drink, previous withdrawal", exam: "Tremor, autonomic signs, ocular signs", ix: "CIWA-Ar, electrolytes, thiamine response" } },
      { name: "Sepsis / hospital-acquired infection / head injury (subdural) / fat embolism after fracture", aliases: ["sepsis", "infection", "subdural haematoma", "head injury", "fat embolism", "pneumonia", "hospital acquired infection"], tier: "dangerous", why: "A post-fracture patient with fever and delirium may have infection, fat embolism or intracranial bleeding.", for: ["Fever, confusion, recent trauma"], against: ["Withdrawal timeline and tremor"], separate: { ask: "Fall, head strike", exam: "Petechiae, focal signs", ix: "CT head, cultures, CXR, gas" } },
      { name: "Primary psychotic disorder / alcoholic hallucinosis", aliases: ["schizophrenia", "psychosis", "alcoholic hallucinosis", "primary psychosis"], tier: "possible", why: "Hallucinations in a drinker could be hallucinosis (clear consciousness) or psychosis.", for: ["Hallucinations"], against: ["Disorientation and autonomic hyperactivity"], separate: { ask: "Course, orientation", exam: "Clear sensorium in hallucinosis", ix: "Clinical" } },
      { name: "Hypoglycaemia / electrolyte disturbance / hepatic encephalopathy / opioid withdrawal", aliases: ["hypoglycaemia", "hepatic encephalopathy", "electrolyte disturbance", "hyponatraemia", "opioid withdrawal"], tier: "possible", why: "Other causes of confusion in a patient with liver disease and electrolyte loss.", for: ["Low Na, Mg"], against: ["Normal glucose; autonomic hyperactivity"], separate: { ask: "Drug use", exam: "Asterixis", ix: "Glucose, ammonia, electrolytes" } },
    ],
    event: { when: "after-exam", title: "Seizure", text: "While being assessed he has a generalised tonic–clonic seizure lasting 3 minutes. His breathing is laboured afterwards.", vitals: "SpO₂ 88%, HR 140, BP 170/100, temperature 38.8 °C.", q: mcq("dt-ev", "emergency", "What do you do NOW? (select all)", [
      o("ABC: airway, oxygen, left-lateral position; IV lorazepam/diazepam for the seizure", true, "Benzodiazepine first-line for withdrawal seizures."), o("High-dose IV thiamine (e.g. 500 mg 8-hourly) before any glucose; correct magnesium/potassium; treat with a benzodiazepine regimen (symptom-triggered or loading) for delirium tremens", true, "Wernicke prevention and withdrawal treatment."), o("Monitor in HDU: cardiac monitoring, glucose, fluids, treat hyperthermia and look for infection or fracture complications", true, "Supportive care."), o("Give phenytoin as the main treatment", false, "Phenytoin does not work in withdrawal seizures."),
    ], ["What stops withdrawal seizures?", "Which vitamin first?", "Which electrolyte lowers the threshold?", "Benzodiazepine + thiamine + magnesium."], "Glucose before thiamine can precipitate Wernicke.") },
    dx: { q: mcq("dt-dx", "pathophysiology", "What is the mechanism of alcohol withdrawal?", [
      o("Chronic alcohol enhances GABA inhibition and suppresses glutamate (NMDA); abrupt cessation causes rebound CNS hyperexcitability with sympathetic overactivity", true, "GABA down, glutamate up."), o("Direct toxic effect of alcohol on liver only", false, "No."), o("Vitamin C deficiency", false, "No."), o("A learned anxiety response", false, "No."),
    ], ["Which transmitter inhibits?", "Which excites?", "What do benzodiazepines act on?", "GABA/glutamate imbalance."], "Benzodiazepines are cross-tolerant with alcohol."),
    },
    mgmt: mcq("dt-mx", "management", "Select correct management.", [
      o("Benzodiazepines (e.g. diazepam or lorazepam) titrated to CIWA-Ar or fixed-dose taper; avoid antipsychotics alone (lower seizure threshold)", true, "Core treatment."), o("Parenteral high-dose thiamine for Wernicke before glucose; replace magnesium, potassium, phosphate; multivitamins", true, "Prevent permanent amnesia."), o("Hydration, antipyretics, treat infection/fracture complications and DVT prophylaxis; cardiac monitoring", true, "Supportive."), o("After recovery: motivational interviewing, relapse prevention (acamprosate/naltrexone/disulfiram when appropriate), treat liver disease, social support", true, "Long-term care."),
      o("Give alcohol IV", false, "No."), o("Discharge him to continue drinking", false, "No."),
    ], ["Which sedative?", "Which vitamin?", "Which minerals?", "Benzodiazepine, thiamine, electrolytes."], "DTs mortality is up to 5–15% if untreated."),
    consultant: [
      mcq("dt-c1", "consultant", "Give the timeline of alcohol withdrawal (select all true).", [
        o("6–12 h: tremor, anxiety, sweating, nausea", true, "Minor withdrawal."), o("12–48 h: seizures, hallucinosis", true, "Seizures."), o("48–96 h: delirium tremens (agitation, hallucinations, autonomic instability)", true, "DTs."), o("DTs begin within minutes of the last drink", false, "No."),
      ], ["When do seizures occur?", "When does DT start?", "What happens first?", "First three."], "Time since last drink guides risk."),
      mcq("dt-c2", "pathophysiology", "What is the Wernicke–Korsakoff syndrome?", [
        o("Wernicke: confusion, ophthalmoplegia/nystagmus, ataxia (thiamine deficiency); untreated leads to Korsakoff: irreversible anterograde amnesia and confabulation", true, "Thiamine deficiency."), o("A viral encephalitis", false, "No."), o("A drug intoxication", false, "No."), o("A stroke", false, "No."),
      ], ["Which triad?", "Which vitamin?", "What is the outcome?", "Thiamine deficiency."], "Give thiamine to every at-risk patient."),
      mcq("dt-c3", "consultant", "What would kill this patient and what else are you worried about?", [
        o("Withdrawal seizures and arrhythmia (low K/Mg, prolonged QT)", true, "Immediate."), o("Hyperthermia, dehydration and aspiration", true, "Delirium complications."), o("Missed infection/fat embolism/GI bleed/hepatic failure", true, "Medical comorbidity."), o("Korsakoff syndrome", true, "Long-term."),
      ], ["Think seizures, heart, infection.", "What is missed?", "What is permanent?", "All."], "Prevention: identify at-risk drinkers on admission and give prophylaxis."),
    ],
    chain: { risk: "Heavy daily alcohol use, previous withdrawal seizures, abrupt cessation (admission), poor nutrition", patho: "Loss of alcohol-enhanced GABA inhibition with up-regulated glutamate → CNS hyperexcitability; thiamine deficiency → Wernicke", symptoms: "Tremor, sweating, hallucinations, agitation, insomnia", signs: "Tachycardia, fever, hypertension, disorientation, nystagmus, ataxia", ix: "CIWA-Ar, glucose, electrolytes/Mg, LFT/FBC/INR, CT head if indicated", dx: "Delirium tremens with Wernicke encephalopathy", mx: "Benzodiazepines, IV thiamine, electrolyte replacement, supportive care, relapse prevention", comp: "Seizures, arrhythmia, Korsakoff, death" },
    mustKnow: ["Withdrawal timeline: tremor 6–12 h; seizures 12–48 h; DT 48–96 h.", "DT = delirium + autonomic hyperactivity (a medical emergency).", "Benzodiazepines are first-line; give thiamine BEFORE glucose.", "Correct magnesium, potassium and phosphate.", "Look for Wernicke: ophthalmoplegia, ataxia, confusion.", "Exclude head injury, infection, hypoglycaemia.", "Plan relapse prevention before discharge."],
    thinkIf: [["Tremor + sweating + hallucinations 2–3 days after stopping alcohol", "Delirium tremens."], ["Confusion + ophthalmoplegia + ataxia in a drinker", "Wernicke encephalopathy."], ["Clear consciousness + persistent voices", "Alcoholic hallucinosis / psychosis."]],
    revise: "alcohol withdrawal",
  },
  {
    id: "ps-panic", rotation: "psychiatry", title: "‘I’m having a heart attack’ — again", level: 2, setting: "Casualty", tags: ["panic disorder", "chest pain", "anxiety", "medical vs psychiatric"],
    involved: ["Psychiatric", "Cardiovascular", "Endocrine / metabolic"],
    vignette: "A 28-year-old woman rushes into casualty gasping, with palpitations, chest tightness, tingling in her hands and a feeling that she is going to die. This is her fourth visit this month; all previous ECGs were normal.",
    hsets: ["psych"], esets: ["general", "cvs", "resp", "mse"],
    hx: {
      pc: "She is sure something is wrong with her heart.", onset: "Attacks come suddenly without warning, peak within 10 minutes and last 20–30 minutes; first attack 3 months ago.", mood: "Worried most of the time; some low mood.", sleep: "Waking at night in panic.", anx: "Fears of another attack; avoids buses and crowded places; constant worry about her health.",
      cog: "No confusion, no fever.", subst: "Drinks several cups of coffee and two energy drinks daily; no alcohol, no drugs.", meds: "No medications; not pregnant; no thyroid disease known.", "risk-self": "Denies suicidal thoughts.", "risk-other": "Denies.", past: "No previous psychiatric history.", fam: "Mother has an anxiety disorder.",
      pers: "Student; recent exam stress and a breakup.", collat: "Friend says attacks come in crowds and at night.", psychosis: "None.", cp: "Chest tightness during attacks, not exertional; no pleuritic pain.", palp: "Pounding heart, dizziness, tingling in fingers and around the mouth.", sob: "Feels she cannot breathe during attacks.",
      wt: "Lost 3 kg over three months (reduced appetite).", fever: "None.", pmh: "No illness; no thyroid history.",
    },
    hxKey: ["onset", "cp", "palp", "subst", "pmh", "anx", "meds", "wt"],
    hxExtra: [
      { id: "cp", group: "Medical screen", label: "Chest pain: character, exertion, pleuritic?", def: "Chest tightness during attacks, not exertional; no pleuritic pain.", why: "Separates cardiac and pleuritic causes from panic." },
      { id: "palp", group: "Medical screen", label: "Palpitations, dizziness, tingling", def: "Pounding heart, dizziness, tingling in fingers and around the mouth.", why: "Autonomic arousal and hyperventilation." },
      { id: "sob", group: "Medical screen", label: "Breathlessness", def: "Feels she cannot breathe during attacks.", why: "Hyperventilation vs respiratory disease." },
      { id: "wt", group: "Medical screen", label: "Weight loss, heat intolerance, tremor", def: "Lost 3 kg over three months (reduced appetite).", why: "Hyperthyroidism mimics anxiety." },
      { id: "pmh", group: "Medical screen", label: "Medical history (thyroid, asthma, heart disease, diabetes)", def: "No illness; no thyroid history.", why: "Organic causes of anxiety." },
      { id: "fever", group: "Medical screen", label: "Fever or recent illness", def: "None.", why: "Infection can cause confusion and tachycardia." },
    ],
    ex: {
      vit: "BP 130/80, pulse 118/min regular, RR 30/min, SpO₂ 99%, temperature 37.0 °C, glucose 5.4 mmol/L.", hands: "Moist, tremulous fingers; carpopedal spasm during hyperventilation; no clubbing.", neck: "Small diffuse goitre palpable; no bruit; JVP normal.", pulse: "118/min regular.", face: "No eye signs.",
      hs: "Normal heart sounds, no murmurs.", bases: "Clear.", breath: "Clear; fast shallow breathing.", rr: "Hyperventilating.", oed: "None.",
      "m-app": "Tearful, anxious, fidgety.", "m-speech": "Rapid, anxious.", "m-mood": "Anxious mood, affect congruent.", "m-form": "Normal.", "m-content": "Fear of death and of heart disease; no psychosis; no suicidal ideas.", "m-perc": "No hallucinations.", "m-cog": "Oriented, anxious.", "m-ins": "Partial insight: ‘it feels real’.",
    },
    exKey: ["vit", "neck", "hs", "hands", "rr"],
    ix: [
      { id: "ecg", group: "Bedside", label: "12-lead ECG", result: "Sinus tachycardia 112/min; no ischaemic changes.", meaning: "No evidence of ACS or arrhythmia.", use: "key" },
      { id: "tft", group: "Blood", label: "Thyroid function tests (TSH, free T4)", result: "TSH <0.01 mU/L; free T4 36 pmol/L (high).", meaning: "Thyrotoxicosis (Graves) can mimic panic attacks and anxiety — an important organic cause.", use: "key" },
      { id: "glu", group: "Bedside", label: "Capillary glucose, FBC, electrolytes, calcium", result: "Normal; Hb 12.9.", meaning: "Excludes hypoglycaemia, anaemia and hypocalcaemia.", use: "useful" },
      { id: "troponin", group: "Blood", label: "Troponin / D-dimer if low risk", result: "Troponin negative at 3 h.", meaning: "No myocardial injury.", use: "useful" },
      { id: "gad", group: "Bedside", label: "GAD-7 and panic scale; PHQ-9", result: "GAD-7 17 (severe anxiety); PHQ-9 11 (moderate).", meaning: "Significant anxiety with some depressive symptoms.", use: "useful" },
      { id: "ct", group: "Imaging", label: "CT pulmonary angiogram", result: "Not done.", meaning: "", use: "low", note: "Low-risk, young, normal oxygenation and clear alternative — not indicated." },
    ],
    interpret: [mcq("pn-i1", "interpretation", "ECG normal, TSH suppressed, free T4 raised, goitre, tachycardia, weight loss, tremor. How does this change your diagnosis of ‘panic disorder’?", [
      o("The panic-like attacks have an organic contributor — hyperthyroidism (Graves’ disease) — so treat the thyrotoxicosis and reassess for an anxiety disorder", true, "Always exclude thyrotoxicosis in anxiety/palpitations."), o("It confirms primary panic disorder", false, "No."), o("It excludes anxiety entirely", false, "Anxiety can co-exist."), o("It indicates cardiac disease", false, "No."),
    ], ["What does the thyroid do to the heart and mind?", "Which test is abnormal?", "Treat what first?", "Hyperthyroidism."], "Medical causes of anxiety: thyrotoxicosis, phaeochromocytoma, hypoglycaemia, arrhythmia, caffeine/stimulants, asthma, PE.", { after: "tft" })],
    ddx: [
      { name: "Panic disorder (± contributing thyrotoxicosis and caffeine)", aliases: ["panic disorder", "panic attacks", "anxiety", "anxiety disorder", "generalised anxiety disorder", "panic attack", "hyperventilation"], tier: "likely", why: "Recurrent unexpected attacks with fear of dying, palpitations, hyperventilation and avoidance, with normal ECGs.", for: ["Abrupt peak in 10 minutes, hyperventilation, paraesthesia, recurrent attacks, avoidance, family history"], against: ["Thyrotoxicosis may be driving it"], separate: { ask: "Triggers, worry between attacks", exam: "Hyperventilation, thyroid", ix: "ECG, TFT" } },
      { name: "Hyperthyroidism (Graves’ disease)", aliases: ["hyperthyroidism", "thyrotoxicosis", "graves disease", "thyroid", "goitre"], tier: "likely", why: "Palpitations, anxiety, weight loss, goitre, tremor — organic cause of anxiety.", for: ["Weight loss, goitre, tremor, tachycardia"], against: ["None"], separate: { ask: "Heat intolerance, weight loss", exam: "Goitre, tremor, eye signs", ix: "TSH, fT4, TRAb" } },
      { name: "Acute coronary syndrome / arrhythmia (SVT) / pulmonary embolism", aliases: ["acs", "myocardial infarction", "heart attack", "svt", "arrhythmia", "pulmonary embolism", "pe", "cardiac"], tier: "dangerous", why: "Chest pain and palpitations: never dismiss them without ECG and risk assessment.", for: ["Chest tightness, palpitations"], against: ["Young, normal ECG/troponin, clear panic features"], separate: { ask: "Exertional, pleuritic", exam: "Murmurs, calves", ix: "ECG, troponin, D-dimer if indicated" } },
      { name: "Phaeochromocytoma / hypoglycaemia / stimulant use / asthma / depression with anxiety", aliases: ["phaeochromocytoma", "hypoglycaemia", "caffeine", "stimulants", "asthma", "depression"], tier: "possible", why: "Other conditions that mimic panic.", for: ["Palpitations, anxiety"], against: ["Normal glucose, BP, clear chest"], separate: { ask: "Episodic hypertension, headache", exam: "BP during attack", ix: "Metanephrines, glucose" } },
    ],
    event: { when: "after-ix", title: "She faints", text: "While waiting for the TFTs she hyperventilates, develops carpopedal spasm and collapses briefly. She recovers within a minute.", vitals: "HR 130, RR 36, SpO₂ 99%, glucose 5.2, ECG unchanged.", q: mcq("pn-ev", "emergency", "What do you do NOW?", [
      o("Reassure; coach slow breathing (breath-holding technique); check ABC and glucose; exclude arrhythmia on monitor; do NOT use a paper bag; benzodiazepine only if severe and persistent", true, "Hypocapnia causes tetany/faint."), o("Rebreathe into a paper bag", false, "Dangerous (hypoxia)."), o("Give IV calcium for ‘low calcium’", false, "Calcium is normal; the cause is respiratory alkalosis."), o("Call it ‘attention seeking’ and discharge", false, "Never dismiss symptoms."),
    ], ["Why do her hands cramp?", "What is happening to CO₂?", "What is the safest first step?", "Slow breathing and monitoring."], "Hyperventilation lowers ionised calcium (alkalosis) causing paraesthesia and carpopedal spasm.") },
    dx: { q: mcq("pn-dx", "pathophysiology", "What is the mechanism of the symptoms?", [
      o("Sympathetic surge (palpitations, tremor) and hyperventilation → respiratory alkalosis → reduced ionised calcium → paraesthesia, carpopedal spasm and a sense of dying; thyrotoxicosis amplifies adrenergic tone", true, "Physiological explanation."), o("Primary heart disease", false, "No."), o("Hypocalcaemia from parathyroid disease", false, "Calcium is normal."), o("Epilepsy", false, "No."),
    ], ["What does fear do to breathing?", "What happens to CO₂ and pH?", "What does alkalosis do to ionised calcium?", "Hyperventilation alkalosis."], "Explain the mechanism to the patient — it reduces fear."),
    },
    mgmt: mcq("pn-mx", "management", "Select correct management.", [
      o("Treat the thyrotoxicosis (carbimazole/PTU, beta-blocker such as propranolol for symptoms) and arrange endocrine follow-up; investigate cause (TRAb/scan)", true, "Organic contributor."), o("Explain panic attacks and give education; teach breathing control; avoid caffeine/stimulants", true, "Psychoeducation."), o("For panic disorder: CBT (first-line) ± SSRI (e.g. sertraline); benzodiazepines only short-term/rescue", true, "Evidence-based therapy."), o("Safety net: return if chest pain is exertional/prolonged/with syncope; follow-up in 1–2 weeks to review mood, GAD-7 and PHQ-9", true, "Review."),
      o("Long-term benzodiazepines", false, "Dependence."), o("Repeat unnecessary scans each visit", false, "Reinforces health anxiety."),
    ], ["What organic cause?", "What does CBT target?", "Which drug class?", "Treat thyroid, educate, CBT/SSRI."], "Always screen for depression and suicide risk in anxiety disorders."),
    consultant: [
      mcq("pn-c1", "consultant", "List medical conditions that mimic or provoke anxiety/panic (select all).", [
        o("Hyperthyroidism, phaeochromocytoma, hypoglycaemia", true, "Endocrine."), o("Arrhythmias, mitral valve prolapse, angina", true, "Cardiac."), o("Asthma/COPD, PE, caffeine and stimulant use, alcohol/benzodiazepine withdrawal", true, "Respiratory/drug."), o("Healthy sleep", false, "No."),
      ], ["Which glands?", "Which organs?", "Which drugs?", "First three."], "Take a medication and caffeine history."),
      mcq("pn-c2", "pathophysiology", "What is the cognitive model of panic disorder?", [
        o("Catastrophic misinterpretation of normal bodily sensations → fear → more sensations → panic; avoidance maintains the problem", true, "Vicious cycle; CBT targets it."), o("Primary heart lesion", false, "No."), o("Hormone excess only", false, "No."), o("Purely genetic with no environmental effect", false, "No."),
      ], ["What do patients think the sensations mean?", "What does fear do?", "What maintains it?", "Catastrophic misinterpretation."], "Explain it to the patient."),
      mcq("pn-c3", "consultant", "What would you worry about in this patient?", [
        o("Missing an organic cause (arrhythmia, PE, thyrotoxicosis)", true, "Diagnostic error."), o("Comorbid depression and suicide risk", true, "Common."), o("Agoraphobia and social disability; benzodiazepine dependence", true, "Long-term."), o("Thyroid storm if untreated", true, "Rare but lethal."),
      ], ["Medical or psychiatric?", "Mood?", "Disability?", "Complications."], "Treat both the thyroid and the anxiety."),
    ],
    chain: { risk: "Family history, stress, caffeine, thyrotoxicosis, catastrophic cognitions", patho: "Sympathetic overactivity + hyperventilation (respiratory alkalosis, ↓ionised Ca²⁺) + threat misinterpretation; thyrotoxicosis amplifies", symptoms: "Palpitations, chest tightness, breathlessness, paraesthesia, fear of dying", signs: "Tachycardia, hyperventilation, tremor, carpopedal spasm, goitre", ix: "ECG, troponin, TFT, glucose, GAD-7/PHQ-9", dx: "Panic disorder with underlying thyrotoxicosis (Graves’)", mx: "Treat thyroid, education, CBT ± SSRI, caffeine reduction, safety netting", comp: "Agoraphobia, depression, dependence, missed cardiac disease" },
    mustKnow: ["Never label ‘anxiety’ before ECG and thyroid function are considered.", "Panic: abrupt peak within 10 minutes, fear of dying, paraesthesia from hyperventilation.", "Thyrotoxicosis mimics anxiety: tremor, weight loss, goitre, tachycardia.", "Hyperventilation → alkalosis → carpopedal spasm; do not use a paper bag.", "CBT first-line for panic; SSRIs add benefit; avoid long-term benzodiazepines.", "Screen for depression and suicide risk.", "Take a caffeine and stimulant history."],
    thinkIf: [["Young woman + palpitations + weight loss + tremor", "Thyrotoxicosis."], ["Sudden fear + hyperventilation + tingling", "Panic attack."], ["Exertional chest pain + risk factors", "Angina — investigate."]],
    revise: "anxiety disorder",
  },
  {
    id: "ps-adhd", rotation: "psychiatry", title: "‘He can’t sit still, can’t learn, and doesn’t look at people’", level: 2, setting: "Child and adolescent mental health clinic", tags: ["ADHD", "autism spectrum disorder", "child psychiatry", "developmental history"],
    involved: ["Psychiatric", "Neurological"],
    vignette: "An 8-year-old boy is brought by his mother after his teacher complained that he cannot sit still, interrupts the class and is failing despite being bright. His mother adds that he plays alone, lines up toys, hates changes in routine and has few friends.",
    hsets: ["psych", "paeds"], esets: ["paeds", "mse"],
    hx: {
      pc: "Mother: ‘He is always on the go; he never listens; he has no friends.’", onset: "Hyperactivity noticed since age 3–4; social difficulties since toddlerhood.", mood: "Cheerful at home, frustrated at school.", sleep: "Takes long to fall asleep; wakes early.", psychosis: "None.", cog: "No fits; no head injury.", subst: "N/A.", meds: "None.", "risk-self": "No self-harm.", "risk-other": "Occasionally hits peers when frustrated.",
      past: "No previous treatment.", fam: "Father had learning problems; an uncle ‘is a loner’.", pers: "Healthy, no major illness.", collat: "Teacher’s report: inattentive, impulsive in class, difficulty with group work, intense interest in trains, distressed by loud noises.", birth: "Term, uneventful delivery; mother had no alcohol/drug use in pregnancy.",
      dev: "Walked at 12 months; first words at 2.5 years; limited back-and-forth conversation; repeats phrases; does not point to share interest; prefers solitary play.", feed: "Very picky eater.", imm: "Complete.", hiv: "Negative.", danger: "No danger signs.", fever: "None.", resp: "None.", gi: "None.", neuro: "No seizures.", other: "Hearing screen normal at school.",
    },
    hxKey: ["dev", "collat", "birth", "past", "fam", "sleep", "cog"],
    ex: {
      pgen: "Weight and height normal for age; alert and active; BP 100/60; no dysmorphic features.", phyd: "Normal.", presp: "Normal.", pcvs: "Normal.", pabd: "Normal.", pneuro: "Normal tone, reflexes and gait; no focal signs; hearing and vision screening normal.", pskin: "No neurocutaneous stigmata.",
      "m-app": "Active, wriggles on the chair, touches everything; poor eye contact.", "m-speech": "Fluent but monotonous and pedantic; talks about trains; echolalia.", "m-mood": "Euthymic; affect appropriate.", "m-form": "Logical but tangential on his special interest.", "m-content": "No delusions; preoccupied with trains and timetables.", "m-perc": "No hallucinations.",
      "m-cog": "Oriented; attention easily distracted on testing; good memory for facts.", "m-ins": "Limited understanding of others’ feelings.",
    },
    exKey: ["pgen", "pneuro", "m-app", "m-speech", "m-cog", "pskin"],
    ix: [
      { id: "scale", group: "Bedside", label: "Standardised rating scales from parents and teachers (Conners/SNAP/ADHD-RS) and autism screening (M-CHAT-R/AQ-Child/ADOS referral)", result: "ADHD scales: elevated inattentive and hyperactive-impulsive scores in two settings. Autism screen: positive for social communication difficulties and restricted/repetitive behaviours.", meaning: "Suggests ADHD with co-occurring autism spectrum disorder (ASD).", use: "key" },
      { id: "hearing", group: "Bedside", label: "Hearing and vision assessment", result: "Normal.", meaning: "Excludes sensory impairment as the cause of inattention/poor communication.", use: "key" },
      { id: "iq", group: "Bedside", label: "Developmental/IQ and educational assessment (psychologist)", result: "Verbal IQ 108, performance IQ 112; reading in line with IQ.", meaning: "Normal intelligence; no learning disability; underachievement due to attention/social issues.", use: "useful" },
      { id: "lab", group: "Blood", label: "Basic screen: FBC, ferritin, TFT, lead (if exposure risk), ECG before stimulants", result: "Normal; ECG normal.", meaning: "No medical cause; safe for stimulant medication.", use: "useful" },
      { id: "eeg", group: "Other", label: "EEG/MRI brain", result: "Not done.", meaning: "", use: "low", note: "Not routinely indicated without neurological signs or seizures." },
      { id: "genetic", group: "Blood", label: "Fragile X/chromosomal microarray", result: "Not done.", meaning: "", use: "low", note: "Reserve for dysmorphism, learning disability or family history." },
    ],
    interpret: [mcq("ad-i1", "interpretation", "Symptoms of inattention and hyperactivity in more than one setting since age 4, plus lifelong social communication difficulty, restricted interests and rigid routines. Normal hearing and IQ. What is the best formulation?", [
      o("Autism spectrum disorder with co-occurring ADHD (combined presentation)", true, "Both conditions are frequent comorbidities."), o("ADHD only", false, "Misses the social communication deficits."), o("Oppositional defiant disorder", false, "No."), o("Normal active child", false, "Impairing."),
    ], ["How many settings?", "How early?", "Which social features?", "ASD + ADHD."], "DSM-5 allows both diagnoses in the same child.", { after: "scale" })],
    ddx: [
      { name: "ADHD with autism spectrum disorder", aliases: ["adhd", "autism", "asd", "autism spectrum disorder", "attention deficit", "adhd and autism", "neurodevelopmental disorder"], tier: "likely", why: "Early-onset pervasive inattention/hyperactivity and persistent social communication/behavioural rigidity.", for: ["Hyperactivity and inattention in school and home; delayed speech, solitary play, repetitive interests, sensory sensitivity"], against: ["None"], separate: { ask: "Onset, settings, social milestones", exam: "Eye contact, play, speech", ix: "Rating scales, ADOS" } },
      { name: "Hearing impairment / visual problem / lead poisoning / sleep disorder / epilepsy (absence)", aliases: ["hearing loss", "deafness", "visual impairment", "lead poisoning", "sleep apnoea", "epilepsy", "absence seizures"], tier: "possible", why: "Medical causes of inattention must be excluded.", for: ["Inattention"], against: ["Normal sensory screens, no staring spells"], separate: { ask: "Staring spells, snoring", exam: "Hearing, neurology", ix: "Audiometry, EEG if indicated" } },
      { name: "Intellectual disability / specific learning disorder / language disorder", aliases: ["intellectual disability", "learning disability", "dyslexia", "language disorder", "global developmental delay"], tier: "possible", why: "Academic failure could reflect cognitive or language impairment.", for: ["Poor school performance"], against: ["Normal IQ"], separate: { ask: "Milestones, reading", exam: "Language", ix: "IQ testing" } },
      { name: "Anxiety/depression, trauma, neglect or abuse, oppositional defiant/conduct disorder, foetal alcohol spectrum", aliases: ["anxiety", "depression", "trauma", "abuse", "neglect", "odd", "conduct disorder", "fasd", "foetal alcohol"], tier: "dangerous", why: "Psychosocial adversity and maltreatment must be considered in every child with behavioural problems.", for: ["Aggression with peers"], against: ["Pervasive lifelong pattern, supportive home"], separate: { ask: "Safety, bullying, home", exam: "Injuries, affect", ix: "Social assessment" } },
    ],
    twist: { text: "Six weeks after starting methylphenidate for ADHD the boy’s mother returns: his attention has improved, but he has lost 2 kg, sleeps poorly, and his heart rate is 112/min. A tic has appeared.", q: mcq("ad-tw", "management", "What is your best response?", [
      o("Review side effects: stimulants can reduce appetite, disturb sleep, raise heart rate/BP and unmask tics — adjust dose/timing, give with food, monitor growth and cardiovascular signs, consider switching (e.g. atomoxetine) if tics/side effects persist", true, "Careful monitoring."), o("Stop all treatment forever", false, "Premature."), o("Increase the dose immediately", false, "Worsens side effects."), o("Ignore the weight loss", false, "Monitor growth."),
    ], ["What are the stimulant side effects?", "What do you monitor?", "What are alternatives?", "Adjust and monitor."], "Behavioural/parent training and school support are part of treatment.") },
    dx: { q: mcq("ad-dx", "pathophysiology", "What is the neurobiological basis of ADHD and the mechanism of stimulants?", [
      o("Reduced dopamine/noradrenaline signalling in prefrontal-striatal circuits; stimulants (methylphenidate) increase synaptic dopamine and noradrenaline, improving attention and impulse control", true, "Catecholamine hypothesis."), o("Excess serotonin only", false, "No."), o("A structural brain tumour", false, "No."), o("A learned behaviour from poor parenting", false, "No."),
    ], ["Which transmitters?", "Which circuit?", "How do stimulants help?", "Dopamine/noradrenaline."], "Strong heritability."),
    },
    mgmt: mcq("ad-mx", "management", "Select correct management.", [
      o("Multimodal: psychoeducation for family/teachers, parent training, school accommodations (seating, breaks), behavioural therapy and social skills training", true, "First-line for all."), o("Pharmacotherapy for ADHD when moderate–severe: methylphenidate (first-line) or atomoxetine, with baseline BP/HR/weight/ECG and regular monitoring", true, "Evidence-based."), o("For autism: early intervention (speech and language, occupational therapy, structured routines, social communication programmes); no medication for core autism symptoms", true, "Therapies."), o("Treat comorbid anxiety/sleep problems, support family, ensure safeguarding; plan transition to adolescence/adulthood", true, "Holistic care."),
      o("Antipsychotics for hyperactivity alone", false, "Not first-line."), o("Blame and punishment", false, "Harmful."),
    ], ["What helps at school?", "Which medication?", "What helps autism?", "Multimodal."], "Early diagnosis improves outcomes."),
    consultant: [
      mcq("ad-c1", "consultant", "Core features of ADHD and ASD (select all true).", [
        o("ADHD: inattention and/or hyperactivity-impulsivity, onset before 12, in ≥2 settings, causing impairment", true, "DSM-5."), o("ASD: persistent deficits in social communication and interaction, plus restricted/repetitive behaviours and sensory differences, from early development", true, "DSM-5."), o("They can co-occur", true, "Common."), o("ASD is caused by vaccines", false, "Myth."),
      ], ["Onset?", "Settings?", "Social?", "First three."], "Vaccines do not cause autism."),
      mcq("ad-c2", "pathophysiology", "What important differentials and comorbidities should you consider in a child with behavioural problems?", [
        o("Hearing/visual impairment, epilepsy, sleep disorders, lead/iron deficiency, thyroid disease, anxiety/depression, learning disorders, maltreatment", true, "A broad screen."), o("Only ADHD", false, "No."), o("Only parenting problems", false, "No."), o("None", false, "No."),
      ], ["Medical?", "Mood?", "Learning?", "First."], "Always assess safeguarding."),
      mcq("ad-c3", "consultant", "What would you worry about in the long term?", [
        o("School failure, bullying and social isolation", true, "Impact."), o("Anxiety, depression and self-harm in adolescence", true, "Comorbidity."), o("Substance misuse and accidents (untreated ADHD)", true, "Risk."), o("Missed diagnosis of autism/learning disability", true, "Under-recognition."),
      ], ["School?", "Mood?", "Risk?", "Diagnosis?"], "Early intervention and family support improve outcomes."),
    ],
    chain: { risk: "Genetics, prematurity, exposures in pregnancy, family history", patho: "Prefrontal-striatal catecholamine dysregulation (ADHD); altered neurodevelopment and social brain circuits (ASD)", symptoms: "Hyperactivity, inattention, impulsivity; social communication difficulty, rigidity, sensory sensitivity", signs: "Restless, poor eye contact, monotonous speech, echolalia, special interests", ix: "Rating scales, developmental history, hearing/vision, IQ, screening labs/ECG", dx: "ADHD (combined) with autism spectrum disorder", mx: "Psychoeducation, school support, behavioural therapy, stimulant/atomoxetine, speech/OT, family support", comp: "School failure, anxiety/depression, bullying, substance use" },
    mustKnow: ["ADHD requires symptoms before 12, in ≥2 settings, with impairment.", "ASD: social communication deficits + restricted/repetitive behaviours from early childhood.", "ADHD and ASD frequently co-occur.", "Exclude hearing/vision problems, epilepsy, sleep and medical causes.", "Multimodal treatment first; medication for moderate–severe ADHD with monitoring.", "Consider safeguarding and psychosocial factors.", "Vaccines do not cause autism."],
    thinkIf: [["Hyperactive + inattentive in school and home since age 4", "ADHD."], ["Delayed speech + solitary play + rigid routines + special interests", "Autism spectrum disorder."], ["Staring spells + inattention", "Absence epilepsy."]],
    revise: "ADHD autism",
  },
]
