import type { CaseDef } from "../types";
import { mcq, o } from "../templates";

export const PSYCH_1: CaseDef[] = [
  {
    id: "ps-delirium", rotation: "psychiatry", title: "‘Psychotic’ and agitated — brought by the police", level: 3, setting: "Casualty / psychiatric emergency", tags: ["delirium", "psychosis", "HIV", "organic cause", "agitation"], emergency: true,
    involved: ["Psychiatric", "Infective / immune", "Neurological", "Toxic / drug-related"],
    vignette: "A 24-year-old man is brought by the police after he was found shouting in a market, saying that snakes are crawling on his body. He is agitated and frightened, and keeps looking at the corners of the room.",
    hsets: ["psych"], esets: ["general", "mse", "neuro"],
    hx: {
      pc: "He says people are poisoning him. His cousin says it started 3 days ago, suddenly.", onset: "Over 3 days; he was normal last week. He is worse at night and calmer in the morning.", mood: "Frightened, irritable.", sleep: "Has not slept for 3 nights.", psychosis: "Sees snakes and ‘small people’ on his body (visual); hears people whispering.",
      cog: "Cousin says he sometimes doesn’t know the day or where he is; his concentration comes and goes; he has had fever, cough and headache for 4 days.", subst: "Chews khat occasionally; drank alcohol heavily last week, none for the last 3 days; denies cannabis.", meds: "Started antibiotics from a pharmacy 4 days ago; no regular medication; has lost weight over the last 3 months; has never had an HIV test.",
      "risk-self": "Denies suicidal thoughts.", "risk-other": "Threatened people he thinks are poisoning him; pushed a policeman.", past: "No previous psychiatric history.", fam: "No psychiatric illness in the family.", pers: "Mechanic; sociable; no previous aggression.", collat: "Cousin confirms fever, confusion at night, and recent weight loss and night sweats.",
      anx: "Very frightened.",
    },
    hxKey: ["onset", "psychosis", "cog", "subst", "meds", "collat"],
    ex: {
      vit: "BP 134/84, pulse 118/min, RR 24/min, SpO₂ 93%, temperature 38.9 °C, capillary glucose 6.4 mmol/L.", gcs: "GCS 14 — drowsy at times, then agitated; fluctuating.", mouth: "Dry mouth, oral thrush.", nodes: "Generalised lymphadenopathy.", hands: "Coarse tremor.", nutr: "Thin, wasted.", neck: "No neck stiffness.",
      "m-app": "Dishevelled, agitated, picking at his clothes, looks frightened.", "m-speech": "Rapid, rambling, and incoherent at times.", "m-mood": "Fearful, labile.", "m-form": "Disorganised, tangential; cannot follow a train of thought.", "m-content": "Persecutory ideas (poisoning) that change from minute to minute.",
      "m-perc": "Vivid visual hallucinations (snakes) and illusions; some auditory misperceptions.", "m-cog": "Disoriented to time and place; attention markedly impaired (cannot say months of the year backwards); poor short-term memory; fluctuates.", "m-ins": "No insight; judgment impaired.",
      cn: "Pupils equal and reactive; no papilloedema; no cranial nerve deficit.", tone: "Normal tone and power; reflexes brisk; plantars flexor.", sens: "Normal.", mening: "Neck supple.", speech: "Dysarthric when agitated.",
    },
    exKey: ["vit", "m-cog", "gcs", "mouth", "nodes", "m-perc"],
    ix: [
      { id: "glu", group: "Bedside", label: "Capillary glucose and malaria test", result: "Glucose 6.4; malaria RDT negative.", meaning: "Excludes hypoglycaemia and malaria as the cause.", use: "key" },
      { id: "hiv", group: "Blood", label: "HIV test (with counselling) and CD4", result: "HIV-1 positive; CD4 64 cells/µL.", meaning: "Advanced HIV: opportunistic infections and HIV-associated neuropsychiatric disease are likely.", use: "key" },
      { id: "cxr", group: "Imaging", label: "Chest X-ray", result: "Right lower-zone consolidation with bilateral perihilar interstitial infiltrates.", meaning: "Pneumonia (± PCP) — the source of fever, hypoxia and delirium.", use: "key" },
      { id: "uec", group: "Blood", label: "U&E, calcium, LFT, FBC, urinalysis", result: "Na 126, creatinine 130, WBC 3.2, Hb 9.0; urine normal.", meaning: "Hyponatraemia (SIADH from pneumonia) and anaemia worsen delirium.", use: "useful" },
      { id: "ct", group: "Imaging", label: "CT head ± lumbar puncture (CSF CrAg)", result: "CT: no mass lesion. LP: CrAg positive, opening pressure 34 cmH₂O.", meaning: "Cryptococcal meningitis is also present in advanced HIV.", use: "key" },
      { id: "udrug", group: "Blood", label: "Urine drug screen", result: "Positive for cannabinoids (cannabis).", meaning: "Contributory but not the main cause.", use: "useful" },
      { id: "eeg", group: "Other", label: "EEG / MRI brain as first-line tests", result: "Not done.", meaning: "", use: "low", note: "Not urgent; delirium is a clinical diagnosis and the cause needs bedside/blood tests." },
    ],
    interpret: [mcq("de-i1", "interpretation", "Fever, hypoxia, fluctuating consciousness, disorientation, visual hallucinations, CD4 64, CrAg positive. What is the correct diagnostic formulation?", [
      o("Delirium due to multiple medical causes (pneumonia/sepsis, cryptococcal meningitis, hyponatraemia) in advanced HIV — not primary psychosis", true, "Acute, fluctuating, attention impaired, organic cause identified."), o("Schizophrenia", false, "Course too acute; consciousness impaired."), o("Substance-induced psychosis", false, "Cannabis is incidental."), o("Mania", false, "No elevated mood."),
    ], ["Is consciousness/attention impaired?", "How fast was onset?", "Which kinds of hallucination?", "Delirium."], "Delirium is a medical emergency with high mortality; always look for the cause.", { after: "ct" })],
    ddx: [
      { name: "Delirium (acute organic brain syndrome) due to infection/HIV/metabolic causes", aliases: ["delirium", "acute confusional state", "organic psychosis", "acute organic brain syndrome", "toxic confusional state", "encephalopathy", "sepsis", "meningitis", "cryptococcal meningitis"], tier: "likely", why: "Acute onset over days, fluctuating course, impaired attention and disorientation, visual hallucinations, fever and abnormal vitals.", for: ["Acute fluctuating course, disorientation, impaired attention, visual hallucinations, fever, tachycardia, hypoxia"], against: ["None"], separate: { ask: "Onset, fluctuation, fever", exam: "Attention, orientation, vital signs", ix: "Glucose, infection screen, electrolytes, HIV, CT/LP" } },
      { name: "Schizophrenia / acute psychotic disorder", aliases: ["schizophrenia", "psychosis", "acute psychosis", "brief psychotic disorder", "schizophreniform"], tier: "possible", why: "Persecutory delusions and hallucinations are typical of psychosis, but consciousness is clear and orientation intact.", for: ["Persecutory delusions, hallucinations"], against: ["Fluctuating consciousness, disorientation, fever, visual hallucinations, acute onset"], separate: { ask: "Duration of illness, prodrome", exam: "Clear sensorium, auditory hallucinations", ix: "Exclude organic causes" } },
      { name: "Substance-induced psychosis / withdrawal (khat, cannabis, alcohol)", aliases: ["substance induced psychosis", "alcohol withdrawal", "khat psychosis", "cannabis psychosis", "intoxication", "withdrawal", "delirium tremens"], tier: "possible", why: "Khat, cannabis and alcohol can cause psychosis; withdrawal from alcohol can cause delirium tremens.", for: ["Khat, alcohol, cannabis"], against: ["Fever, hypoxia, lymphadenopathy, HIV risk"], separate: { ask: "Timing of use and symptoms", exam: "Tremor, autonomic signs", ix: "Drug screen, glucose" } },
      { name: "Neurological: cerebral malaria, meningitis/encephalitis, cerebral toxoplasmosis/lymphoma, temporal lobe epilepsy", aliases: ["cerebral malaria", "meningitis", "encephalitis", "toxoplasmosis", "epilepsy", "neurocysticercosis", "brain abscess"], tier: "dangerous", why: "Fever, confusion and hallucinations in an HIV risk patient — treatable and lethal if missed.", for: ["Fever, confusion"], against: ["Neck supple, no focal signs (so far)"], separate: { ask: "Headache, fits, travel", exam: "Neck stiffness, focal signs, papilloedema", ix: "Malaria test, CT, LP, CrAg" } },
    ],
    event: { when: "after-exam", title: "Dangerous agitation", text: "He becomes aggressive, throws a chair, tries to leave and strikes a nurse. He is sweating, tremulous and shouting.", vitals: "HR 130, BP 160/100, temperature 39.1 °C; escalating threat to staff.", q: mcq("de-ev", "emergency", "What do you do NOW? (select all)", [
      o("De-escalate verbally first; ensure staff safety and a calm low-stimulation environment; use minimal restraint only if needed", true, "Least restrictive approach."), o("If sedation is needed: low-dose benzodiazepine (lorazepam) or a short-acting antipsychotic (e.g. haloperidol) with monitoring; avoid over-sedation and treat the cause", true, "Cautious pharmacological control; benzodiazepine preferred in withdrawal/delirium."), o("Check vitals, glucose and oxygen; treat the medical cause urgently (IV antibiotics, treat meningitis, fluids, correct sodium slowly)", true, "Treat the underlying cause."), o("Give a large dose of haloperidol and discharge him to police custody", false, "Dangerous; ‘psychiatric’ label would miss the cause."),
    ], ["What comes first — safety or diagnosis?", "Which route to treat agitation?", "What is the real problem?", "Safety, de-escalate, treat the cause."], "Treat the cause of delirium; sedate lightly, only if necessary.") },
    dx: { q: mcq("de-dx", "pathophysiology", "What is the most important diagnosis to make?", [
      o("Delirium caused by treatable medical illness (pneumonia/sepsis, cryptococcal meningitis, hyponatraemia) in advanced HIV", true, "Reversible with treatment."), o("First-episode schizophrenia", false, "Mislabelling kills."), o("Substance-induced psychosis only", false, "Incomplete."), o("Bipolar mania", false, "No."),
    ], ["What distinguishes delirium from psychosis?", "Which findings are not primary psychiatric?", "What would you miss if you called it psychosis?", "Delirium from infection."], "Never label a patient with ‘psychosis’ before excluding delirium."),
    },
    mgmt: mcq("de-mx", "management", "Select correct management.", [
      o("Treat the causes: IV antibiotics for pneumonia/sepsis, antifungal (amphotericin B + flucytosine/fluconazole) for cryptococcal meningitis with therapeutic LPs, correct sodium slowly, oxygen and fluids", true, "The cause is the cure."), o("Nurse in a calm, well-lit room with reorientation, family presence, glasses/hearing aids and sleep protection; avoid restraints and polypharmacy", true, "Delirium prevention/management."), o("Use sedation sparingly (low-dose haloperidol or lorazepam) only for dangerous agitation; avoid benzodiazepines unless withdrawal/seizures", true, "Careful drug use."), o("HIV care: counselling, start ART at the right time after cryptococcal treatment, cotrimoxazole prophylaxis, screen for TB; collateral history and capacity assessment", true, "Long-term plan."),
      o("Admit to a psychiatric unit and start long-term antipsychotics", false, "Wrong diagnosis."), o("Discharge with benzodiazepines", false, "No."),
    ], ["What treats delirium?", "How do you keep staff safe?", "What about HIV?", "Treat the cause, nurse, cautious sedation."], "Capacity: assess before restraining or treating against will."),
    consultant: [
      mcq("de-c1", "consultant", "How do you distinguish delirium from schizophrenia? (select all true)", [
        o("Delirium: acute onset, fluctuating course, impaired consciousness and attention, disorientation, visual/tactile hallucinations", true, "Organic."), o("Schizophrenia: gradual onset, clear consciousness, intact orientation, auditory hallucinations, delusions, negative symptoms", true, "Functional."), o("Delirium is common in medical ward patients with infection, drugs and metabolic disturbance", true, "Prevalent."), o("Hallucinations always mean schizophrenia", false, "No."),
      ], ["Onset?", "Consciousness?", "Type of hallucination?", "First three."], "Attention testing (months backwards) is the best bedside test."),
      mcq("de-c2", "pathophysiology", "What is the mechanism of delirium?", [
        o("Acute disruption of neurotransmission (acetylcholine deficiency, dopamine excess), inflammation and global cerebral dysfunction from systemic illness", true, "Reversible encephalopathy."), o("A primary dopamine disease only", false, "No."), o("A fixed structural lesion", false, "No."), o("A learned behaviour", false, "No."),
      ], ["Which brain function fails?", "Which transmitter?", "Is it reversible?", "Global cerebral dysfunction."], "Elderly and HIV patients are most vulnerable."),
      mcq("de-c3", "consultant", "What would kill this patient and what else are you worried about?", [
        o("Cryptococcal meningitis with raised ICP and sepsis from pneumonia", true, "Life-threatening."), o("Missed medical illness due to ‘psychiatric’ labelling", true, "Diagnostic error."), o("Violence to self/others and complications of restraint", true, "Safety."), o("Withdrawal seizures", true, "If alcohol dependence."),
      ], ["What infection?", "What error?", "What risk?", "All."], "Always reconsider the diagnosis if the patient is not improving."),
    ],
    chain: { risk: "Advanced HIV, infection, alcohol/khat use, electrolyte disturbance", patho: "Systemic infection/inflammation + meningeal disease → global cerebral dysfunction with fluctuating arousal", symptoms: "Acute confusion, visual hallucinations, agitation, insomnia, fever", signs: "Disorientation, inattention, fluctuating GCS, tachycardia, fever, hypoxia, thrush, nodes", ix: "Glucose, malaria, HIV/CD4, CXR, U&E, CT, LP (CrAg)", dx: "Delirium due to pneumonia, cryptococcal meningitis and hyponatraemia in advanced HIV", mx: "Treat the causes, safe environment, cautious sedation, ART/cotrimoxazole", comp: "Death, raised ICP, aspiration, injury, long-term cognitive decline" },
    mustKnow: ["Acute onset + fluctuating consciousness + impaired attention = delirium until proven otherwise.", "Visual hallucinations suggest an organic cause.", "Always check glucose, vitals, infection and drug/alcohol history.", "Test HIV in any new psychiatric presentation in a high-risk patient.", "Treat the cause; sedate only when necessary.", "Benzodiazepines for alcohol withdrawal; avoid in other delirium unless needed.", "Document capacity and risk."],
    thinkIf: [["Agitated + hallucinating + acute onset + fever", "Delirium (infection, withdrawal, metabolic) not schizophrenia."], ["Clear consciousness + persecutory delusions + auditory voices for >1 month", "Schizophrenia."], ["Tremor + sweating + hallucinations after stopping alcohol", "Delirium tremens."]],
    revise: "delirium",
  },
  {
    id: "ps-schiz", rotation: "psychiatry", title: "Hearing voices and withdrawing from everyone", level: 2, setting: "Psychiatric outpatient clinic", tags: ["schizophrenia", "psychosis", "MSE", "risk assessment"],
    involved: ["Psychiatric"],
    vignette: "A 21-year-old university student is brought by his mother. Over the past six months he has stopped attending classes, rarely washes, talks to himself, and believes his lecturers are broadcasting his thoughts on the radio.",
    hsets: ["psych"], esets: ["general", "mse"],
    hx: {
      pc: "He says ‘there is a plan against me’ and refuses to explain more.", onset: "Gradual over 6 months, with a withdrawal phase for the year before.", mood: "Flat, little emotion.", sleep: "Sleeps erratically; poor appetite.", psychosis: "Hears two voices commenting on what he does and arguing; believes his thoughts are being broadcast and that the TV sends him messages.",
      cog: "No confusion, no head injury, no fever; fully aware of date and place.", subst: "Smokes cannabis occasionally in the last year; no heavy alcohol; no khat.", meds: "No regular medications; no medical illness; HIV test negative last year.", "risk-self": "Denies wanting to die.", "risk-other": "Says he is ‘ready to defend himself’ against those who talk about him; no actual violence.",
      past: "No previous treatment.", fam: "Maternal uncle ‘had mental illness’.", pers: "Was an average student, quiet; social withdrawal over a year; no trauma.", collat: "Mother confirms the deterioration; he stopped self-care, spends days in his room, talks to himself.", anx: "Suspicious but not panicking.",
    },
    hxKey: ["onset", "psychosis", "subst", "meds", "risk-self", "risk-other", "collat"],
    ex: {
      vit: "BP 118/74, pulse 80/min, RR 16, SpO₂ 99%, temperature 36.7 °C, glucose normal.", gcs: "Alert and oriented.", nutr: "Thin and unkempt.", hands: "Normal; no tremor.",
      "m-app": "Dishevelled, poor hygiene, avoids eye contact; sits with his head tilted as if listening.", "m-speech": "Sparse, slow, monotonous; long pauses.", "m-mood": "Blunted/flat affect; mood ‘fine’.", "m-form": "Loosening of associations; occasional thought blocking.", "m-content": "Delusions of reference (media messages), thought broadcast, persecution; no suicidal or homicidal intent expressed.",
      "m-perc": "Auditory hallucinations: two voices commenting in the third person; sometimes arguing.", "m-cog": "Fully oriented; attention and memory intact.", "m-ins": "No insight: ‘I am not sick; they are against me’. Judgment poor.",
    },
    exKey: ["m-perc", "m-content", "m-form", "m-cog", "m-ins", "vit"],
    ix: [
      { id: "med", group: "Blood", label: "Screen for organic causes: FBC, U&E, LFT, calcium, glucose, TFT, HIV, syphilis", result: "All normal; HIV negative; TFT normal.", meaning: "No medical cause found.", use: "key" },
      { id: "udrug", group: "Blood", label: "Urine drug screen", result: "Positive for cannabinoids.", meaning: "Cannabis is a risk factor but symptoms have persisted for 6 months.", use: "key" },
      { id: "ct", group: "Imaging", label: "CT/MRI brain (selected cases)", result: "Normal.", meaning: "Excludes structural lesion.", use: "useful" },
      { id: "eeg", group: "Other", label: "EEG", result: "Normal.", meaning: "Excludes temporal lobe epilepsy.", use: "useful" },
      { id: "baseline", group: "Blood", label: "Baseline for antipsychotics: weight, BMI, BP, fasting glucose, lipids, ECG (QTc)", result: "Normal baseline; QTc 410 ms.", meaning: "Needed before starting antipsychotics.", use: "key" },
      { id: "lp", group: "Other", label: "Lumbar puncture", result: "Not done.", meaning: "", use: "low", note: "No features of CNS infection; unnecessary." },
    ],
    interpret: [mcq("sz-i1", "interpretation", "Six months of third-person auditory hallucinations, thought broadcast, delusions of reference, flat affect, social withdrawal, clear consciousness and normal investigations. Which diagnosis fits best?", [
      o("Schizophrenia (first-episode)", true, "Characteristic symptoms for >1 month (6 months here) with functional decline."), o("Delirium", false, "Clear consciousness and long course."), o("Brief psychotic disorder", false, "Duration >1 month."), o("Bipolar mania", false, "Mood is flat, not elevated."),
    ], ["How long?", "Is consciousness clear?", "Which first-rank symptoms?", "Schizophrenia."], "Schneider’s first-rank symptoms: third-person hallucinations, thought broadcast, passivity.", { after: "med" })],
    ddx: [
      { name: "Schizophrenia (first episode)", aliases: ["schizophrenia", "first episode psychosis", "psychotic disorder", "psychosis"], tier: "likely", why: "Prolonged course with hallucinations, delusions, negative symptoms and decline in functioning, clear consciousness.", for: ["Third-person voices, thought broadcast, flat affect, withdrawal, family history"], against: ["None"], separate: { ask: "Duration, mood symptoms, substances", exam: "MSE, clear consciousness", ix: "Exclude organic/substance causes" } },
      { name: "Substance-induced psychotic disorder (cannabis)", aliases: ["cannabis psychosis", "substance induced psychosis", "drug induced psychosis", "khat psychosis"], tier: "possible", why: "Cannabis can precipitate or worsen psychosis.", for: ["Cannabis use"], against: ["Symptoms for 6 months, onset before heavy use"], separate: { ask: "Timing of use vs symptoms", exam: "Intoxication signs", ix: "Urine drug screen; persistence after abstinence" } },
      { name: "Mood disorder with psychotic features (bipolar/psychotic depression)", aliases: ["bipolar", "psychotic depression", "mania", "schizoaffective"], tier: "possible", why: "Psychosis can occur in severe mood episodes.", for: ["Psychosis"], against: ["Flat affect, no mood episodes"], separate: { ask: "Mood episodes, sleep", exam: "Mood congruence", ix: "Longitudinal history" } },
      { name: "Organic psychosis: delirium, epilepsy, neurosyphilis, HIV, brain tumour", aliases: ["delirium", "epilepsy", "temporal lobe epilepsy", "hiv", "neurosyphilis", "tumour", "encephalitis"], tier: "dangerous", why: "Must exclude medical causes before labelling primary psychosis.", for: ["Psychosis"], against: ["Clear consciousness, normal tests"], separate: { ask: "Head injury, fever, seizures", exam: "Attention, neurology", ix: "FBC, U&E, TFT, HIV, VDRL, CT" } },
    ],
    twist: { text: "Three days after you diagnose schizophrenia, his mother calls: he has stopped eating, says the voices are ordering him to ‘end it’ and has hidden a rope under his bed.", q: mcq("sz-tw", "emergency", "What is your most appropriate response?", [
      o("Urgent risk assessment: ask directly about command hallucinations, suicidal intent and plan; admit (voluntarily or under the Mental Health Act if needed), remove means, start antipsychotic, close observation", true, "Command hallucinations with a plan = high risk."), o("Reassure and arrange review next month", false, "Unsafe."), o("Prescribe long-term benzodiazepines and discharge", false, "No."), o("Tell the mother to ignore him", false, "No."),
    ], ["Is this low or high risk?", "What does a rope mean?", "Who must act today?", "Admit and treat."], "Asking about suicide does not plant the idea. Document risk and plan.") },
    dx: { q: mcq("sz-dx", "pathophysiology", "What is the neurochemical basis of the positive symptoms and how do antipsychotics work?", [
      o("Excess dopamine activity in the mesolimbic pathway; antipsychotics block D2 receptors (atypicals also act on 5-HT2A)", true, "Dopamine hypothesis."), o("Excess GABA", false, "No."), o("Low serotonin only", false, "No."), o("Low thyroid hormone", false, "No."),
    ], ["Which pathway?", "Which receptor is blocked?", "Which side effect results from nigrostriatal block?", "D2 blockade."], "Mesolimbic ↑ dopamine → positive symptoms; mesocortical ↓ → negative symptoms."),
    },
    mgmt: mcq("sz-mx", "management", "Select correct management of first-episode schizophrenia.", [
      o("Start an oral antipsychotic (e.g. risperidone, olanzapine or haloperidol) after baseline checks; monitor weight, metabolic parameters, extrapyramidal side effects and ECG", true, "First-line pharmacology."), o("Psychoeducation for patient and family, cognitive behavioural therapy for psychosis, family therapy, social support and occupational rehabilitation", true, "Psychosocial interventions."), o("Risk assessment at every visit; admit if high risk or lacking capacity; adherence support (long-acting injection if needed); avoid cannabis", true, "Relapse prevention."), o("Treat for at least 1–2 years before considering withdrawal; early intervention improves outcome", true, "Duration."),
      o("Admit and sedate without a plan", false, "No."), o("Use antidepressants alone", false, "No."),
    ], ["Which drug class?", "Which therapies add benefit?", "What about risk?", "Antipsychotic + psychosocial + risk."], "Clozapine for treatment-resistant schizophrenia."),
    consultant: [
      mcq("sz-c1", "consultant", "List positive and negative symptoms (select all).", [
        o("Positive: hallucinations, delusions, disorganised thought and behaviour", true, "Added experiences."), o("Negative: flat affect, alogia, avolition, social withdrawal", true, "Lost functions."), o("Cognitive symptoms: poor attention, memory and executive function", true, "Also present."), o("Positive symptoms respond poorly to antipsychotics", false, "They respond best."),
      ], ["Which are ‘added’?", "Which are ‘lost’?", "Which treatment works?", "First three."], "Negative symptoms respond poorly."),
      mcq("sz-c2", "pathophysiology", "Name important antipsychotic side effects (select all).", [
        o("Extrapyramidal: dystonia, parkinsonism, akathisia, tardive dyskinesia (D2 block in nigrostriatal pathway)", true, "Typicals more."), o("Hyperprolactinaemia (tuberoinfundibular D2 block)", true, "Galactorrhoea, amenorrhoea."), o("Metabolic: weight gain, diabetes, dyslipidaemia (olanzapine/clozapine)", true, "Monitor."), o("Neuroleptic malignant syndrome; QT prolongation; agranulocytosis with clozapine", true, "Serious."),
      ], ["Which pathways are blocked?", "Which hormone?", "Which drugs cause weight gain?", "All."], "Always monitor."),
      mcq("sz-c3", "consultant", "What would kill or harm this patient?", [
        o("Suicide (about 5–10% of people with schizophrenia)", true, "Highest-risk early after diagnosis."), o("Violence/self-neglect and homelessness", true, "Risks."), o("Physical illness (cardiovascular, metabolic) and substance misuse", true, "Reduced life expectancy."), o("Relapse from non-adherence", true, "Common."),
      ], ["What is the commonest cause of death?", "What affects physical health?", "What drives relapse?", "All."], "Holistic care includes physical health."),
    ],
    chain: { risk: "Family history, cannabis, urban/stress, male sex, late adolescence", patho: "Dopaminergic dysregulation (mesolimbic ↑, mesocortical ↓), neurodevelopmental factors", symptoms: "Voices, thought broadcast, delusions, withdrawal, neglect of self-care", signs: "Disorganised speech, flat affect, third-person hallucinations, poor insight, clear consciousness", ix: "Organic screen (FBC, U&E, TFT, HIV, VDRL, CT), urine drug screen, baseline metabolic", dx: "Schizophrenia (first-episode)", mx: "Antipsychotic, psychoeducation, CBTp, family therapy, risk management, adherence", comp: "Suicide, relapse, metabolic syndrome, homelessness, substance misuse" },
    mustKnow: ["Exclude organic and substance causes before diagnosing schizophrenia.", "Schizophrenia needs ≥1 month of symptoms (ICD-11); clear consciousness.", "First-rank symptoms: third-person voices, thought broadcast, passivity.", "Always assess suicide and harm-to-others risk and ask directly.", "Antipsychotic + psychosocial treatment; monitor metabolic effects.", "Clozapine for resistant cases (monitor WBC).", "Cannabis worsens prognosis."],
    thinkIf: [["Clear consciousness + 3rd-person voices + delusions >1 month", "Schizophrenia."], ["Acute onset + fluctuating consciousness", "Delirium."], ["Elevated mood + grandiosity + decreased need for sleep", "Mania."]],
    revise: "schizophrenia",
  },
  {
    id: "ps-depr", rotation: "psychiatry", title: "‘I can’t go on’ — low mood after a diagnosis", level: 2, setting: "Medical ward — liaison psychiatry", tags: ["depression", "suicide risk", "HIV", "MSE"], emergency: true,
    involved: ["Psychiatric", "Infective / immune", "Endocrine / metabolic"],
    vignette: "A 34-year-old woman, a mother of two, was diagnosed with HIV three months ago. The ward nurse refers her because she has stopped eating, is not taking her antiretroviral drugs and says, ‘My children will be better off without me.’",
    hsets: ["psych"], esets: ["general", "mse"],
    hx: {
      pc: "She says life has no meaning and she is a burden.", onset: "Low mood began after her diagnosis 3 months ago, and worsened after her husband left her 6 weeks ago.", mood: "Persistent low mood, nothing gives her pleasure, worse in the mornings; frequent tears.", sleep: "Wakes at 3 a.m. and cannot return to sleep; appetite poor, lost 7 kg.",
      anx: "Constant worry about the children and stigma.", psychosis: "No hallucinations; no delusions beyond guilt and hopelessness.", cog: "Slowed, poor concentration; no confusion or fluctuation.", subst: "No alcohol or drugs.", meds: "Efavirenz-based ART (not taking for 3 weeks); no steroids; no other medicines.",
      "risk-self": "Has thought of taking all her tablets; has saved them; has written a note for her children; no previous attempts.", "risk-other": "No thoughts of harming others.", past: "No previous episodes; mother had depression.", fam: "Mother treated for depression.", pers: "Previously functioning well; married, shop assistant.", collat: "Sister says she gave away her phone and told her to ‘look after the children’.",
    },
    hxKey: ["mood", "sleep", "risk-self", "risk-other", "meds", "collat", "psychosis"],
    ex: {
      vit: "BP 108/66, pulse 92, RR 16, SpO₂ 98%, temperature 36.8 °C, glucose normal.", nutr: "Thin, BMI 18.", mouth: "Dry; no thrush.", gcs: "Alert.",
      "m-app": "Poorly groomed, slow, tearful, avoids eye contact; psychomotor retardation.", "m-speech": "Slow, quiet, long pauses, brief answers.", "m-mood": "Mood ‘hopeless’; affect sad, constricted, non-reactive.", "m-form": "Slow but logical.", "m-content": "Guilt, worthlessness, hopelessness; active suicidal ideation with plan and intent; no delusions.",
      "m-perc": "No hallucinations.", "m-cog": "Oriented; attention reduced from poor concentration.", "m-ins": "Partial insight (‘I know I am low, but nothing will help’); judgment impaired by hopelessness.",
    },
    exKey: ["m-mood", "m-content", "m-app", "m-ins", "vit"],
    ix: [
      { id: "med", group: "Blood", label: "Screen for medical contributors: FBC, U&E, TFT, B12/folate, glucose, CD4/viral load", result: "Hb 10.1, TSH normal, B12 normal; CD4 280, viral load high (not on ART).", meaning: "Anaemia and HIV; no thyroid cause. Untreated HIV also contributes to low mood.", use: "key" },
      { id: "phq", group: "Bedside", label: "Structured screening: PHQ-9 and suicide risk assessment", result: "PHQ-9 score 23 (severe); suicidal ideation with plan and intent; protective factors: children, sister.", meaning: "Severe major depressive episode with high suicide risk.", use: "key" },
      { id: "ecg", group: "Bedside", label: "Baseline ECG before antidepressant", result: "Normal QTc.", meaning: "Safe to use an SSRI.", use: "useful" },
      { id: "ct", group: "Imaging", label: "CT brain", result: "Not done.", meaning: "", use: "low", note: "No neurological signs; not indicated." },
      { id: "eeg", group: "Other", label: "EEG", result: "Not done.", meaning: "", use: "low", note: "Not helpful." },
    ],
    interpret: [mcq("dp-i1", "interpretation", "Persistent low mood, anhedonia, early morning waking, weight loss, psychomotor retardation, guilt, and suicidal ideation with plan. What is the diagnosis and the immediate priority?", [
      o("Severe major depressive episode with high suicide risk — assess risk, ensure safety (admission/close observation), start treatment, and restart ART", true, "Safety first."), o("Adjustment disorder only", false, "Too mild."), o("Normal grief", false, "Pervasive and severe."), o("Bipolar mania", false, "No."),
    ], ["How many core symptoms?", "Is she safe?", "What is the plan?", "Severe MDE with high risk."], "Risk assessment: ideation, plan, intent, means, previous attempts, protective factors.", { after: "phq" })],
    ddx: [
      { name: "Major depressive disorder (severe, with suicidal ideation) triggered by HIV diagnosis and loss", aliases: ["depression", "major depression", "major depressive disorder", "mdd", "severe depression", "depressive episode"], tier: "likely", why: "Pervasive low mood, anhedonia, biological symptoms, hopelessness and suicidal plan.", for: ["Low mood, anhedonia, early waking, weight loss, retardation, guilt, SI with plan, family history"], against: ["None"], separate: { ask: "Core and biological symptoms", exam: "MSE affect and content", ix: "PHQ-9; exclude medical causes" } },
      { name: "Adjustment disorder / bereavement or normal reaction", aliases: ["adjustment disorder", "grief", "bereavement", "reaction to illness"], tier: "possible", why: "Stressors can produce an adjustment reaction, but severity and suicidality here exceed it.", for: ["Stressors"], against: ["Severe symptoms, functional impairment"], separate: { ask: "Duration and severity", exam: "Pervasive vs reactive mood", ix: "PHQ-9" } },
      { name: "Organic/medical or drug-related depression (HIV, anaemia, hypothyroidism, efavirenz)", aliases: ["hiv", "hypothyroidism", "anaemia", "efavirenz", "medication induced depression", "organic depression", "hiv associated neurocognitive disorder"], tier: "dangerous", why: "Medical causes and drugs (efavirenz) can cause or worsen depression.", for: ["HIV, anaemia"], against: ["Normal TFT/B12"], separate: { ask: "Drug timing, symptoms", exam: "Neurology, thyroid signs", ix: "TFT, B12, CD4" } },
      { name: "Bipolar depression / psychotic depression / substance use", aliases: ["bipolar", "bipolar depression", "psychotic depression", "substance use"], tier: "possible", why: "Always ask about previous mania and psychotic symptoms before prescribing antidepressants alone.", for: ["Depressed mood"], against: ["No mania or psychosis"], separate: { ask: "Past mania/hypomania", exam: "Psychotic features", ix: "Longitudinal history" } },
    ],
    event: { when: "after-exam", title: "Attempt in progress", text: "While you speak to the sister she suddenly leaves the ward. She is found in the toilet having swallowed a handful of tablets from her bag, including her sister’s paracetamol.", vitals: "Drowsy, HR 110, BP 100/60; unknown quantity ingested 20 minutes ago.", q: mcq("dp-ev", "emergency", "What do you do NOW? (select all)", [
      o("Treat as medical emergency: ABC, find out what/how much/when (paracetamol is likely); activated charcoal if <1 h and airway safe", true, "Overdose management."), o("Measure paracetamol level at 4 h (or start N-acetylcysteine immediately if time unknown/large ingestion) and monitor LFTs, INR, creatinine, glucose", true, "Paracetamol overdose is silent and fatal."), o("Close one-to-one observation; psychiatric assessment once medically fit; consider Mental Health Act", true, "Safety."), o("Wait and discharge once awake", false, "Dangerous."),
    ], ["What medical problem first?", "Which overdose is deadly but hidden?", "Which antidote?", "ABC, N-acetylcysteine, observation."], "Intentional overdose: always check paracetamol and salicylate levels.") },
    dx: { q: mcq("dp-dx", "pathophysiology", "What is the neurobiological/psychosocial model for her depression?", [
      o("Monoamine (serotonin/noradrenaline) dysfunction and HPA-axis hyperactivity with psychosocial stressors (stigma, loss) and genetic vulnerability; HIV and its treatment contribute", true, "Biopsychosocial."), o("Only a ‘weak will’", false, "No."), o("A purely hormonal disorder", false, "No."), o("A learned habit", false, "No."),
    ], ["Which transmitters?", "Which stress system?", "What triggered it?", "Biopsychosocial."], "Stigma and non-adherence create a vicious cycle."),
    },
    mgmt: mcq("dp-mx", "management", "Select correct management.", [
      o("Immediate safety: remove means, one-to-one observation, admit/secure environment; assess capacity and legal status", true, "Suicide risk."), o("Start an antidepressant (e.g. an SSRI such as sertraline/fluoxetine) with psychotherapy (CBT/problem-solving); monitor for early worsening of suicidality; consider ECT for severe/refractory or high-risk", true, "Evidence-based therapy."), o("Restart ART with adherence counselling (consider switching efavirenz if it contributes), treat anaemia, nutrition support, treat HIV stigma", true, "Treat the HIV and the depression together."), o("Involve family, social support, children’s care plans; follow-up closely after discharge (highest-risk period)", true, "Social safety net."),
      o("Prescribe tricyclic antidepressants in large quantities", false, "Dangerous in overdose."), o("Discharge with reassurance", false, "No."),
    ], ["What is the first step with suicide risk?", "Which drug class first line?", "Why restart ART?", "Safety, SSRI + therapy, ART, support."], "SSRIs take 2–4 weeks; benzodiazepines are not treatment."),
    consultant: [
      mcq("dp-c1", "consultant", "Outline a suicide risk assessment (select all).", [
        o("Ask directly about thoughts, plan, intent, means and previous attempts", true, "Direct questioning."), o("Identify risk factors (depression, hopelessness, HIV, loss, substance use) and protective factors (children, supports, help-seeking)", true, "Balance."), o("Decide on safety: observe/admit, remove means, safety plan", true, "Action."), o("Avoid the question to prevent giving ideas", false, "Myth."),
      ], ["Plan and intent matter.", "Who protects?", "What do you do?", "First three."], "Document your reasoning."),
      mcq("dp-c2", "pathophysiology", "Why do antidepressants take weeks and why monitor early on?", [
        o("They increase synaptic monoamines quickly but therapeutic effect requires receptor adaptation and neuroplasticity over 2–4 weeks; energy may return before mood, increasing risk early", true, "Delayed effect."), o("They are placebos", false, "No."), o("They only work in the morning", false, "No."), o("They cure in a day", false, "No."),
      ], ["Time course?", "What improves first?", "Why is risk higher?", "Delayed mood effect."], "Review in 1–2 weeks after starting."),
      mcq("dp-c3", "consultant", "What would harm this patient?", [
        o("Suicide (immediate) and overdose", true, "Priority."), o("Untreated HIV progression from non-adherence", true, "Medical."), o("Loss of custody/stigma and social isolation", true, "Social."), o("Chronic recurrent depression", true, "Long-term."),
      ], ["Think immediate, medical, social.", "What can you prevent today?", "What takes time?", "All."], "Integrated mental health and HIV care saves lives."),
    ],
    chain: { risk: "Family history, HIV diagnosis, stigma, loss of partner, poverty", patho: "Monoamine and HPA-axis dysregulation + psychosocial stress; HIV/drugs contribute", symptoms: "Low mood, anhedonia, insomnia (early waking), weight loss, guilt, hopelessness, suicidal ideation", signs: "Psychomotor retardation, sad constricted affect, poor self-care", ix: "PHQ-9, risk assessment, TFT/B12/FBC, CD4/VL", dx: "Severe major depressive disorder with suicidal ideation (and overdose)", mx: "Safety, SSRI + psychotherapy, restart ART, medical treatment of overdose, social support", comp: "Suicide, ART failure, malnutrition, chronicity" },
    mustKnow: ["Ask directly about suicide: plan, intent, means.", "Depression: low mood/anhedonia + biological symptoms for ≥2 weeks.", "Check medical contributors: HIV, thyroid, anaemia, drugs (efavirenz).", "SSRIs first-line; avoid TCAs in suicide risk.", "Overdose: always check paracetamol; give N-acetylcysteine.", "Restart ART and treat depression together.", "Follow up soon after discharge."],
    thinkIf: [["Low mood + early waking + weight loss + guilt", "Major depression."], ["Elevated mood + decreased need for sleep + grandiosity", "Mania/bipolar."], ["Low mood after bereavement < 2 weeks without functional decline", "Grief reaction."]],
    revise: "depression",
  },
]
