// Rapid-fire clinical question bank: short, single-best-answer, mixed across the five rotations. Each carries the reasoning.
import type { MCQ, Rotation, Skill } from "./types";
import { mcq, o } from "./templates";
import { seeded } from "./whyLadders";

export interface BankQ extends MCQ { rotation: Rotation; topic: string }

const Q = (id: string, rotation: Rotation, topic: string, skill: Skill, stem: string, right: string, wrong: [string, string, string], why: string, hint?: string): BankQ => ({
  ...mcq(`bk-${id}`, skill, stem, seeded([o(right, true, why), ...wrong.map((w) => o(w, false, "Not the best answer here."))], id), [hint ?? `Which diagnosis or action fits all the features, not just one?`, `The answer begins “${right.slice(0, 14)}…”.`], why),
  rotation, topic,
});

export const BANK: BankQ[] = [
  // ---------------- Medicine
  Q("m1", "medicine", "Cardiology", "differentials", "A 60-year-old has chest pain radiating to the back, BP 170/100 in the right arm and 120/70 in the left. What do you suspect?", "Aortic dissection", ["Stable angina", "Pericarditis", "Oesophageal spasm"], "A tearing pain radiating to the back with a blood-pressure difference between arms points to dissection. Do not give anticoagulant or thrombolytic."),
  Q("m2", "medicine", "Cardiology", "interpretation", "ECG: PR interval lengthens progressively until a P wave is not followed by a QRS. This is:", "Mobitz type I (Wenckebach)", ["Mobitz type II", "Third-degree block", "First-degree block"], "Progressive PR lengthening then a dropped beat is Wenckebach, usually at the AV node and often benign."),
  Q("m3", "medicine", "Respiratory", "interpretation", "ABG: pH 7.28, pCO₂ 8.5 kPa, HCO₃⁻ 30. This is:", "Acute-on-chronic respiratory acidosis", ["Metabolic acidosis", "Respiratory alkalosis", "Metabolic alkalosis"], "A low pH with high CO₂ is respiratory acidosis; the raised bicarbonate shows renal compensation, so it is chronic (COPD)."),
  Q("m4", "medicine", "Respiratory", "investigations", "The most useful first test in a patient with a unilateral pleural effusion is:", "Diagnostic pleural aspiration", ["CT head", "Spirometry", "Bronchoscopy"], "Sampling the fluid (protein, LDH, cells, ADA, culture) identifies the cause."),
  Q("m5", "medicine", "Endocrine", "emergency", "In DKA, which should be done before starting an insulin infusion?", "Check potassium and start fluids", ["Give a bicarbonate bolus", "Give oral glucose", "Start potassium-free fluids only"], "Insulin drives K⁺ into cells; if K⁺ is < 3.5 you must replace it first. Fluids come first."),
  Q("m6", "medicine", "Endocrine", "differentials", "Weight loss, tremor, sweating, tachycardia and a diffuse goitre with exophthalmos:", "Graves’ disease", ["Toxic adenoma", "Hashimoto’s thyroiditis", "Anxiety disorder"], "Exophthalmos is specific for Graves’ disease (an autoimmune TSH-receptor-stimulating disease)."),
  Q("m7", "medicine", "Renal", "investigations", "Which finding best distinguishes acute kidney injury from chronic kidney disease?", "Normal-sized kidneys on ultrasound with a recent rise in creatinine", ["Anaemia", "Proteinuria", "Hypertension"], "Small shrunken kidneys suggest chronicity; normal-sized kidneys and a rising creatinine suggest AKI."),
  Q("m8", "medicine", "Neurology", "emergency", "A patient has a CT-confirmed ischaemic stroke 2 hours after onset. The treatment is:", "Intravenous thrombolysis if no contraindication", ["Immediate heparin infusion", "Immediate lumbar puncture", "Dexamethasone"], "Alteplase within 4.5 hours of onset improves outcomes; a CT first excludes haemorrhage."),
  Q("m9", "medicine", "Infection", "differentials", "Fever, headache, neck stiffness and a petechial rash in a young adult:", "Meningococcal meningitis/septicaemia", ["Viral meningitis", "Migraine", "Tension headache"], "Petechiae suggest meningococcaemia: give antibiotics immediately — do not wait for the LP or CT."),
  Q("m10", "medicine", "Infection", "management", "A patient with TB starts RHZE. Which supplement prevents peripheral neuropathy?", "Pyridoxine (vitamin B₆)", ["Vitamin C", "Folic acid", "Calcium"], "Isoniazid depletes pyridoxine and causes neuropathy; give B₆ routinely."),
  Q("m11", "medicine", "Haematology", "differentials", "Microcytic anaemia with low ferritin in a 45-year-old man requires:", "Investigation for gastrointestinal blood loss", ["Iron alone and discharge", "B₁₂ injections", "Bone marrow biopsy first"], "Iron deficiency in a man or postmenopausal woman is GI cancer or bleeding until proved otherwise."),
  Q("m12", "medicine", "GI", "management", "A cirrhotic patient with ascites has fever and abdominal pain. The key test is:", "Diagnostic ascitic tap (neutrophils > 250/mm³)", ["CT head", "Urine dipstick", "ECG"], "Spontaneous bacterial peritonitis: ascitic neutrophils > 250 mm³; treat with ceftriaxone and albumin."),
  Q("m13", "medicine", "Pharmacology", "management", "A patient on an ACE inhibitor develops a persistent dry cough. The best step:", "Switch to an ARB", ["Add a second ACE inhibitor", "Stop all antihypertensives", "Add a diuretic only"], "Cough is bradykinin-mediated; ARBs do not cause it."),
  // ---------------- Obs & Gynae
  Q("o1", "obgyn", "Obstetrics", "emergency", "Eclamptic fit at 37 weeks. The first-line anticonvulsant is:", "Magnesium sulphate", ["Phenytoin", "Diazepam alone", "Carbamazepine"], "Magnesium reduces recurrent seizures and is superior to diazepam or phenytoin."),
  Q("o2", "obgyn", "Obstetrics", "differentials", "Painless fresh vaginal bleeding at 34 weeks with a soft uterus:", "Placenta praevia", ["Placental abruption", "Labour", "Uterine rupture"], "Praevia classically causes painless bleeding. Abruption is painful with a woody uterus."),
  Q("o3", "obgyn", "Obstetrics", "management", "Primary PPH after vaginal delivery with a soft boggy uterus. First action:", "Uterine massage, oxytocin and resuscitation", ["Hysterectomy", "Wait and watch", "Give ergometrine to a hypertensive woman"], "Atony is the commonest cause: massage, uterotonics, tranexamic acid, then escalate."),
  Q("o4", "obgyn", "Obstetrics", "differentials", "Positive pregnancy test, unilateral iliac fossa pain and an empty uterus on ultrasound:", "Ectopic pregnancy", ["Threatened miscarriage", "Appendicitis", "Molar pregnancy"], "Ectopic until proved otherwise — it is lethal."),
  Q("o5", "obgyn", "Obstetrics", "management", "A pregnant woman’s BP is 160/110 with proteinuria. Which antihypertensive is NOT safe?", "Enalapril (ACE inhibitor)", ["Labetalol", "Nifedipine", "Methyldopa"], "ACE inhibitors cause fetal renal damage; use labetalol, nifedipine or methyldopa."),
  Q("o6", "obgyn", "Obstetrics", "emergency", "Shoulder dystocia is managed first by:", "McRoberts manoeuvre with suprapubic pressure", ["Fundal pressure", "Immediate caesarean", "Traction on the head"], "Call for help, McRoberts and suprapubic pressure; avoid fundal pressure."),
  Q("o7", "obgyn", "Gynaecology", "differentials", "Fever, bilateral lower abdominal pain, cervical motion tenderness and purulent discharge:", "Pelvic inflammatory disease", ["Endometriosis", "Fibroids", "Ovarian cancer"], "PID: cervical motion tenderness with adnexal tenderness; treat early to protect fertility."),
  Q("o8", "obgyn", "Gynaecology", "investigations", "Postmenopausal bleeding needs:", "Endometrial assessment (transvaginal ultrasound ± biopsy)", ["Reassurance", "HRT only", "No investigation"], "Postmenopausal bleeding is endometrial cancer until proved otherwise."),
  Q("o9", "obgyn", "Obstetrics", "pathophysiology", "The most common cause of maternal death in Kenya is:", "Haemorrhage (with hypertensive disorders and sepsis)", ["Malaria alone", "Road traffic accidents", "Stroke"], "Obstetric haemorrhage remains the leading direct cause worldwide."),
  Q("o10", "obgyn", "Obstetrics", "management", "A Rhesus-negative mother has an antepartum haemorrhage. What must be given?", "Anti-D immunoglobulin", ["Vitamin K", "Folic acid", "Corticosteroids only"], "Sensitisation to fetal Rh-positive cells is prevented by anti-D."),
  // ---------------- Paediatrics
  Q("p1", "paeds", "Respiratory", "management", "A child has fast breathing and chest indrawing. According to IMCI, classify as:", "Severe pneumonia — admit and give antibiotics", ["No pneumonia", "Pneumonia — treat at home", "Asthma"], "Chest indrawing is a sign of severe pneumonia."),
  Q("p2", "paeds", "Infection", "emergency", "The first step for a convulsing child with fever is:", "Airway, oxygen, check glucose, then give a benzodiazepine", ["Lumbar puncture", "CT head", "Paracetamol only"], "ABC and glucose first, then terminate the seizure."),
  Q("p3", "paeds", "Nutrition", "management", "A child with kwashiorkor and shock should receive:", "Cautious IV fluids (10–15 ml/kg over 1 h) with reassessment", ["20 ml/kg bolus", "No fluids at all", "Free water orally"], "Children with SAM are prone to heart failure with large boluses."),
  Q("p4", "paeds", "Neonatology", "differentials", "A baby is yellow at 12 hours of age. The most likely cause is:", "Haemolysis (ABO/Rh incompatibility)", ["Physiological jaundice", "Breast-milk jaundice", "Biliary atresia"], "Jaundice in the first 24 hours is pathological until proved otherwise."),
  Q("p5", "paeds", "Gastroenterology", "management", "Some dehydration in a child with diarrhoea is treated with:", "ORS 75 ml/kg over 4 hours plus zinc", ["IV 20 ml/kg bolus", "Antibiotics for everyone", "Anti-diarrhoeals"], "Most diarrhoea needs fluids and zinc, not antibiotics."),
  Q("p6", "paeds", "Haematology", "emergency", "A child with sickle cell disease has fever 39 °C. The most important action is:", "Urgent assessment with blood culture and IV antibiotics", ["Paracetamol and home", "Blood transfusion", "Wait 48 hours"], "Functional asplenia — fever is sepsis until proved otherwise."),
  Q("p7", "paeds", "Respiratory", "management", "The best bronchodilator in an acute severe asthma attack in a child is:", "Nebulised salbutamol, with ipratropium and steroids", ["Oral theophylline", "Antibiotics", "Cough suppressants"], "Salbutamol first; add ipratropium in severe cases; give steroids early."),
  Q("p8", "paeds", "Development", "pathophysiology", "A 12-month-old cannot sit, has poor head control and lacks social smile. This suggests:", "Global developmental delay", ["Normal variation", "Hearing loss only", "Autism only"], "Missing multiple milestones across domains = global delay; investigate causes."),
  Q("p9", "paeds", "Cardiology", "differentials", "A newborn is blue and not improving with oxygen. This suggests:", "Cyanotic congenital heart disease", ["Respiratory distress syndrome", "Transient tachypnoea", "Anaemia"], "Failure of the hyperoxia test suggests a right-to-left shunt."),
  Q("p10", "paeds", "Malaria", "management", "Severe malaria in a child is treated first with:", "IV artesunate", ["Oral artemether-lumefantrine alone", "IV quinine as the first choice", "Chloroquine"], "Artesunate reduces mortality compared with quinine."),
  // ---------------- Surgery
  Q("s1", "surgery", "Trauma", "emergency", "In the primary survey, which is addressed FIRST?", "Airway with cervical-spine protection", ["Circulation", "Disability", "Exposure"], "ABCDE order is fixed; airway always comes first."),
  Q("s2", "surgery", "Abdomen", "differentials", "Pain beginning around the umbilicus, then localising to the right iliac fossa:", "Acute appendicitis", ["Gastroenteritis", "Constipation", "Renal colic"], "Visceral pain from the midgut moves to the right iliac fossa when the parietal peritoneum is involved."),
  Q("s3", "surgery", "Abdomen", "management", "Free air under the diaphragm on an erect CXR:", "Perforated viscus — urgent laparotomy", ["Normal finding", "Pneumonia", "Pancreatitis"], "A perforation needs resuscitation, antibiotics and surgery."),
  Q("s4", "surgery", "Burns", "management", "For a child with 15% TBSA burns, the first-day fluids are guided by:", "A burn formula (e.g. Parkland) plus maintenance, titrated to urine output", ["Oral sips only", "No fluids", "Fixed 500 ml bolus"], "Parkland: 4 ml × kg × %TBSA in 24 h, half in the first 8 hours."),
  Q("s5", "surgery", "Breast", "investigations", "A 45-year-old with a breast lump needs:", "Triple assessment: clinical examination, imaging and core biopsy", ["Mammogram only", "FNAC only", "Observation for 3 months"], "Triple assessment is the standard of care."),
  Q("s6", "surgery", "Vascular", "differentials", "A cold, pale, painful leg with absent pulses of sudden onset:", "Acute limb ischaemia", ["DVT", "Cellulitis", "Gout"], "The six Ps: pain, pallor, pulselessness, paraesthesia, paralysis, perishing cold; emergency vascular review."),
  Q("s7", "surgery", "Urology", "differentials", "A man cannot pass urine, with a distended painful bladder and an enlarged prostate:", "Acute urinary retention from BPH", ["UTI", "Renal colic", "Appendicitis"], "Catheterise and measure residual volume; look for the cause."),
  Q("s8", "surgery", "Thyroid", "management", "A solitary thyroid nodule is first investigated with:", "TSH and ultrasound-guided fine-needle aspiration", ["Radioiodine immediately", "CT chest", "Surgery without tests"], "Function and cytology decide management."),
  Q("s9", "surgery", "Hernia", "emergency", "A tender, irreducible, discoloured groin swelling with vomiting:", "Strangulated hernia — urgent surgery", ["Reducible hernia", "Lipoma", "Lymph node"], "Ischaemic bowel requires emergency operation."),
  Q("s10", "surgery", "Trauma", "emergency", "Hypotension, absent breath sounds and distended neck veins after chest trauma:", "Tension pneumothorax — needle decompression now", ["Cardiac tamponade only", "Simple rib fracture", "Pulmonary contusion"], "Decompress immediately; do not wait for an X-ray."),
  // ---------------- Psychiatry
  Q("y1", "psychiatry", "Psychosis", "differentials", "A fluctuating level of consciousness with visual hallucinations and disorientation:", "Delirium", ["Schizophrenia", "Mania", "Depression"], "Delirium is acute, fluctuating and usually medical; look for the cause."),
  Q("y2", "psychiatry", "Mood", "differentials", "Elevated mood, decreased need for sleep, grandiosity and pressured speech for 10 days:", "Mania (bipolar disorder)", ["Schizophrenia", "ADHD", "Panic disorder"], "Duration ≥ 7 days with these features is mania."),
  Q("y3", "psychiatry", "Risk", "management", "The best way to assess suicide risk is to:", "Ask directly about thoughts, plans, intent and means", ["Avoid the topic", "Ask only family", "Wait for them to mention it"], "Asking does not plant the idea; it opens the door to help."),
  Q("y4", "psychiatry", "Pharmacology", "management", "First-line drug for acute agitation due to alcohol withdrawal:", "A benzodiazepine, with thiamine", ["Haloperidol alone", "Phenytoin", "Amitriptyline"], "Benzodiazepines treat withdrawal and prevent seizures; antipsychotics lower the seizure threshold."),
  Q("y5", "psychiatry", "Pharmacology", "management", "A patient on lithium develops coarse tremor, vomiting and ataxia. This suggests:", "Lithium toxicity", ["Parkinson disease", "Alcohol withdrawal", "Serotonin syndrome"], "Dehydration, NSAIDs and ACE inhibitors raise lithium levels; check level and U&E."),
  Q("y6", "psychiatry", "Anxiety", "differentials", "Before diagnosing panic disorder you must exclude:", "Thyrotoxicosis, arrhythmia, hypoglycaemia and substance effects", ["Nothing is needed", "Only epilepsy", "Only dementia"], "Anxiety has many organic mimics."),
  Q("y7", "psychiatry", "Law", "management", "A psychotic patient poses a serious risk to others and lacks insight. The proper approach is:", "Detention and treatment under mental health legislation, with the least restrictive care", ["Discharge him", "Restrain without documentation", "Treat him covertly"], "Risk, illness and lack of capacity justify compulsory care under the Mental Health Act."),
  Q("y8", "psychiatry", "Child", "differentials", "A child with inattention and hyperactivity in school and at home, with onset before 12 years:", "ADHD", ["Normal child behaviour", "Conduct disorder only", "Autism only"], "Persistent symptoms in two or more settings before 12 years with impairment."),
  Q("y9", "psychiatry", "Pharmacology", "management", "A woman on valproate plans pregnancy. The key advice is:", "Switch to a safer alternative before conception because of teratogenicity", ["Continue unchanged", "Double the dose", "Stop all medication permanently"], "Valproate causes neural-tube and developmental harm."),
  Q("y10", "psychiatry", "Substance", "management", "Before giving glucose to an alcoholic with confusion, give:", "IV thiamine", ["Insulin", "Haloperidol", "Aspirin"], "Glucose can precipitate Wernicke’s encephalopathy in thiamine-deficient patients."),
];
