import type { ReasonDrill } from "./types";
import { o } from "./templates";

// "Backwards" reasoning: start from a finding and work out the mechanism, the system, the diseases, and what separates them.
export const REASON_DRILLS: ReasonDrill[] = [
  {
    id: "rd-oedema", finding: "Bilateral pitting leg oedema", context: "A 50-year-old presents with swollen ankles for two weeks.",
    mechanisms: [o("Raised capillary hydrostatic pressure (venous congestion)", true, "Right heart failure, venous obstruction, fluid overload."), o("Low plasma oncotic pressure (hypoalbuminaemia)", true, "Nephrotic syndrome, cirrhosis, malnutrition."), o("Sodium and water retention by the kidney", true, "Renal failure, nephritic syndrome, drugs (NSAIDs, amlodipine)."), o("Increased arterial pressure in the legs", false, "Not a recognised cause.")],
    systems: [o("Cardiovascular", true, "Heart failure, venous insufficiency."), o("Renal", true, "Nephrotic/nephritic syndrome, CKD."), o("Hepatic/GI", true, "Cirrhosis, protein-losing enteropathy."), o("Respiratory only", false, "Cor pulmonale is cardiac; pure lung disease does not cause oedema.")],
    diseases: [o("Heart failure", true, "Raised JVP, orthopnoea."), o("Nephrotic syndrome", true, "Periorbital oedema, frothy urine."), o("Cirrhosis with hypoalbuminaemia", true, "Ascites, spider naevi."), o("Drug-induced (NSAIDs, calcium-channel blockers)", true, "Always take a drug history."), o("Appendicitis", false, "Unrelated.")],
    ask: ["Orthopnoea / PND (cardiac)", "Facial puffiness and frothy urine (nephrotic)", "Alcohol, jaundice (liver)", "Drugs: NSAIDs, amlodipine, steroids", "One leg or both? Pain? (DVT)"],
    exam: ["JVP: raised in cardiac, low/normal in nephrotic and cirrhosis", "Ascites, spider naevi, liver size", "Periorbital oedema, blood pressure", "Calf tenderness for unilateral swelling"],
    ix: ["Urine dipstick / protein:creatinine", "Albumin and LFTs", "Urea, creatinine, electrolytes", "Echo / NT-proBNP", "Doppler if unilateral"], danger: "Heart failure with pulmonary oedema; DVT/PE if unilateral; AKI.",
  },
  {
    id: "rd-haemoptysis", finding: "Haemoptysis", context: "A 40-year-old coughs up blood-streaked sputum for three weeks.",
    mechanisms: [o("Mucosal/vascular erosion by infection or tumour", true, "TB cavities, bronchiectasis, carcinoma."), o("Raised pulmonary venous pressure", true, "Mitral stenosis, pulmonary oedema."), o("Pulmonary infarction (embolus)", true, "PE."), o("Upper GI bleeding aspirated", false, "That is haematemesis, not haemoptysis, though history must separate them.")],
    systems: [o("Respiratory", true, "Most causes."), o("Cardiovascular", true, "Mitral stenosis, PE, left heart failure."), o("Haematological", true, "Coagulopathy, anticoagulants."), o("Renal", true, "Goodpasture/vasculitis — pulmonary-renal syndromes.")],
    diseases: [o("Pulmonary tuberculosis", true, "Cavitating lesion, weight loss, night sweats; endemic in Kenya."), o("Lung cancer", true, "Smoker, weight loss, hoarse voice, clubbing."), o("Bronchiectasis / lung abscess", true, "Chronic purulent sputum."), o("Pulmonary embolism", true, "Pleuritic pain, risk factors."), o("Gastro-oesophageal reflux", false, "Doesn’t cause haemoptysis.")],
    ask: ["Weight loss, night sweats, TB contacts, HIV", "Smoking, hoarseness", "Chronic productive cough since childhood", "Pleuritic pain, leg swelling, recent surgery", "Anticoagulants"],
    exam: ["Clubbing, cachexia, lymph nodes", "Focal chest signs, bronchial breathing", "Mitral murmur (mid-diastolic), irregular pulse", "Calves"],
    ix: ["Chest X-ray", "Sputum GeneXpert / AFB ×3", "HIV test", "CT chest if CXR unclear", "FBC, INR", "D-dimer/CTPA if PE suspected"], danger: "Massive haemoptysis (airway compromise), TB with HIV, PE.",
  },
  {
    id: "rd-jaundice", finding: "Jaundice", context: "A 35-year-old has yellow eyes and dark urine for one week.",
    mechanisms: [o("Pre-hepatic: excess haemolysis (unconjugated bilirubin)", true, "Malaria, sickle cell, G6PD."), o("Hepatic: hepatocyte injury or failure of conjugation/excretion", true, "Viral hepatitis, drugs, alcohol."), o("Post-hepatic: obstruction to bile flow (conjugated bilirubin, pale stool)", true, "Gallstones, pancreatic head cancer."), o("Excess carotene in the diet", false, "Skin only; sclerae stay white.")],
    systems: [o("Haematological", true, "Haemolysis."), o("Hepatic", true, "Hepatitis, cirrhosis."), o("Biliary / pancreatic", true, "Obstruction."), o("Neurological", false, "Not a cause.")],
    diseases: [o("Acute viral hepatitis (A, B, E)", true, "Prodrome, raised ALT in the hundreds–thousands."), o("Malaria / haemolysis", true, "Fever, anaemia, unconjugated bilirubin."), o("Gallstone obstruction / cholangitis", true, "Pain, fever, rigors (Charcot)."), o("Drug-induced liver injury (paracetamol, anti-TB)", true, "Always ask about medicines."), o("Appendicitis", false, "Not a cause of jaundice.")],
    ask: ["Pale stools, dark urine, itching", "Fever, rigors, RUQ pain", "Drugs, alcohol, herbal remedies", "Risk exposures: injections, sexual, unsafe food/water", "Anaemia symptoms, family history of sickle cell"],
    exam: ["Pallor, spleen size (haemolysis)", "Liver size/tenderness, stigmata of chronic liver disease", "Murphy’s sign, palpable gallbladder", "Ascites, encephalopathy (asterixis)"],
    ix: ["Fractionated bilirubin (conjugated vs unconjugated)", "ALT/AST vs ALP/GGT pattern", "FBC, film, reticulocytes, malaria test", "Hepatitis serology", "INR (synthetic function)", "Ultrasound (dilated ducts)"], danger: "Fulminant hepatic failure (encephalopathy, high INR), ascending cholangitis, severe malaria.",
  },
  {
    id: "rd-hyponatraemia", finding: "Hyponatraemia (Na 118 mmol/L) with confusion", context: "A 68-year-old woman on a diuretic is drowsy and vomiting.",
    mechanisms: [o("Excess water relative to sodium (dilutional)", true, "ADH excess (SIADH), polydipsia, heart failure, cirrhosis."), o("True sodium loss", true, "Diuretics, vomiting/diarrhoea, adrenal insufficiency."), o("Pseudohyponatraemia from high glucose/lipids", true, "Check glucose and lipids first."), o("Excess sodium intake", false, "That causes hypernatraemia.")],
    systems: [o("Renal / endocrine (ADH, adrenal)", true, "Kidney handling of water and sodium."), o("Cardiovascular (heart failure)", true, "Neurohormonal water retention."), o("Respiratory / neurological (SIADH causes)", true, "Pneumonia, lung cancer, CNS disease."), o("Musculoskeletal", false, "Not relevant.")],
    diseases: [o("Thiazide-induced hyponatraemia", true, "Common in the elderly."), o("SIADH (pneumonia, tumour, CNS disease, drugs)", true, "Euvolaemic, concentrated urine."), o("Heart failure / cirrhosis (hypervolaemic)", true, "Oedema and ascites."), o("Adrenal insufficiency / hypothyroidism", true, "Low cortisol impairs water excretion."), o("Hypoglycaemia", false, "Different problem.")],
    ask: ["Drug list (thiazides, SSRIs, carbamazepine)", "Vomiting, diarrhoea, fluid intake", "Weight loss, cough (lung cancer), headache", "Symptoms of adrenal/thyroid disease"],
    exam: ["Volume status: JVP, oedema, skin turgor, postural BP", "Heart failure and ascites signs", "Neurology (confusion, seizures)"],
    ix: ["Serum osmolality, glucose, lipids", "Urine sodium and osmolality", "Cortisol and TSH", "CXR (SIADH source)"], danger: "Seizures and cerebral oedema; correcting sodium too fast → osmotic demyelination (limit to ≤8–10 mmol/L per 24 h).",
  },
  {
    id: "rd-seizure", finding: "First generalised seizure in an adult", context: "A 28-year-old man had a witnessed tonic–clonic seizure for 2 minutes and is now drowsy.",
    mechanisms: [o("Structural cortical irritation", true, "Tumour, stroke, neurocysticercosis, abscess, trauma."), o("Metabolic derangement lowering the seizure threshold", true, "Hypoglycaemia, hyponatraemia, hypocalcaemia, uraemia."), o("Toxic / withdrawal", true, "Alcohol withdrawal, drugs, medication."), o("Infective inflammation", true, "Meningitis, encephalitis, cerebral malaria, HIV-related.")],
    systems: [o("Neurological", true, "Epilepsy and structural lesions."), o("Metabolic / endocrine", true, "Glucose, sodium, calcium."), o("Infective", true, "Meningitis, cerebral malaria, toxoplasmosis."), o("Toxic", true, "Alcohol, drugs.")],
    diseases: [o("Neurocysticercosis / brain lesion", true, "Common in endemic areas — CT/MRI."), o("Cerebral malaria / meningitis", true, "Fever, neck stiffness, travel."), o("Hypoglycaemia", true, "Always check glucose immediately."), o("Alcohol withdrawal", true, "Seizures 6–48 hours after stopping."), o("Primary epilepsy", true, "Diagnosis of exclusion after provoked causes."), o("Panic attack", false, "No post-ictal state.")],
    ask: ["Aura, tongue biting, incontinence, post-ictal confusion", "Fever, headache, head injury", "Alcohol and drug use, last drink", "Diabetes and medicines", "HIV status"],
    exam: ["Glucose at the bedside", "Temperature, neck stiffness", "Focal neurological deficit, papilloedema", "Tongue bite, injuries"],
    ix: ["Capillary glucose", "Electrolytes (Na, Ca, Mg), renal function", "Malaria test, HIV test", "CT head (and LP if meningitis suspected)", "EEG if recurrent"], danger: "Status epilepticus; hypoglycaemia; meningitis/encephalitis; raised ICP.",
  },
  {
    id: "rd-chestpain", finding: "Acute chest pain", context: "A 46-year-old man has sudden central chest pain.",
    mechanisms: [o("Myocardial ischaemia (supply–demand mismatch)", true, "ACS, stable angina."), o("Vascular tear or obstruction", true, "Aortic dissection, pulmonary embolism."), o("Pleural / pericardial inflammation", true, "Pleurisy, pericarditis, pneumonia."), o("Oesophageal or chest wall irritation", true, "GORD, spasm, costochondritis, herpes zoster.")],
    systems: [o("Cardiovascular", true, "ACS, dissection, pericarditis."), o("Respiratory", true, "PE, pneumothorax, pneumonia."), o("Gastrointestinal", true, "Reflux, oesophageal rupture, pancreatitis."), o("Musculoskeletal / psychiatric", true, "Costochondritis, panic.")],
    diseases: [o("Acute coronary syndrome", true, "Heavy, exertional, radiating, sweating."), o("Pulmonary embolism", true, "Pleuritic, dyspnoea, risk factors."), o("Aortic dissection", true, "Tearing, back, unequal BPs."), o("Tension pneumothorax", true, "Sudden dyspnoea, hyper-resonance, tracheal shift."), o("Pericarditis", true, "Pain eased by sitting forward."), o("Gastro-oesophageal reflux", true, "Burning, meals, antacid response.")],
    ask: ["Character, radiation, exertional, duration", "Pleuritic or positional?", "Sudden tearing, back pain", "Dyspnoea, cough, fever", "Risk factors: diabetes, smoking, immobility, surgery"],
    exam: ["Both arm BPs, pulses, murmurs", "Chest: air entry, percussion, trachea", "Calves", "Pericardial rub, JVP"],
    ix: ["ECG within 10 min", "Troponin (serial)", "Chest X-ray", "D-dimer/CTPA if PE probable", "Echo / CT aortogram if dissection suspected"], danger: "STEMI, aortic dissection, PE, tension pneumothorax, tamponade — treat the emergencies first.",
  },
  {
    id: "rd-pbleed", finding: "Vaginal bleeding in pregnancy", context: "A 27-year-old woman is bleeding per vagina.",
    mechanisms: [o("Implantation outside the uterus with rupture", true, "Ectopic pregnancy (early)."), o("Failure of the early pregnancy", true, "Miscarriage."), o("Placental separation or abnormal placental position", true, "Abruption, praevia (late)."), o("Cervical or uterine rupture/trauma", true, "Labour, scar rupture.")],
    systems: [o("Obstetric / gynaecological", true, "All of the above."), o("Haematological", true, "Coagulopathy (DIC after abruption)."), o("Surgical (ruptured ectopic)", true, "Needs laparotomy."), o("Neurological", false, "Not relevant.")],
    diseases: [o("Ectopic pregnancy (<12 weeks)", true, "Pain, amenorrhoea, shock."), o("Miscarriage (threatened/incomplete)", true, "Open os, products of conception."), o("Placenta praevia (>24 weeks)", true, "Painless, bright red."), o("Placental abruption", true, "Painful, woody uterus, DIC risk."), o("Uterine rupture", true, "Labour, scar, collapse."), o("Normal period", false, "Not in pregnancy.")],
    ask: ["Gestational age (LNMP, scan)", "Pain? Painless?", "Amount, colour, clots, trauma, intercourse", "Previous CS, PID, IUD, ectopic", "Hypertension (abruption), cocaine"],
    exam: ["Vital signs and shock index", "Uterine tone and tenderness, fundal height", "Fetal heart", "NO digital VE until praevia excluded", "Speculum for source"],
    ix: ["Urine/serum β-hCG", "Ultrasound (site, placenta)", "Haemoglobin, group & save/cross-match", "Clotting profile", "Kleihauer if rhesus negative"], danger: "Haemorrhagic shock; DIC; ruptured ectopic; fetal death.",
  },
  {
    id: "rd-fever-child", finding: "Fever in a 2-year-old", context: "A mother brings a hot, irritable child for two days.",
    mechanisms: [o("Pyrogen release from infection (bacterial, viral, parasitic)", true, "Cytokines raise the hypothalamic set-point."), o("Non-infective inflammation", true, "Kawasaki disease, juvenile arthritis."), o("Malignancy", true, "Leukaemia, lymphoma."), o("Heat exposure without a raised set-point", true, "Heat stroke, overwrapping (rarely).")],
    systems: [o("Infective (the commonest)", true, "Malaria, pneumonia, UTI, meningitis, otitis."), o("Haematological", true, "Leukaemia, sickle cell."), o("Rheumatological", true, "Kawasaki, JIA."), o("Endocrine", false, "Not typical at this age.")],
    diseases: [o("Malaria", true, "Endemic: test every febrile child."), o("Pneumonia", true, "Fast breathing, chest indrawing."), o("Meningitis", true, "Neck stiffness, bulging fontanelle, seizures."), o("Urinary tract infection", true, "Check urine in febrile children without a source."), o("Otitis media / tonsillitis", true, "Examine the ears and throat."), o("Appendicitis", false, "Uncommon at this age.")],
    ask: ["Danger signs (drinking, vomiting, convulsion, lethargy)", "Cough/fast breathing", "Diarrhoea, urinary symptoms", "Travel to malaria area", "Immunisation status, HIV exposure"],
    exam: ["Look sick? AVPU, RR, perfusion", "Neck stiffness, fontanelle, rash", "Chest, ears, throat", "Hepatosplenomegaly, pallor"],
    ix: ["Malaria RDT / smear", "Blood glucose", "Urinalysis/culture", "CXR if respiratory signs", "LP if meningitis suspected", "FBC, blood culture if very sick"], danger: "Severe malaria, meningitis, septic shock, severe pneumonia — treat danger signs first.",
  },
  {
    id: "rd-hallucinations", finding: "Hallucinations and agitation", context: "A 24-year-old is brought by the police, hearing voices and agitated.",
    mechanisms: [o("Primary psychotic disorder (dopaminergic dysregulation)", true, "Schizophrenia, bipolar mania with psychosis."), o("Substance intoxication or withdrawal", true, "Khat, cannabis, alcohol, stimulants."), o("Delirium from a medical cause", true, "Infection, metabolic, hypoxia, head injury."), o("Neurological disease", true, "Epilepsy, encephalitis, tumour, HIV.")],
    systems: [o("Psychiatric", true, "Functional psychosis."), o("Toxic / substance-related", true, "Common."), o("Infective / metabolic (delirium)", true, "Look for fever, hypoxia, hypoglycaemia."), o("Neurological", true, "Temporal lobe, encephalitis.")],
    diseases: [o("Schizophrenia", true, "Auditory hallucinations, clear consciousness, ≥1 month."), o("Substance-induced psychosis", true, "Temporal link with use; urine drug screen."), o("Delirium", true, "Fluctuating consciousness, visual hallucinations, disorientation."), o("Cerebral malaria / meningitis / HIV encephalopathy", true, "Fever, focal signs."), o("Bipolar mania with psychosis", true, "Elevated mood, reduced sleep."), o("Normal grief reaction", false, "Not with agitation and hallucinations like this.")],
    ask: ["Onset (sudden vs weeks), fluctuation through the day", "Substances and last use", "Fever, headache, head injury, seizures", "Sleep, mood, grandiosity", "Medications; family history"],
    exam: ["Vital signs, glucose, temperature", "Level of consciousness and orientation (attention!)", "Neurology and neck stiffness", "MSE: perception, thought form, insight", "Signs of intoxication/withdrawal"],
    ix: ["Capillary glucose, malaria test", "Electrolytes, renal and liver function, calcium", "HIV test", "Urine drug screen", "CT head / LP if indicated"], danger: "Delirium from a treatable medical cause (missed), risk to self/others, withdrawal seizures.",
  },
  {
    id: "rd-abdopain", finding: "Acute abdominal pain with vomiting", context: "A 30-year-old has severe abdominal pain for 12 hours.",
    mechanisms: [o("Inflammation of a hollow organ or peritoneum", true, "Appendicitis, cholecystitis, perforation."), o("Obstruction of a lumen", true, "Bowel obstruction, renal colic, biliary colic."), o("Vascular compromise", true, "Strangulation, mesenteric ischaemia, torsion."), o("Referred or metabolic pain", true, "DKA, basal pneumonia, MI, ectopic pregnancy.")],
    systems: [o("Gastrointestinal / surgical", true, "Most causes."), o("Gynaecological", true, "Ectopic, torsion, PID."), o("Urological / renal", true, "Colic, pyelonephritis."), o("Endocrine / metabolic and cardiac", true, "DKA, inferior MI.")],
    diseases: [o("Acute appendicitis", true, "Periumbilical → RIF, anorexia, fever."), o("Intestinal obstruction", true, "Colicky, vomiting, distension, constipation."), o("Perforated viscus / peritonitis", true, "Rigid abdomen, free air."), o("Ectopic pregnancy (woman of reproductive age)", true, "Always do a pregnancy test."), o("Acute pancreatitis", true, "Epigastric to back, alcohol/gallstones."), o("Ureteric colic", true, "Loin to groin, haematuria.")],
    ask: ["Site, onset, character, migration", "Vomiting, bowels, last flatus", "Last menstrual period (women)", "Urinary symptoms", "Previous surgery, hernia, alcohol"],
    exam: ["Vitals — shock/sepsis?", "Guarding, rebound, rigidity", "Hernial orifices, distension, bowel sounds", "Rectal exam; genital exam if indicated"],
    ix: ["Pregnancy test", "FBC, CRP, U&E, amylase", "Urinalysis", "Erect CXR / abdominal X-ray", "Ultrasound / CT"], danger: "Peritonitis, strangulation, ruptured ectopic, mesenteric ischaemia — urgent surgical review.",
  },
  {
    id: "rd-anaemia", finding: "Pallor with fatigue (Hb 5.8 g/dL)", context: "A 32-year-old woman is tired, breathless and pale.",
    mechanisms: [o("Reduced production (nutrient lack or marrow failure)", true, "Iron, B12, folate; aplastic anaemia, leukaemia."), o("Increased destruction", true, "Haemolysis: malaria, sickle cell, G6PD, autoimmune."), o("Blood loss", true, "GI, menorrhagia, hookworm."), o("Excess red cell production", false, "That causes polycythaemia, not anaemia.")],
    systems: [o("Haematological", true, "Primary disorder."), o("Gastrointestinal / gynaecological", true, "Occult loss."), o("Infective", true, "Malaria, hookworm, HIV."), o("Renal / chronic disease", true, "Reduced erythropoietin.")],
    diseases: [o("Iron-deficiency anaemia (chronic blood loss, poor diet, hookworm)", true, "Microcytic, low ferritin."), o("Megaloblastic anaemia (B12/folate)", true, "Macrocytic, neurological signs in B12."), o("Haemolytic anaemia (malaria, sickle cell)", true, "Jaundice, raised reticulocytes, LDH."), o("Anaemia of chronic disease/CKD", true, "Normocytic."), o("Leukaemia / marrow failure", true, "Pancytopenia, bleeding, infections.")],
    ask: ["Menstrual blood loss, melaena, diet", "Jaundice, dark urine, fever, malaria", "Family history of sickle cell/thalassaemia", "Drugs (NSAIDs), alcohol", "Neurological symptoms, weight loss"],
    exam: ["Pallor, koilonychia, jaundice, glossitis", "Spleen/liver, nodes", "Signs of heart failure", "Bruising, bleeding"],
    ix: ["FBC with MCV and film", "Reticulocyte count", "Ferritin, B12, folate", "Malaria test, stool for ova", "LDH, bilirubin, Coombs if haemolysis", "Bone marrow if pancytopenia"], danger: "Decompensation with Hb <5 g/dL — transfuse; severe malaria; leukaemia with pancytopenia.",
  },
  {
    id: "rd-goitre", finding: "Neck swelling that moves on swallowing", context: "A 38-year-old woman has a lump in the front of her neck.",
    mechanisms: [o("Diffuse enlargement from TSH/antibody stimulation or iodine deficiency", true, "Graves, endemic goitre."), o("Nodular hyperplasia or adenoma", true, "Multinodular goitre, toxic adenoma."), o("Inflammation of the gland", true, "Thyroiditis (Hashimoto, De Quervain)."), o("Malignant change", true, "Papillary, follicular, medullary, anaplastic.")],
    systems: [o("Endocrine", true, "Thyroid function."), o("Surgical (neck mass)", true, "Cancer and compression."), o("Immune", true, "Autoimmune thyroid disease."), o("Respiratory (compression)", true, "Stridor, retrosternal extension.")],
    diseases: [o("Graves’ disease", true, "Thyrotoxicosis, eye signs, diffuse goitre, bruit."), o("Multinodular goitre", true, "Common; may be toxic."), o("Hashimoto thyroiditis", true, "Hypothyroid, firm goitre."), o("Solitary nodule — carcinoma", true, "Hard, fixed, nodes, hoarse voice."), o("Thyroglossal cyst", false, "Midline, moves on tongue protrusion (not the gland itself).")],
    ask: ["Heat intolerance, weight loss, palpitations (hyper) vs cold intolerance, weight gain (hypo)", "Compression: dysphagia, dyspnoea, hoarseness", "Radiation, family history", "Rapid growth"],
    exam: ["Tremor, pulse, eye signs, pretibial myxoedema", "Shape: diffuse vs nodule, bruit", "Cervical nodes", "Pemberton sign"],
    ix: ["TSH, free T4 (±T3)", "Thyroid antibodies", "Ultrasound", "FNAC for nodules", "Isotope scan"], danger: "Thyroid storm; airway compression; anaplastic carcinoma.",
  },
];
