// Ward-round traps: the mistakes lecturers and consultants catch students on again and again.
import type { MCQ, Rotation } from "./types";
import { mcq, o } from "./templates";
import { seeded } from "./whyLadders";

export interface Trap { id: string; rot: Rotation | "all"; title: string; scenario: string; q: MCQ; lecturer: string }

const T = (id: string, rot: Trap["rot"], title: string, scenario: string, q: string, right: string, wrong: [string, string, string], why: string, lecturer: string, hint = "Think about what the consultant is trying to catch you on."): Trap => ({
  id, rot, title, scenario, lecturer,
  q: mcq(`tr-${id}`, "management", q, seeded([o(right, true, why), ...wrong.map((w) => o(w, false, "This is the trap."))], id), [hint, `The correct answer starts with “${right.slice(0, 16)}…”.`, `Key idea: ${right.slice(0, 50)}…`], why),
});

export const TRAPS: Trap[] = [
  T("oedema", "medicine", "All oedema is heart failure", "A patient has bilateral leg swelling. The student says: “Heart failure.”", "What is the trap?", "Oedema has many causes (cardiac, renal, hepatic, nutritional, venous, drugs); the JVP, urine protein and the history separate them", ["There is no trap — bilateral oedema is always cardiac", "It is always due to calcium-channel blockers", "Leg swelling is never important"], "Use Starling’s forces: raised hydrostatic pressure (heart, veins, fluid overload) or lowered oncotic pressure (nephrotic, liver, malnutrition) — and check the JVP.", "“Tell me how you know it is the heart.”"),
  T("pulse-bp", "all", "Confusing pulse rate with blood pressure", "A student reports: “His pressure is 110/min.”", "What is the problem?", "110/min is a pulse rate; BP is in mmHg. Always report each vital sign with its unit and interpret them together (e.g. shock index)", ["Nothing; they mean the same", "Pulse is measured in mmHg", "Blood pressure is measured in beats per minute"], "Vital signs are reported precisely: pulse (bpm), BP (mmHg), RR (breaths/min), SpO₂ (%), temperature (°C).", "“Rate or pressure? Units!”"),
  T("seizure", "medicine", "Seizure ≠ epilepsy", "A man has a first generalised fit after three days of fever and vomiting. The student writes ‘epilepsy’.", "What is the trap?", "A seizure is a symptom; epilepsy requires recurrent unprovoked seizures. First look for a provoked cause (infection, hypoglycaemia, electrolytes, drugs, stroke)", ["Epilepsy and seizure mean the same thing", "He should be started on lifelong anticonvulsants", "All fits are psychogenic"], "Check glucose, sodium, calcium, malaria, meningitis, drug or alcohol withdrawal, and imaging before calling it epilepsy.", "“Provoked or unprovoked?”"),
  T("psych", "psychiatry", "Calling every altered patient psychiatric", "A young man is agitated, hallucinating and fluctuates in orientation. The student says ‘acute psychosis’.", "What should you do first?", "Exclude delirium and organic causes: vitals, glucose, infection (malaria, meningitis), drugs, withdrawal and head injury", ["Start antipsychotics and admit to the psychiatric ward", "Send him home with family", "Tell him it is stress"], "Acute onset, fluctuating attention and disorientation or visual hallucinations suggest delirium until proved otherwise.", "“What is the medical cause?”"),
  T("single-test", "all", "Interpreting a result without the patient", "The student says: “Troponin is 2× normal so it is an MI.”", "What is the trap?", "A result must be interpreted in the clinical context and trend: troponin rises in many conditions (renal failure, sepsis, PE, HF)", ["Troponin is perfectly specific for MI", "Always repeat the test five times", "Ignore the troponin"], "Pre-test probability decides the meaning of any test. Flat mild elevation is chronic injury; a rise and fall suggests acute injury.", "“Does this fit the story?”"),
  T("drug-ae", "all", "Forgetting that drugs cause the problem", "An elderly man has AKI. The student orders a renal ultrasound but doesn’t look at the drug chart.", "What was missed?", "NSAIDs, ACE inhibitors, diuretics and metformin may be causing or worsening AKI — always take a drug history", ["Drugs never cause AKI", "Only antibiotics cause kidney injury", "Herbal medicines are always safe"], "Medication review is part of every history: prescribed, over-the-counter and herbal.", "“What is he taking?”"),
  T("emergency", "all", "Not recognising an emergency", "A patient with RR 34, SpO₂ 82% and BP 80/50 is being asked ten history questions.", "What should you do?", "Start ABCDE resuscitation immediately and call for help, taking the history in parallel", ["Complete the history first", "Order a CT before treating", "Wait for the senior"], "Treat life-threatening problems as you find them: A, B, C, D, E. History and examination run alongside.", "“What would kill him first?”"),
  T("glucose", "all", "Forgetting a bedside glucose", "A confused patient has a negative CT head but nobody has checked glucose.", "What is the lesson?", "Check capillary glucose in every patient with altered consciousness — it is quick, treatable and lethal if missed", ["Glucose is irrelevant", "Only diabetics get hypoglycaemia", "Wait for the lab"], "Hypoglycaemia mimics stroke, seizure and psychosis.", "“D in ABCDE is for glucose.”"),
  T("cpr-negative", "all", "Treating the result and not the patient", "A child with SpO₂ 97% is in severe respiratory distress with chest indrawing.", "What is the trap?", "Look at the child: work of breathing and danger signs outweigh a single reassuring number", ["Normal saturation excludes severe disease", "Chest indrawing is normal in children", "Children don’t need oxygen"], "Pulse oximetry can be normal in compensated respiratory failure, and in children the clinical signs are central.", "“Look at the child, not the monitor.”"),
  T("anchoring", "all", "Anchoring on the first diagnosis", "A patient with fever and confusion is called ‘malaria’ and no further tests are done.", "What is the error?", "Anchoring: malaria and bacterial meningitis can coexist — keep a differential and test for both", ["There is no error", "Fever always means malaria", "Meningitis can’t occur in the tropics"], "Always ask what else it could be and what the worst case is.", "“What else could it be?”"),
  T("hiv", "medicine", "Forgetting HIV", "A young woman with weight loss, cough and effusion is treated, but HIV isn’t tested.", "What is the lesson?", "Offer HIV testing in all patients with TB, pneumonia, meningitis and unexplained weight loss — it changes the diagnosis and treatment", ["HIV is irrelevant here", "Only offer testing to men", "Testing requires a lumbar puncture"], "HIV changes the pretest probability of TB, cryptococcus, PCP and drug choices.", "“What is her HIV status?”"),
  T("preg", "obgyn", "Forgetting to ask about pregnancy", "A 26-year-old woman collapses with abdominal pain. The student orders an abdominal CT.", "What is missing?", "A pregnancy test in every woman of reproductive age with abdominal pain or collapse — ectopic pregnancy is lethal", ["Pregnancy tests are only for obstetric wards", "CT is always safe in pregnancy", "She cannot be pregnant if she is menstruating"], "Always ask LMP and test: it changes imaging, drugs and diagnosis.", "“When was her last period?”"),
  T("ve-aph", "obgyn", "Doing a vaginal exam in antepartum bleeding", "A woman with painless bleeding at 33 weeks: the student prepares for a digital vaginal exam.", "What should you do first?", "Ultrasound to locate the placenta — a digital examination in placenta praevia can precipitate catastrophic bleeding", ["Perform a vaginal examination immediately", "Send her home", "Give oxytocin"], "Never perform a digital vaginal examination in antepartum haemorrhage until praevia is excluded.", "“Have you excluded praevia?”"),
  T("fluids", "paeds", "Giving fluids to every sick child the same way", "A severely malnourished child with oedema is given a 20 ml/kg bolus.", "What is the trap?", "In SAM, shock is treated cautiously (10–15 ml/kg over 1 h) with reassessment, because the heart is weak and fluid causes failure", ["Boluses are always safe", "Oedema means dehydration", "Children don’t get heart failure"], "SAM changes the rules of fluid resuscitation.", "“Is he malnourished?”"),
  T("dose", "paeds", "Using adult doses in children", "A 12 kg child is prescribed 500 mg of paracetamol.", "What is the problem?", "Children’s doses are calculated per kilogram and checked against the weight", ["Nothing, it is a standard dose", "Children need higher doses", "Weights are not needed"], "Always weigh the child and check mg/kg doses.", "“What does he weigh?”"),
  T("abd", "surgery", "Missing peritonitis because the abdomen is ‘soft’", "An elderly diabetic with abdominal pain has a soft abdomen and normal WCC. The student discharges him.", "What is the trap?", "Elderly, diabetic and immunosuppressed patients mask signs: use a low threshold for imaging and surgical review", ["Soft abdomen always excludes surgery", "Normal WCC rules out perforation", "Elderly patients never need CT"], "The absence of guarding does not rule out a surgical abdomen.", "“What are you missing?”"),
  T("hernia", "surgery", "Not examining the hernial orifices", "A man vomiting with a distended abdomen: the student orders X-rays without examining the groins.", "What is the lesson?", "Examine all hernial orifices in every patient with obstruction — a strangulated hernia is a common cause", ["Hernias never cause obstruction", "Examining the groin is unnecessary", "X-ray is always sufficient"], "Inspect and palpate the groin and umbilicus.", "“Where is the hernia?”"),
  T("suicide", "psychiatry", "Not asking about suicide", "A depressed woman is discussed. No one has asked about suicidal thoughts for fear of ‘putting ideas in her head’.", "What is the evidence-based rule?", "Ask directly about suicidal thoughts, plans, intent and means — asking does not increase risk", ["Never ask about suicide", "Wait for the patient to bring it up", "Only ask if she is crying"], "Direct questions reduce risk by opening the conversation.", "“Have you asked about suicide?”"),
  T("benzo-alcohol", "psychiatry", "Antipsychotics in alcohol withdrawal", "A man with DTs is given haloperidol alone.", "What is the trap?", "Benzodiazepines are the first-line treatment, and antipsychotics lower the seizure threshold; give thiamine first", ["Antipsychotics are first-line in DTs", "Withdrawal is not dangerous", "Give glucose before thiamine"], "Treat the withdrawal itself (benzodiazepines) and protect against Wernicke’s encephalopathy.", "“Thiamine before glucose?”"),
  T("anaemia-treat", "all", "Treating the number, not the cause", "A patient has Hb 6 g/dL and is transfused, with no cause sought.", "What is the lesson?", "Always find the cause of anaemia (blood loss, haemolysis, marrow, nutritional, chronic disease) and send a pre-transfusion sample", ["A transfusion is always the complete answer", "Anaemia needs no investigation", "Only iron deficiency causes anaemia"], "Transfusion treats the emergency; investigation treats the cause.", "“Why is he anaemic?”"),
  T("o2-copd", "medicine", "High-flow oxygen for everyone", "A COPD patient with SpO₂ 82% is placed on 15 L/min by mask and becomes drowsy.", "What went wrong?", "In chronic hypercapnic patients aim for SpO₂ 88–92%, as too much oxygen can worsen CO₂ retention", ["Oxygen is harmless", "Drowsiness is a sign of recovery", "They need no oxygen at all"], "Titrate oxygen to a target range and recheck blood gases.", "“What is the target saturation?”"),
  T("documentation", "all", "Not reassessing", "A patient was stable at 8 a.m. and nobody has rechecked at 2 p.m.", "What is the lesson?", "Repeat observations and reassess after every treatment — patients change, and early warning scores should trigger escalation", ["Once stable, always stable", "Only review if the family complains", "Observations are only for night staff"], "Deterioration is recognised by trends, not single readings.", "“When did you last check him?”"),
  T("consent", "all", "Forgetting capacity and consent", "A confused patient refuses treatment and the student argues with him.", "What is the correct approach?", "Assess capacity (understand, retain, weigh, communicate); treat in the patient’s best interests if he lacks capacity", ["Treat against his will without assessing capacity", "Accept any refusal as final", "Ask the porter"], "Capacity is decision-specific and can fluctuate.", "“Does he have capacity?”"),
];
