// "Cold patient" openings: the only thing the learner is told. No diagnosis, no history, no vitals — just why the nurse called you.

export const COLD: Record<string, string> = {
  "med-hf": "You have been asked to review a 62-year-old man in bed 7 who the nurse says is “getting more short of breath since this morning”. Proceed.",
  "med-acs": "A 55-year-old man has just walked into casualty looking unwell and sweaty. The triage nurse pulls you aside: “Doctor, please come now.” Proceed.",
  "med-tb": "You are asked to review a 34-year-old woman in the medical outpatient clinic who has been “coughing for a long time” and today looks more breathless when she walks in. Proceed.",
  "med-pe": "You have been asked to review a 38-year-old woman in bed 12 on the surgical ward, five days after her operation. The nurse says: “She suddenly doesn’t look right.” Proceed.",
  "med-stroke": "A 70-year-old man is wheeled into casualty by his wife. The nurse says: “He can’t talk properly and something is wrong with his right side.” Proceed.",
  "med-mening": "You have been asked to review a 24-year-old man in the casualty observation bay whose brother says he has become “very sleepy and confused since this morning”. Proceed.",
  "med-dka": "A 19-year-old woman is brought into casualty drowsy by a friend. The nurse says: “She keeps vomiting and she is breathing strangely.” Proceed.",
  "med-aki": "You have been asked to review a 58-year-old man in bed 4 who has been “very weak and barely passing urine” according to the night nurse. Proceed.",
  "med-malaria": "A 29-year-old man is brought by his brother to casualty from the lakeshore. He has had fever for days and is now “talking nonsense”. Proceed.",
  "med-gibleed": "You have been called to casualty: a 52-year-old man has just vomited a large amount of blood on the trolley. Proceed.",
  "ob-pe": "A 22-year-old woman, 36 weeks pregnant, is sitting in the antenatal clinic waiting room holding her head. The midwife asks you to see her before the others. Proceed.",
  "ob-aph": "A 31-year-old woman, 33 weeks pregnant, has just been brought to the maternity ward; the midwife says her clothes and the bed are soaked. Proceed.",
  "ob-pph": "You are the doctor on call in the labour ward. The midwife calls: “She delivered ten minutes ago and the bleeding doesn’t look right.” Proceed.",
  "ob-ectopic": "A 26-year-old woman has just collapsed at work and is brought to casualty by colleagues, holding her lower abdomen. Proceed.",
  "ob-labour": "You are asked to review an 18-year-old woman who has just been referred from a health centre to the labour ward after a long labour. Proceed.",
  "ob-pid": "You have been asked to review a 24-year-old woman in the gynaecology clinic who cannot sit upright because of lower abdominal pain. Proceed.",
  "pd-pneu": "A mother carries an 18-month-old girl into the paediatric casualty. The child is quiet and the mother says: “She won’t feed.” Proceed.",
  "pd-malaria": "A 4-year-old boy is rushed into paediatric casualty by his father. The nurse says: “He just had a fit and he is not waking properly.” Proceed.",
  "pd-dehyd": "A 9-month-old boy is carried into the paediatric clinic limp in his mother’s arms. Proceed.",
  "pd-sam": "A grandmother brings a 2-year-old girl to the clinic because “her feet are swollen and she is not herself”. Proceed.",
  "pd-neo": "A grandmother brings a 4-day-old baby boy to the newborn unit because “he will not suck”. Proceed.",
  "pd-scd": "A 7-year-old boy with a known blood condition is brought to casualty in pain and breathing fast. Proceed.",
  "pd-asthma": "A 6-year-old girl is rushed into the paediatric casualty by her mother. The child is making a noise when she breathes and cannot talk. Proceed.",
  "sg-appy": "You have been asked to review a 19-year-old man in the surgical casualty who has had belly pain since yesterday. Proceed.",
  "sg-obstruct": "You have been asked to review a 60-year-old man in the surgical casualty who is vomiting repeatedly and says his belly hurts in waves. Proceed.",
  "sg-trauma": "Ambulance pre-alert: a young man, motorbike versus lorry, arriving in two minutes. You are the doctor on call in the trauma bay. Proceed.",
  "sg-foot": "You have been asked to review a 58-year-old woman in bed 15 on the surgical ward whose nurse says her left foot “smells terrible” and she feels hot. Proceed.",
  "sg-burn": "A mother runs into casualty carrying a crying 3-year-old boy wrapped in a wet cloth. Proceed.",
  "sg-breast": "You are asked to see a 45-year-old woman in the surgical outpatient clinic, referred with a lump. Proceed.",
  "ps-delirium": "The police bring a 24-year-old man to casualty, saying he was “behaving madly” in the market. He is restrained and shouting. Proceed.",
  "ps-schiz": "A 21-year-old university student is brought to the psychiatry clinic by his mother, who says: “He is not himself any more.” Proceed.",
  "ps-depr": "The ward nurse refers a 34-year-old woman on the medical ward who “has stopped eating and says she doesn’t want to be here”. Proceed.",
  "ps-mania": "A woman of 29 is brought to casualty by her husband. He says: “She hasn’t slept for days and she is spending all our money.” Proceed.",
  "ps-dts": "You are called to the surgical ward at 2 a.m. to see a 45-year-old man on day 3 after a leg fracture: “He is agitated and he is pulling out his drip.” Proceed.",
  "ps-panic": "A 28-year-old woman rushes into casualty gasping and says: “Please, I am dying.” Proceed.",
  "ps-adhd": "A mother brings her 8-year-old son to the child clinic after a complaint from his school. Proceed.",
};
