// Drug reasoning: not "give ceftriaxone" but WHY — class, mechanism, adverse effects, cautions, dose, special populations.
// Dose lines are typical adult/paediatric teaching doses; local guidelines (e.g. Kenya Clinical Guidelines) take precedence.

export interface Drug {
  id: string; name: string; cls: string; why: string; mech: string;
  ae: string[]; caution: string; dose: string; special: string;
}

const d = (id: string, name: string, cls: string, why: string, mech: string, ae: string[], caution: string, dose: string, special: string): Drug => ({ id, name, cls, why, mech, ae, caution, dose, special });

export const DRUGS: Drug[] = [
  d("furosemide", "Furosemide", "Loop diuretic", "Removes excess salt and water fast in pulmonary oedema and fluid overload.", "Blocks the Na⁺-K⁺-2Cl⁻ cotransporter in the thick ascending limb of the loop of Henle.", ["Hypokalaemia, hyponatraemia, hypomagnesaemia", "Hypovolaemia and pre-renal AKI", "Ototoxicity at high IV doses", "Hyperuricaemia / gout"], "Anuria or hypovolaemia; caution with aminoglycosides (ototoxicity) and NSAIDs (blunt effect).", "20–80 mg IV (adult); 1 mg/kg IV (child). Watch urine output, K⁺ and creatinine.", "In renal impairment higher doses are needed to reach the tubule. In pregnancy avoid unless essential. In children dose by weight."),
  d("gtn", "Glyceryl trinitrate (GTN)", "Organic nitrate vasodilator", "Reduces preload (and afterload at high dose) and relieves ischaemic chest pain and pulmonary oedema.", "Releases nitric oxide → cGMP → venous (more than arterial) smooth-muscle relaxation.", ["Headache and flushing", "Hypotension", "Reflex tachycardia"], "Systolic BP < 90, right ventricular infarct, severe aortic stenosis, and recent phosphodiesterase-5 inhibitor (sildenafil).", "0.4 mg sublingual, repeat ×2; IV infusion titrated to BP in acute pulmonary oedema.", "Avoid in hypotension and RV infarction. Not routine in children."),
  d("aspirin", "Aspirin", "Antiplatelet (COX inhibitor)", "Stops platelets aggregating on a ruptured plaque in acute coronary syndrome and secondary prevention.", "Irreversibly acetylates COX-1, reducing thromboxane A₂.", ["Gastric irritation and GI bleeding", "Bronchospasm in aspirin-sensitive asthma", "Bleeding"], "Active peptic ulcer or bleeding, aspirin allergy; avoid in children < 16 (Reye’s syndrome) except in specific indications.", "300 mg chewed stat, then 75–100 mg daily.", "Avoid in children and late pregnancy unless advised. Reduced dose in severe renal impairment."),
  d("heparin", "Enoxaparin / heparin", "Anticoagulant (LMWH / UFH)", "Prevents clot extension in PE, DVT and ACS.", "Potentiates antithrombin → inactivates factor Xa (and thrombin for UFH).", ["Bleeding", "Heparin-induced thrombocytopenia", "Osteoporosis with long use"], "Active bleeding, severe thrombocytopenia, recent neurosurgery or haemorrhagic stroke.", "Enoxaparin 1 mg/kg SC 12-hourly (treatment) or 40 mg daily (prophylaxis). Use UFH if eGFR < 30.", "Reduce or avoid enoxaparin in renal impairment (UFH is safer). Safe in pregnancy (warfarin is not)."),
  d("alteplase", "Alteplase / streptokinase", "Thrombolytic (fibrinolytic)", "Dissolves the clot in STEMI when PCI is unavailable and in selected acute ischaemic stroke within the window.", "Converts plasminogen to plasmin, which lyses fibrin.", ["Bleeding including intracranial haemorrhage", "Hypotension and allergy (streptokinase)", "Reperfusion arrhythmias"], "Recent haemorrhage or surgery, uncontrolled hypertension, aortic dissection, bleeding disorder, previous haemorrhagic stroke.", "Dosed by protocol (stroke: 0.9 mg/kg, max 90 mg within 4.5 h).", "Contraindicated in pregnancy’s peripartum period and recent surgery."),
  d("ceftriaxone", "Ceftriaxone", "Third-generation cephalosporin (β-lactam)", "Broad bactericidal cover for meningitis, severe pneumonia, sepsis and PID.", "Binds penicillin-binding proteins and blocks bacterial cell-wall synthesis.", ["Allergy (cross-reactivity with penicillin)", "Diarrhoea and C. difficile", "Biliary sludging", "Kernicterus risk in jaundiced neonates; precipitates with calcium"], "Previous severe β-lactam anaphylaxis; avoid in neonates with hyperbilirubinaemia or receiving IV calcium.", "Adult 1–2 g IV daily (meningitis 2 g 12-hourly); child 50–100 mg/kg/day.", "No renal adjustment unless combined renal and hepatic failure. Safe in pregnancy. Neonate: use with caution."),
  d("ampicillin-gent", "Ampicillin + gentamicin", "β-lactam + aminoglycoside", "First-line empirical therapy for neonatal sepsis.", "Ampicillin blocks cell-wall synthesis; gentamicin binds the 30S ribosome and is bactericidal.", ["Nephrotoxicity and ototoxicity (gentamicin)", "Rash and allergy (ampicillin)", "Diarrhoea"], "Gentamicin: renal impairment, myasthenia gravis; monitor levels.", "Ampicillin 50 mg/kg 12-hourly (age-dependent); gentamicin 5 mg/kg once daily.", "Reduce frequency in renal impairment. In neonates dose by weight and gestation. Avoid gentamicin in pregnancy unless essential."),
  d("artesunate", "IV artesunate", "Artemisinin antimalarial", "Treatment of choice for severe malaria; clears parasites faster than quinine.", "Endoperoxide bridge generates free radicals that kill parasites, including young ring forms.", ["Post-artesunate delayed haemolysis", "Rarely hypersensitivity", "Neutropenia"], "Known hypersensitivity.", "2.4 mg/kg IV at 0, 12, 24 h then daily until oral therapy possible; follow with a full ACT course.", "Safe in children and in the 2nd/3rd trimester (and first trimester for severe disease)."),
  d("insulin", "Soluble insulin infusion", "Short-acting insulin", "Switches off ketogenesis and lowers glucose in DKA.", "Binds insulin receptors: glucose uptake, glycogen storage and suppression of lipolysis and ketone production.", ["Hypoglycaemia", "Hypokalaemia", "Hyponatraemia / cerebral oedema with rapid correction (children)"], "Start only when potassium ≥ 3.5 mmol/L.", "0.1 unit/kg/h fixed-rate IV infusion, with dextrose added when glucose < 14 mmol/L.", "Children: slower fluids and 0.05–0.1 unit/kg/h. Reduce dose in renal failure (reduced clearance)."),
  d("salbutamol", "Salbutamol (albuterol)", "Short-acting β₂-agonist", "Relieves bronchospasm in acute asthma and shifts potassium into cells in hyperkalaemia.", "Stimulates β₂ receptors → ↑cAMP → bronchial smooth-muscle relaxation; stimulates Na⁺/K⁺-ATPase.", ["Tremor", "Tachycardia and palpitations", "Hypokalaemia", "Lactic acidosis in high doses"], "Caution in tachyarrhythmias; mask-delivered doses cause hypokalaemia.", "Nebulised 2.5–5 mg (child < 5 y: 2.5 mg) every 20 min × 3; 10 mg nebulised for hyperkalaemia.", "Safe in pregnancy. In children use age-based dose."),
  d("ipratropium", "Ipratropium bromide", "Antimuscarinic bronchodilator", "Adds bronchodilation in severe asthma and COPD.", "Blocks M₃ receptors, reducing vagal bronchoconstriction.", ["Dry mouth", "Urinary retention", "Paradoxical bronchospasm (rare)"], "Glaucoma and prostatic enlargement (caution).", "250–500 µg nebulised with salbutamol, up to 4–6 hourly.", "Safe in pregnancy and children."),
  d("prednisolone", "Prednisolone / hydrocortisone", "Corticosteroid", "Reduces airway inflammation in asthma and acts in many inflammatory conditions.", "Binds glucocorticoid receptors, ↓ pro-inflammatory gene transcription.", ["Hyperglycaemia", "Fluid retention and hypertension", "Immunosuppression and infection", "Adrenal suppression with prolonged use", "Psychiatric effects"], "Untreated systemic infection; care in diabetes (monitor glucose).", "Prednisolone 1–2 mg/kg (max 40–60 mg) daily for 3–5 days; hydrocortisone 100 mg IV in severe attacks/anaphylaxis.", "Children dose by weight. In pregnancy prednisolone is preferred (placenta metabolises most of it)."),
  d("magsulph", "Magnesium sulphate", "Anticonvulsant / smooth-muscle relaxant", "First-line prevention and treatment of eclamptic seizures.", "NMDA antagonism and cerebral vasodilatation; also competes with calcium at the neuromuscular junction.", ["Loss of patellar reflexes", "Respiratory depression", "Hypotension", "Flushing and nausea"], "Myasthenia gravis; severe renal impairment (reduce maintenance dose).", "4 g IV loading over 5–20 min then 1 g/h (or IM regimen 5 g each buttock). Monitor reflexes, RR (>12), urine output (>30 ml/h).", "Antidote: 10 ml of 10% calcium gluconate IV. Reduce dose in renal impairment."),
  d("labetalol", "Labetalol / nifedipine", "Antihypertensive (α/β-blocker or CCB)", "Lowers dangerously high blood pressure in pregnancy and hypertensive emergency.", "Labetalol blocks α₁ and β receptors; nifedipine blocks L-type calcium channels, relaxing arterioles.", ["Labetalol: bradycardia, bronchospasm, postural hypotension", "Nifedipine: headache, flushing, reflex tachycardia, oedema"], "Labetalol: asthma, heart block. Nifedipine: severe aortic stenosis.", "Labetalol 20 mg IV then 40–80 mg every 10 min (max 300 mg); nifedipine 10 mg oral, repeat in 30 min.", "Both safe in pregnancy (ACE inhibitors and ARBs are not). Avoid sudden severe drops in BP (fetal perfusion)."),
  d("oxytocin", "Oxytocin", "Uterotonic (oxytocin receptor agonist)", "First-line drug for preventing and treating postpartum haemorrhage from uterine atony.", "Binds oxytocin receptors on myometrium, causing rhythmic contractions and compressing vessels.", ["Hypotension with rapid IV bolus", "Water intoxication with large volumes", "Uterine hyperstimulation and rupture in labour"], "Do not give a rapid bolus; do not use for induction in obstructed labour.", "10 IU IM/IV for prevention; infusion of 20–40 IU in 1 L at 125–250 ml/h for treatment.", "Safe in pregnancy and the postpartum period."),
  d("misoprostol", "Misoprostol", "Prostaglandin E₁ analogue", "Second-line uterotonic for PPH and where oxytocin is unavailable; cervical ripening.", "Binds prostaglandin receptors on myometrium → contraction; softens the cervix.", ["Fever and shivering", "Diarrhoea and nausea", "Uterine hyperstimulation"], "Not for uterine hyperstimulation or previous caesarean in induction (rupture risk).", "800 µg sublingual or 1000 µg rectal for PPH.", "Avoid in early pregnancy unless intentional (teratogenic/abortifacient)."),
  d("txa", "Tranexamic acid", "Antifibrinolytic", "Reduces death from bleeding in PPH and trauma when given within 3 hours.", "Blocks lysine-binding sites on plasminogen, preventing fibrin breakdown.", ["Thrombosis (rare)", "Seizures at high dose", "Nausea"], "Active thromboembolism; reduce dose in renal impairment.", "1 g IV over 10 minutes, repeat once after 30 minutes if bleeding continues.", "Reduce in renal impairment. Safe in pregnancy and postpartum."),
  d("benzylpen", "Benzylpenicillin / amoxicillin", "Penicillin (β-lactam)", "First-line for many childhood infections including pneumonia.", "Blocks cell-wall cross-linking through penicillin-binding proteins.", ["Allergy and anaphylaxis", "Rash", "Diarrhoea", "Seizures at very high doses in renal failure"], "Previous severe penicillin allergy.", "Amoxicillin 40–45 mg/kg twice daily (child pneumonia, 3–5 days); benzylpenicillin 50,000 IU/kg IV.", "Adjust in severe renal impairment. Safe in pregnancy."),
  d("ors-zinc", "ORS + zinc", "Oral rehydration therapy and mineral supplement", "Replaces water and electrolytes in diarrhoea and reduces duration and severity.", "Sodium–glucose co-transport in the gut drives water uptake even during secretory diarrhoea; zinc restores mucosal repair.", ["Vomiting if given too quickly", "Hypernatraemia if incorrectly mixed"], "Shock or ileus: use IV fluid instead.", "ORS 75 ml/kg over 4 h (some dehydration); zinc 20 mg daily × 10–14 days (10 mg if < 6 months).", "Safe at all ages. Low-osmolarity ORS preferred."),
  d("diazepam", "Diazepam / lorazepam / midazolam", "Benzodiazepine", "Stops seizures and treats alcohol withdrawal and severe agitation.", "Enhances GABA-A receptor chloride channel opening → neuronal inhibition.", ["Respiratory depression and hypotension", "Sedation and confusion", "Dependence and withdrawal", "Paradoxical agitation"], "Respiratory failure, severe hepatic impairment (caution), myasthenia; always have airway equipment.", "Diazepam 10 mg IV (child 0.3 mg/kg PR); lorazepam 4 mg IV; midazolam 0.2 mg/kg buccal.", "Lower doses in elderly and hepatic failure. In pregnancy use only for seizures."),
  d("haloperidol", "Haloperidol", "Typical antipsychotic (D₂ antagonist)", "Calms acute psychosis and agitation, including delirium when other measures fail.", "Blocks dopamine D₂ receptors in the mesolimbic pathway.", ["Extrapyramidal symptoms and acute dystonia", "QT prolongation", "Neuroleptic malignant syndrome", "Lowered seizure threshold"], "Parkinson disease, QT prolongation, alcohol withdrawal (lowers the seizure threshold — benzodiazepines are first).", "2.5–5 mg IM/oral, repeat after 30–60 min; maximum 20 mg/day.", "Lower doses in the elderly. Avoid in early pregnancy where possible."),
  d("risperidone", "Risperidone", "Atypical antipsychotic", "Long-term treatment of schizophrenia and mania with fewer motor side effects.", "Blocks D₂ and 5-HT₂A receptors.", ["Weight gain and metabolic syndrome", "Hyperprolactinaemia", "Extrapyramidal symptoms at higher doses", "Postural hypotension"], "Dementia (increased mortality), QT-prolonging drugs.", "2–6 mg daily, starting at 1–2 mg.", "Reduce dose in renal and hepatic impairment. Use cautiously in pregnancy."),
  d("fluoxetine", "Fluoxetine", "SSRI antidepressant", "First-line for depression and anxiety disorders.", "Blocks the serotonin reuptake transporter, increasing synaptic serotonin.", ["Nausea and GI upset", "Sexual dysfunction", "Insomnia and agitation initially", "Serotonin syndrome", "Hyponatraemia in the elderly"], "Take care with MAOIs, tramadol and triptans (serotonin syndrome); suicidality in the young in early weeks.", "20 mg daily; effect takes 2–4 weeks.", "Lower dose in hepatic impairment. Preferred SSRI in breast-feeding is sertraline."),
  d("lithium", "Lithium / sodium valproate", "Mood stabiliser", "Prevents manic and depressive relapses in bipolar disorder.", "Lithium modulates second-messenger systems (inositol, GSK-3); valproate enhances GABA and blocks sodium channels.", ["Lithium: tremor, polyuria (nephrogenic DI), hypothyroidism, toxicity", "Valproate: weight gain, hair loss, hepatotoxicity, teratogenicity"], "Lithium: renal impairment, dehydration, NSAIDs/ACE inhibitors raise levels. Valproate: pregnancy and liver disease.", "Lithium titrated to a level of 0.6–1.0 mmol/L; valproate 500–1500 mg daily.", "Avoid valproate in women of child-bearing age (neural tube defects). Lithium is cautioned in pregnancy and renal failure."),
  d("thiamine", "IV thiamine (Pabrinex)", "Vitamin B₁ replacement", "Prevents and treats Wernicke’s encephalopathy in alcohol dependence and malnutrition.", "Cofactor for pyruvate dehydrogenase and transketolase in glucose metabolism.", ["Anaphylaxis (rare, IV)", "Otherwise very safe"], "Always give before glucose in a malnourished or alcoholic patient.", "200–500 mg IV thiamine 8-hourly for 3–5 days.", "Safe in pregnancy and children (weight-based)."),
  d("rhze", "RHZE (rifampicin, isoniazid, pyrazinamide, ethambutol)", "Antituberculous combination", "Four drugs kill TB at different stages and prevent resistance.", "Rifampicin blocks RNA polymerase; isoniazid blocks mycolic acid synthesis; pyrazinamide acts in acidic environments; ethambutol blocks arabinosyl transferase.", ["Hepatotoxicity (all except ethambutol)", "Peripheral neuropathy (isoniazid; give pyridoxine)", "Optic neuritis (ethambutol)", "Orange body fluids and enzyme induction (rifampicin)", "Hyperuricaemia (pyrazinamide)"], "Hepatitis, optic neuritis (ethambutol), interactions with ARVs and contraceptives (rifampicin).", "Weight-banded fixed-dose combination; 2RHZE/4RH.", "Adjust ethambutol in renal impairment. Safe in pregnancy (except streptomycin). In children dose by weight."),
  d("metformin", "Metformin", "Biguanide", "First-line oral drug for type 2 diabetes.", "Reduces hepatic gluconeogenesis and improves peripheral insulin sensitivity.", ["GI upset", "B₁₂ deficiency", "Lactic acidosis in AKI or hypoxia"], "eGFR < 30, AKI, sepsis, contrast, severe hepatic impairment — stop it in acute illness.", "500 mg twice daily, titrate to 2 g/day.", "Contraindicated in significant renal impairment. Stop during acute illness (sick-day rule)."),
  d("morphine", "Morphine", "Opioid analgesic", "Strong pain relief in myocardial infarction, trauma, burns and sickle cell crisis.", "Agonist at µ-opioid receptors, reducing pain transmission.", ["Respiratory depression", "Nausea and vomiting", "Constipation", "Hypotension", "Sedation and dependence"], "Respiratory depression, head injury (masks neurology), biliary colic (sphincter spasm — caution).", "2.5–10 mg IV titrated (child 0.05–0.1 mg/kg).", "Reduce dose in renal impairment (active metabolite accumulates), elderly, children and neonates."),
  d("paracetamol", "Paracetamol", "Non-opioid analgesic / antipyretic", "Safe first-line analgesic and antipyretic.", "Central COX inhibition (precise mechanism incompletely understood).", ["Hepatotoxicity in overdose (NAPQI)", "Rarely rash"], "Severe liver disease and malnutrition lower the safe dose.", "1 g every 6 h (max 4 g/day); child 15 mg/kg every 4–6 h.", "Reduce dose in low weight, alcohol-related liver disease or malnutrition. Safe in pregnancy."),
  d("tetanus", "Tetanus toxoid ± immunoglobulin", "Vaccine / passive immunisation", "Prevents tetanus after contaminated wounds, burns and open injuries.", "Toxoid induces anti-toxin antibodies; immunoglobulin gives immediate passive cover.", ["Local pain and swelling", "Fever", "Anaphylaxis (very rare)"], "Previous severe reaction to a tetanus vaccine.", "0.5 ml IM toxoid; TIG 250–500 IU for high-risk wounds.", "Safe in pregnancy and children."),
  d("silver", "Silver sulfadiazine / burn dressings", "Topical antimicrobial", "Reduces infection in partial-thickness and deep burns.", "Silver ions disrupt bacterial membranes and DNA; sulfadiazine blocks folate synthesis.", ["Local skin irritation", "Leukopenia (rare)", "Delays healing if over-used"], "Sulfonamide allergy, neonates and late pregnancy (kernicterus risk).", "Thin layer daily under a non-adherent dressing.", "Avoid in sulfonamide allergy, neonates and pregnancy near term."),
  d("hydroxyurea", "Hydroxyurea / folic acid", "Antimetabolite (HbF inducer) / vitamin", "Reduces the frequency of sickle crises and acute chest syndrome.", "Raises fetal haemoglobin (HbF), which inhibits sickling.", ["Myelosuppression", "Teratogenicity", "Mouth ulcers and skin changes"], "Pregnancy; severe cytopenias.", "15–20 mg/kg/day titrated to blood counts.", "Monitor FBC; contraception needed. Folic acid 5 mg daily replaces ongoing marrow demand."),
  d("octreotide", "Terlipressin / octreotide", "Splanchnic vasoconstrictor", "Lowers portal pressure and controls variceal bleeding.", "Terlipressin is a vasopressin analogue (V₁); octreotide a somatostatin analogue reducing splanchnic inflow.", ["Terlipressin: ischaemia, hyponatraemia", "Octreotide: bradycardia, glucose disturbance"], "Terlipressin: ischaemic heart or peripheral vascular disease.", "Terlipressin 2 mg IV 4–6 hourly; octreotide 50 µg bolus then 50 µg/h.", "Use cautiously in coronary disease."),
  d("propranolol", "Propranolol", "Non-selective β-blocker", "Reduces portal pressure for variceal prophylaxis, and controls tremor and tachycardia in thyrotoxicosis.", "Blocks β₁ and β₂ receptors; reduces cardiac output and splanchnic flow.", ["Bradycardia and hypotension", "Bronchospasm", "Masks hypoglycaemia", "Fatigue and cold peripheries"], "Asthma, heart block, severe peripheral vascular disease, acute decompensated heart failure.", "20–40 mg 8–12 hourly titrated to heart rate.", "Avoid in asthma. Lower doses in hepatic failure."),
  d("ace", "Enalapril / lisinopril", "ACE inhibitor", "Improves survival in heart failure and protects the kidney in diabetes.", "Blocks conversion of angiotensin I to II → vasodilatation, less aldosterone, and reduced efferent arteriolar tone.", ["Dry cough", "Hyperkalaemia", "AKI in renal artery stenosis or volume depletion", "Angioedema", "Teratogenic"], "Pregnancy, bilateral renal artery stenosis, hyperkalaemia, AKI, hypotension.", "Enalapril 2.5 mg daily, titrate to 10–20 mg; check U&E in 1–2 weeks.", "Stop in pregnancy and during AKI (sick-day rule)."),
  d("spiro", "Spironolactone", "Mineralocorticoid antagonist (K⁺-sparing diuretic)", "Improves survival in heart failure and treats ascites in cirrhosis.", "Blocks aldosterone at the distal tubule, increasing Na⁺ and water loss and retaining K⁺.", ["Hyperkalaemia", "Gynaecomastia", "Menstrual disturbance", "AKI with ACE inhibitors"], "Hyperkalaemia, severe renal impairment, Addison’s disease.", "25–100 mg daily; monitor K⁺ and creatinine.", "Avoid in significant renal impairment. Not for pregnancy."),
  d("ca-gluc", "Calcium gluconate (IV)", "Cardiac membrane stabiliser", "Protects the heart in hyperkalaemia with ECG changes.", "Raises the threshold potential of cardiac myocytes, antagonising the depolarising effect of potassium.", ["Extravasation necrosis", "Bradycardia if given rapidly", "Hypercalcaemia"], "Digoxin toxicity (relative).", "10 ml of 10% IV over 2–5 min, repeat if ECG not normalised.", "It does not lower potassium — pair with insulin/dextrose and salbutamol."),
  d("ceftaz-meto", "Metronidazole", "Nitroimidazole antimicrobial", "Anaerobic and protozoal cover in PID, abdominal sepsis and diabetic foot.", "Reduced to cytotoxic radicals by anaerobes, damaging DNA.", ["Metallic taste and nausea", "Peripheral neuropathy with prolonged use", "Disulfiram-like reaction with alcohol"], "Avoid alcohol; caution in hepatic impairment.", "500 mg IV/oral 8-hourly (child 7.5 mg/kg).", "Reduce in severe hepatic impairment. Generally safe in pregnancy after the first trimester."),
  d("doxy", "Doxycycline", "Tetracycline antibiotic", "Chlamydia and atypical cover in PID and some tropical infections.", "Binds the 30S ribosomal subunit, blocking tRNA binding.", ["Photosensitivity", "Oesophagitis", "Tooth discolouration and bone effects in children", "Fetal harm"], "Pregnancy and children < 8 years.", "100 mg twice daily for 14 days (PID).", "Avoid in pregnancy, breast-feeding and young children."),
  d("gentamicin", "Gentamicin", "Aminoglycoside", "Concentration-dependent bactericidal drug for sepsis, intra-abdominal and urinary infections.", "Binds the 30S ribosomal subunit causing misreading of mRNA.", ["Nephrotoxicity", "Ototoxicity (cochlear and vestibular)", "Neuromuscular blockade"], "Renal impairment, myasthenia, concurrent loop diuretics or other nephrotoxins.", "5–7 mg/kg once daily IV (check levels).", "Reduce frequency in renal impairment. Avoid in pregnancy unless essential."),
  d("methylphenidate", "Methylphenidate", "CNS stimulant", "First-line medication for moderate-to-severe ADHD from age 6.", "Blocks dopamine and noradrenaline reuptake, improving prefrontal attention networks.", ["Reduced appetite and growth slowing", "Insomnia", "Tachycardia and hypertension", "Tics and irritability"], "Cardiac disease, psychosis, glaucoma, substance abuse.", "5 mg once or twice daily, titrate to effect.", "Monitor growth and blood pressure in children."),
  d("dextrose", "Dextrose 10% (IV)", "Glucose replacement", "Corrects hypoglycaemia, which is lethal and common in malaria, sepsis and the malnourished.", "Provides glucose as the brain’s main fuel.", ["Hyperglycaemia and hyponatraemia with large volumes", "Tissue necrosis if extravasated (50%)"], "Give thiamine before glucose in alcohol dependence.", "Child 2–5 ml/kg of 10% IV; adult 50 ml of 50%.", "In neonates use 10% only (2 ml/kg)."),
  d("oxygen", "Oxygen", "Medical gas", "Treats hypoxaemia; target SpO₂ ≥ 94% (88–92% in COPD).", "Raises the alveolar and arterial PO₂, improving tissue oxygen delivery.", ["Absorption atelectasis", "O₂ toxicity at high FiO₂ for long", "CO₂ retention in COPD"], "Avoid in paraquat poisoning; use targets in COPD.", "Titrate with a mask or nasal cannulae to target SpO₂.", "In neonates avoid hyperoxia (retinopathy of prematurity)."),
];

/** Which drug(s) each case turns on. */
export const CASE_DRUGS: Record<string, string[]> = {
  "med-hf": ["furosemide", "ace", "spiro"], "med-acs": ["aspirin", "morphine", "alteplase"], "med-tb": ["rhze"], "med-pe": ["heparin", "oxygen"],
  "med-stroke": ["alteplase", "aspirin"], "med-mening": ["ceftriaxone"], "med-dka": ["insulin", "dextrose"], "med-aki": ["ca-gluc", "salbutamol"],
  "med-malaria": ["artesunate", "dextrose"], "med-gibleed": ["octreotide", "ceftriaxone", "propranolol"],
  "ob-pe": ["magsulph", "labetalol"], "ob-aph": ["txa"], "ob-pph": ["oxytocin", "misoprostol", "txa"], "ob-ectopic": ["morphine"], "ob-labour": ["ceftriaxone", "oxytocin"], "ob-pid": ["ceftriaxone", "doxy", "ceftaz-meto"],
  "pd-pneu": ["benzylpen", "oxygen"], "pd-malaria": ["artesunate", "diazepam", "dextrose"], "pd-dehyd": ["ors-zinc"], "pd-sam": ["dextrose", "benzylpen"], "pd-neo": ["ampicillin-gent"], "pd-scd": ["morphine", "ceftriaxone", "hydroxyurea"], "pd-asthma": ["salbutamol", "ipratropium", "prednisolone"],
  "sg-appy": ["ceftriaxone", "paracetamol", "ceftaz-meto"], "sg-obstruct": ["morphine", "gentamicin"], "sg-trauma": ["txa", "tetanus", "morphine"], "sg-foot": ["ceftriaxone", "ceftaz-meto", "insulin"], "sg-burn": ["morphine", "silver", "tetanus"], "sg-breast": ["paracetamol"],
  "ps-delirium": ["haloperidol", "diazepam"], "ps-schiz": ["risperidone"], "ps-depr": ["fluoxetine", "paracetamol"], "ps-mania": ["lithium", "haloperidol"], "ps-dts": ["thiamine", "diazepam"], "ps-panic": ["propranolol", "fluoxetine"], "ps-adhd": ["methylphenidate"],
};

export const drugById = (id: string) => DRUGS.find((x) => x.id === id);
