import { FormEvent, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { Helmet } from "react-helmet-async";
import { CalendarDays, Check, Loader2, LockKeyhole } from "lucide-react";
import { useAuth } from "@/hooks/useAuth";
import { getAcademicYears,getUnitsForYear,type Unit } from "@/lib/academic";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";

type PlanItem={id:string;scheduled_date:string;resource_title:string|null;activity:string;estimated_minutes:number;status:string};
export default function RevisionPlanner(){const{user}=useAuth();const[year,setYear]=useState(3),[units,setUnits]=useState<Unit[]>([]),[selected,setSelected]=useState<string[]>([]),[date,setDate]=useState(''),[minutes,setMinutes]=useState(90),[items,setItems]=useState<PlanItem[]>([]),[loading,setLoading]=useState(false);
 useEffect(()=>{void getAcademicYears();getUnitsForYear(year).then(setUnits)},[year]);useEffect(()=>{if(!user)return;(supabase as any).from('revision_plan_items').select('id,scheduled_date,resource_title,activity,estimated_minutes,status').eq('user_id',user.id).order('scheduled_date').limit(100).then(({data}:any)=>setItems(data||[]))},[user?.id]);
 const generate=async(e:FormEvent)=>{e.preventDefault();if(!user||!date||!selected.length)return;setLoading(true);const chosen=units.filter(u=>selected.includes(u.id));const{data:plan,error}=await(supabase as any).from('revision_plans').insert({user_id:user.id,title:`Year ${year} revision plan`,unit_ids:selected,exam_date:date,daily_minutes:minutes,study_days:Math.max(1,Math.ceil((new Date(date).getTime()-Date.now())/86400000)),activity_types:['read','practice']}).select().single();if(!error&&plan){const days=Math.max(1,Math.ceil((new Date(date).getTime()-Date.now())/86400000));const rows=[];for(let i=0;i<Math.min(days,Math.max(7,chosen.length*3));i++){const u=chosen[i%chosen.length];const d=new Date();d.setDate(d.getDate()+i);rows.push({plan_id:plan.id,user_id:user.id,scheduled_date:d.toISOString().slice(0,10),unit_id:u.id,resource_title:u.name,activity:i%3===2?'practice questions':'review notes',estimated_minutes:Math.max(20,Math.floor(minutes/(i%2?2:1))),display_order:i})}const{data}=await(supabase as any).from('revision_plan_items').insert(rows).select();setItems(data||[])}setLoading(false)};
 const toggle=async(item:PlanItem)=>{const status=item.status==='completed'?'pending':'completed';setItems(v=>v.map(x=>x.id===item.id?{...x,status}:x));await(supabase as any).from('revision_plan_items').update({status}).eq('id',item.id)};
 if(!user)return <main className="mx-auto max-w-2xl px-5 py-16 text-center"><LockKeyhole className="mx-auto h-8 w-8 text-primary"/><h1 className="mt-3 font-serif text-3xl font-bold">Revision Planner</h1><p className="mt-2 text-muted-foreground">Sign in to create and save a personal examination plan.</p><Link to="/login" className="mt-5 inline-block rounded-lg bg-primary px-5 py-2.5 font-bold text-primary-foreground">Sign in</Link></main>;
 return <main className="mx-auto max-w-6xl px-5 py-8 sm:py-12"><Helmet><title>Revision Planner | OmpathStudy</title><meta name="robots" content="noindex"/></Helmet><div className="grid gap-8 lg:grid-cols-[360px_1fr]"><form onSubmit={generate} className="h-fit rounded-2xl border border-border bg-card p-5"><CalendarDays className="h-6 w-6 text-primary"/><h1 className="mt-3 font-serif text-2xl font-bold">Build your plan</h1><label className="mt-5 block text-xs font-bold">Academic year</label><select value={year} onChange={e=>{setYear(+e.target.value);setSelected([])}} className="mt-1 w-full rounded-lg border bg-background p-2.5">{[1,2,3,4,5,6].map(y=><option key={y} value={y}>Year {y}</option>)}</select><label className="mt-4 block text-xs font-bold">Units</label><div className="mt-2 max-h-56 space-y-1 overflow-auto">{units.map(u=><label key={u.id} className="flex items-center gap-2 rounded-lg p-2 text-sm hover:bg-muted"><input type="checkbox" checked={selected.includes(u.id)} onChange={()=>setSelected(v=>v.includes(u.id)?v.filter(x=>x!==u.id):[...v,u.id])}/>{u.name}</label>)}</div><label className="mt-4 block text-xs font-bold">Exam date</label><input type="date" min={new Date(Date.now()+86400000).toISOString().slice(0,10)} value={date} onChange={e=>setDate(e.target.value)} className="mt-1 w-full rounded-lg border bg-background p-2.5"/><label className="mt-4 block text-xs font-bold">Minutes per day</label><input type="number" min="20" max="480" value={minutes} onChange={e=>setMinutes(+e.target.value)} className="mt-1 w-full rounded-lg border bg-background p-2.5"/><Button disabled={loading||!date||!selected.length} className="mt-5 w-full">{loading?<Loader2 className="animate-spin"/>:'Generate plan'}</Button></form><section><h2 className="font-serif text-2xl font-bold">Your schedule</h2><p className="mt-1 text-sm text-muted-foreground">A balanced sequence of reading and question practice.</p><div className="mt-5 space-y-2">{items.length?items.map(i=><button key={i.id} onClick={()=>toggle(i)} className={`flex w-full items-center gap-3 rounded-xl border p-4 text-left ${i.status==='completed'?'border-primary/20 bg-primary/5':'border-border bg-card'}`}><span className={`flex h-7 w-7 items-center justify-center rounded-full border ${i.status==='completed'?'bg-primary text-primary-foreground':'border-border'}`}>{i.status==='completed'&&<Check className="h-4 w-4"/>}</span><span className="flex-1"><strong className="block text-sm">{i.resource_title}</strong><span className="text-xs text-muted-foreground">{i.scheduled_date} · {i.activity} · {i.estimated_minutes} min</span></span></button>):<p className="rounded-xl border border-dashed p-10 text-center text-muted-foreground">Choose units and an exam date to generate your schedule.</p>}</div></section></div></main>}
