// Cancer drugs: cytotoxic, hormonal/targeted, and the supportive-care drugs that make chemotherapy survivable.
// Teaching doses only; real regimens are set by the oncology team and calculated per body surface area.
import type { PDrug } from "./types";

const p = (group: string, id: string, name: string, cls: string, why: string, mech: string, ae: string[], caution: string, dose: string, special: string): PDrug => ({ group, id, name, cls, why, mech, ae, caution, dose, special });

export const CYTO = "Cancer: cytotoxic chemotherapy";
export const TARGET = "Cancer: hormonal and targeted";
export const SUPPORT = "Cancer: supportive care";

export const ONC_DRUGS: PDrug[] = [
  p(CYTO, "cyclophosphamide", "Cyclophosphamide", "Alkylating agent (nitrogen mustard)", "Backbone of many regimens: lymphomas including Burkitt, breast cancer, leukaemia; also used to suppress immunity in lupus nephritis and vasculitis.", "A prodrug activated by liver enzymes to phosphoramide mustard, which cross-links DNA strands so the cell cannot replicate. It acts in any phase of the cell cycle.", ["Myelosuppression (neutropenia)", "Haemorrhagic cystitis from the metabolite acrolein — prevent with fluids and mesna", "Nausea, vomiting and hair loss", "Infertility and a small risk of secondary bladder cancer or leukaemia"], "Active urinary infection or outflow obstruction, severe marrow suppression, pregnancy.", "Calculated per body surface area, e.g. 600 mg/m² IV every 3 weeks in breast cancer regimens.", "Teratogenic. Reduce the dose in renal impairment. Give generous fluids; add mesna for high doses."),
  p(CYTO, "doxorubicin", "Doxorubicin", "Anthracycline (topoisomerase II inhibitor)", "Active in breast cancer, lymphomas, sarcomas and Kaposi sarcoma.", "Inserts between DNA bases and inhibits topoisomerase II, and makes free radicals, causing DNA strand breaks.", ["Cardiotoxicity: dose-related cardiomyopathy (lifetime limit about 450–550 mg/m²)", "Myelosuppression", "Mucositis, nausea and alopecia", "Red urine (harmless); severe tissue necrosis if it leaks out of the vein"], "Heart failure or low ejection fraction, previous high-dose anthracycline or chest radiotherapy, severe liver impairment.", "About 60 mg/m² every 3 weeks in AC regimens; the cumulative dose is tracked and an echo is done before and during treatment.", "Reduce the dose if bilirubin is raised. Avoid in pregnancy. Dexrazoxane can lessen the heart damage."),
  p(CYTO, "cisplatin", "Cisplatin", "Platinum compound", "Cervical, lung, head and neck, testicular, ovarian and bladder cancers; sensitises tumours to radiotherapy in cervical cancer.", "Forms platinum–DNA cross-links that block replication and trigger cell death.", ["Kidney damage — hydrate and check creatinine and magnesium", "Severe nausea and vomiting (highly emetogenic)", "Ototoxicity: tinnitus and high-frequency hearing loss", "Peripheral neuropathy and low magnesium"], "Significant renal impairment, pre-existing deafness or neuropathy; avoid with aminoglycosides and loop diuretics.", "40 mg/m² weekly with radiotherapy for cervical cancer, or 75–100 mg/m² every 3 weeks, always with vigorous IV hydration.", "Avoid if eGFR is below about 45–60 (use carboplatin instead). Replace magnesium. Teratogenic."),
  p(CYTO, "carboplatin", "Carboplatin", "Platinum compound", "Gentler alternative to cisplatin for ovarian and lung cancer, and in patients with poor kidney function.", "Same DNA cross-linking as cisplatin but with less kidney, nerve and ear damage.", ["Myelosuppression, especially low platelets (dose-limiting)", "Nausea and vomiting (moderate)", "Allergic reactions after repeated cycles"], "Severe marrow suppression; the dose depends on kidney function.", "Dose is calculated from GFR (Calvert formula), target AUC 5–6, every 3 weeks.", "Because the dose follows GFR, renal impairment lowers the dose automatically."),
  p(CYTO, "vincristine", "Vincristine", "Vinca alkaloid (microtubule inhibitor)", "Part of lymphoma (CHOP), Burkitt and leukaemia regimens, Wilms tumour and Kaposi sarcoma.", "Binds tubulin so the mitotic spindle cannot form: cells are stuck in metaphase (M phase).", ["Peripheral neuropathy: tingling, foot drop, jaw pain", "Constipation and ileus from autonomic neuropathy", "Tissue necrosis if it leaks out of the vein (a vesicant)", "Fatal if given into the spinal fluid", "Little bone-marrow suppression"], "NEVER intrathecal; existing neuropathy; liver impairment.", "1.4 mg/m² IV (maximum 2 mg), usually weekly or 3-weekly; give a laxative with it.", "Reduce the dose if bilirubin is raised. Syringes are labelled “for intravenous use only”."),
  p(CYTO, "methotrexate", "Methotrexate", "Antimetabolite (antifolate)", "Leukaemia, lymphoma, osteosarcoma (high dose), choriocarcinoma; low dose for rheumatoid arthritis, psoriasis and unruptured ectopic pregnancy.", "Blocks dihydrofolate reductase, so no thymidylate or purines are made (S phase). Folinic acid bypasses the block to rescue normal cells.", ["Myelosuppression", "Mouth ulcers and diarrhoea", "Liver damage and lung fibrosis/pneumonitis", "Kidney damage at high dose — hydrate and alkalinise the urine", "Teratogenic"], "Renal impairment, fluid in the abdomen or chest (it pools and is released slowly), NSAIDs, trimethoprim or cotrimoxazole together, pregnancy.", "Low dose 7.5–25 mg ONCE WEEKLY; high dose 1–12 g/m² with folinic acid rescue. Taking it daily by mistake can be fatal.", "Avoid in significant renal impairment. Give folic acid with low doses and folinic acid rescue for high doses or toxicity."),
  p(CYTO, "fluorouracil", "5-Fluorouracil (and capecitabine)", "Antimetabolite (pyrimidine analogue)", "Colorectal, breast, gastric and head-and-neck cancers; capecitabine is the oral prodrug.", "A metabolite blocks thymidylate synthase, stopping DNA synthesis; another is built into RNA.", ["Mouth ulcers and diarrhoea", "Myelosuppression", "Hand–foot syndrome (especially capecitabine)", "Coronary vasospasm and chest pain", "Severe, sometimes fatal toxicity in DPD deficiency"], "DPD deficiency; warfarin interaction (raises INR); angina.", "By body surface area, e.g. bolus plus a 46-hour infusion in FOLFOX; capecitabine twice daily for 2 of every 3 weeks.", "Reduce in liver or kidney impairment; avoid in pregnancy."),
  p(CYTO, "paclitaxel", "Paclitaxel (and docetaxel)", "Taxane (microtubule stabiliser)", "Breast, ovarian and lung cancers, and Kaposi sarcoma.", "Binds beta-tubulin and locks microtubules so they cannot disassemble, arresting mitosis.", ["Hypersensitivity reaction — premedicate with a steroid and antihistamine", "Peripheral neuropathy", "Neutropenia", "Hair loss, muscle and joint pain", "Fluid retention (docetaxel)"], "Previous hypersensitivity to the castor-oil carrier, severe neutropenia, liver impairment.", "175 mg/m² every 3 weeks or 80 mg/m² weekly, with premedication.", "Reduce the dose in liver impairment; avoid in pregnancy."),
  p(CYTO, "bleomycin", "Bleomycin", "Cytotoxic antibiotic (DNA strand-breaker)", "Hodgkin lymphoma (ABVD), testicular germ-cell tumours and squamous cell cancers.", "Binds iron and makes free radicals that break DNA. It barely suppresses the bone marrow.", ["Pulmonary fibrosis — cumulative, worsened by oxygen and radiotherapy", "Skin darkening and rash", "Fever or allergic-type reaction", "Little marrow suppression"], "Existing lung disease; reduced kidney function (excreted by the kidney); avoid high-concentration oxygen.", "10–15 units/m² per cycle; lifetime limit about 400 units.", "Reduce the dose in renal impairment. Tell the anaesthetist before any operation."),
  p(CYTO, "etoposide", "Etoposide", "Topoisomerase II inhibitor", "Small-cell lung cancer, testicular cancer, lymphomas and leukaemia.", "Traps the topoisomerase II–DNA complex so DNA double-strand breaks accumulate.", ["Myelosuppression", "Nausea and hair loss", "Secondary leukaemia", "Low blood pressure if infused quickly"], "Severe marrow suppression; liver or kidney impairment.", "About 100 mg/m² IV on days 1–3 of each cycle.", "Reduce the dose if eGFR is below about 50 or the liver is impaired."),
  p(TARGET, "imatinib", "Imatinib", "Tyrosine-kinase inhibitor (BCR-ABL, KIT)", "Chronic myeloid leukaemia (Philadelphia chromosome) and GIST — it turned a fatal leukaemia into a chronic condition treated by tablets.", "Blocks the ATP site of the BCR-ABL fusion kinase, switching off its growth signal.", ["Fluid retention and swelling around the eyes", "Nausea, diarrhoea and muscle cramps", "Low blood counts and raised liver enzymes", "Rash"], "Liver impairment; drug interactions through CYP3A4 (rifampicin lowers levels); pregnancy.", "400 mg once daily with food in chronic-phase CML; response monitored by BCR-ABL levels.", "Teratogenic. Rifampicin (TB treatment) lowers imatinib levels, so the dose needs adjusting."),
  p(TARGET, "tamoxifen", "Tamoxifen", "Selective oestrogen receptor modulator", "Hormone-receptor-positive breast cancer, especially before the menopause.", "Blocks the oestrogen receptor in breast tissue (but acts like oestrogen on the uterus and bone).", ["Hot flushes", "Venous thromboembolism", "Endometrial thickening and cancer", "Vaginal discharge and irregular periods", "Cataracts"], "Previous clot, unexplained vaginal bleeding, pregnancy; strong CYP2D6 inhibitors such as fluoxetine and paroxetine reduce its effect.", "20 mg once daily for 5–10 years.", "Contraindicated in pregnancy. Any bleeding after the menopause must be investigated."),
  p(TARGET, "letrozole", "Letrozole (and anastrozole)", "Aromatase inhibitor", "Hormone-receptor-positive breast cancer after the menopause.", "Blocks aromatase, the enzyme that makes oestrogen from androgens in fat and muscle — the main oestrogen source after the menopause.", ["Bone loss and fractures — give calcium and vitamin D", "Joint and muscle pain", "Hot flushes and vaginal dryness", "Raised cholesterol"], "Premenopausal women (the ovaries override it unless suppressed), osteoporosis, pregnancy.", "Letrozole 2.5 mg or anastrozole 1 mg once daily.", "Only for postmenopausal women, or with ovarian suppression. Monitor bone density."),
  p(TARGET, "trastuzumab", "Trastuzumab", "Monoclonal antibody (anti-HER2)", "HER2-positive breast and stomach cancers — improves survival.", "Binds the HER2 receptor, blocking its growth signal and flagging the cell for immune attack.", ["Heart muscle weakness — monitor with echo", "Infusion reactions (fever, chills)", "Diarrhoea and rash"], "Low ejection fraction; avoid giving at the same time as anthracyclines; pregnancy (too little amniotic fluid).", "8 mg/kg loading then 6 mg/kg every 3 weeks IV, usually for a year.", "Contraindicated in pregnancy. Stop or pause if the ejection fraction falls."),
  p(TARGET, "rituximab", "Rituximab", "Monoclonal antibody (anti-CD20)", "B-cell lymphomas (R-CHOP) and chronic lymphocytic leukaemia; also some autoimmune diseases.", "Binds CD20 on B cells, which are then destroyed by complement and immune cells.", ["Infusion reactions", "Hepatitis B reactivation — screen before treatment", "Infections and low antibody levels", "Tumour lysis syndrome in bulky disease"], "Check HBsAg and anti-HBc first; serious active infection.", "375 mg/m² IV with each chemotherapy cycle.", "Avoid live vaccines; give hepatitis B prophylaxis if the core antibody is positive."),
  p(TARGET, "leuprorelin", "Leuprorelin (and goserelin)", "GnRH agonist (androgen deprivation)", "Prostate cancer; also breast cancer (to switch off the ovaries), endometriosis and fibroids.", "Continuous GnRH stimulation exhausts the pituitary, so LH and FSH fall and testosterone or oestrogen drops after an initial surge.", ["Tumour flare at the start — cover with an anti-androgen such as bicalutamide", "Hot flushes, loss of libido and erectile dysfunction", "Bone loss and metabolic changes", "Injection-site reactions"], "Metastatic disease near the spinal cord (flare can cause cord compression); pregnancy.", "Depot injection every 1 or 3 months (e.g. 3.75 mg monthly).", "Start an anti-androgen 1–2 weeks beforehand in advanced disease; monitor bone density."),
  p(TARGET, "bicalutamide", "Bicalutamide", "Non-steroidal anti-androgen", "Prostate cancer, usually with a GnRH agonist, and to cover the testosterone flare.", "Blocks the androgen receptor so testosterone cannot drive tumour growth.", ["Breast enlargement and tenderness", "Hot flushes", "Liver enzyme rise (rarely severe)", "Fatigue"], "Severe liver impairment.", "50 mg daily with a GnRH agonist, or 150 mg daily alone.", "Check liver tests periodically."),
  p(SUPPORT, "ondansetron", "Ondansetron", "5-HT3 antagonist (antiemetic)", "Prevents and treats chemotherapy-induced and post-operative nausea and vomiting.", "Blocks 5-HT3 receptors in the vomiting centre pathway and on gut vagal nerves.", ["QT prolongation", "Constipation", "Headache"], "Congenital long QT or other QT-prolonging drugs.", "8 mg IV or oral every 8–12 hours (4 mg for post-operative nausea).", "Maximum 8 mg/day in severe liver impairment."),
  p(SUPPORT, "dexamethasone", "Dexamethasone", "Corticosteroid", "An antiemetic with ondansetron; reduces swelling around tumours (raised ICP, cord compression); matures the fetal lungs before preterm birth; used in bacterial meningitis and croup.", "Binds glucocorticoid receptors and switches off inflammatory gene transcription.", ["High blood sugar", "Fluid retention and raised blood pressure", "Infection and delayed wound healing", "Mood change and insomnia", "Stomach irritation"], "Uncontrolled systemic infection; take care in diabetes.", "Antiemetic 8–12 mg; spinal cord compression 16 mg; fetal lung maturity 6 mg IM 12-hourly for four doses before 34 weeks.", "Check glucose in diabetes; short courses rarely cause lasting problems."),
  p(SUPPORT, "filgrastim", "Filgrastim (G-CSF)", "Colony-stimulating factor", "Shortens neutropenia and lowers the risk of febrile neutropenia after chemotherapy.", "Binds the G-CSF receptor and makes the marrow produce and release more neutrophils.", ["Bone pain", "Splenic enlargement or rupture (rare)", "High white count"], "Do not give within 24 hours before or after chemotherapy; caution in sickle cell disease.", "5 µg/kg subcutaneously once daily until the neutrophil count recovers.", "Monitor the blood count during treatment."),
  p(SUPPORT, "mesna", "Mesna", "Uroprotective agent", "Prevents haemorrhagic cystitis from cyclophosphamide and ifosfamide.", "Binds acrolein, the toxic metabolite, in the bladder and makes it harmless.", ["Nausea and diarrhoea", "Allergic reactions (rare)"], "Allergy to thiol compounds.", "Typically 60% of the cyclophosphamide or ifosfamide dose, divided around the infusion.", "Also keep the patient well hydrated and passing urine often."),
  p(SUPPORT, "folinic-acid", "Folinic acid (leucovorin)", "Reduced folate (rescue agent)", "Rescues normal cells after high-dose methotrexate and strengthens the effect of 5-FU.", "A ready-made reduced folate that skips the enzyme (DHFR) that methotrexate blocks.", ["Rarely allergic reactions", "Nausea and diarrhoea (it can worsen 5-FU toxicity)"], "Never give into the spinal fluid; timing relative to methotrexate matters.", "Per protocol, starting 24 hours after high-dose methotrexate and continued until levels are safe.", "Higher doses are needed if methotrexate levels stay high or the kidneys are impaired."),
  p(SUPPORT, "allopurinol", "Allopurinol", "Xanthine oxidase inhibitor", "Prevents tumour lysis syndrome and gout attacks.", "Blocks the enzyme that turns purines into uric acid, so less urate is made.", ["Rash, rarely severe (Stevens–Johnson syndrome; HLA-B*5801)", "Stomach upset", "Raised liver enzymes"], "Do not start during an acute gout attack; reduce with azathioprine or mercaptopurine (by about 75%).", "100–300 mg daily; 300–600 mg daily for tumour lysis prevention.", "Reduce the dose in renal impairment."),
  p(SUPPORT, "zoledronic-acid", "Zoledronic acid", "Bisphosphonate", "Bone metastases, hypercalcaemia of malignancy and osteoporosis.", "Poisons osteoclasts so bone is not broken down.", ["Flu-like reaction after the first dose", "Low calcium", "Kidney damage", "Osteonecrosis of the jaw"], "Poor kidney function, dental problems (get a dental check first), hypocalcaemia.", "4 mg IV over at least 15 minutes, every 3–4 weeks for bone metastases.", "Adjust the dose to creatinine clearance; give calcium and vitamin D."),
];
