// Drugs for common conditions. Teaching doses only: always follow the national guideline and the hospital formulary.
import type { PDrug } from "./types";

const p = (group: string, id: string, name: string, cls: string, why: string, mech: string, ae: string[], caution: string, dose: string, special: string): PDrug => ({ group, id, name, cls, why, mech, ae, caution, dose, special });

export const CV = "Heart and blood pressure";
export const BLOOD = "Blood and clotting";
export const ENDO = "Diabetes and endocrine";
export const RESP = "Lungs and allergy";
export const INF = "Antibacterials and antifungals";
export const VIRAL = "HIV, TB, malaria and worms";
export const CNS = "Brain, mood and seizures";
export const PAIN = "Pain and inflammation";
export const GI = "Stomach and gut";
export const WOMEN = "Pregnancy and contraception";
export const EMERG = "Emergency and antidotes";

export const COMMON_DRUGS: PDrug[] = [
  // ---- heart and blood pressure
  p(CV, "amlodipine", "Amlodipine", "Dihydropyridine calcium-channel blocker", "First-line for hypertension (particularly effective in Black patients) and for angina.", "Blocks L-type calcium channels in arteriolar smooth muscle, relaxing arterioles and lowering resistance.", ["Ankle swelling", "Flushing and headache", "Gum overgrowth", "Palpitations from reflex tachycardia"], "Severe aortic stenosis; swelling is not a sign of heart failure but can be mistaken for it.", "5–10 mg once daily; start 2.5 mg in the frail or elderly.", "Nifedipine is the usual choice in pregnancy. The ankle swelling does not respond to diuretics."),
  p(CV, "hydrochlorothiazide", "Hydrochlorothiazide", "Thiazide diuretic", "First-line for hypertension; also lowers calcium loss in stone formers.", "Blocks the sodium–chloride cotransporter in the distal convoluted tubule.", ["Low potassium and low sodium", "High uric acid — may trigger gout", "High blood sugar", "High calcium"], "Gout, severe low sodium or potassium, allergy to sulphonamides.", "12.5–25 mg once daily.", "Works poorly when eGFR is below 30. Check sodium and potassium after starting."),
  p(CV, "losartan", "Losartan", "Angiotensin receptor blocker (ARB)", "Hypertension, diabetic kidney disease and heart failure (alternative if an ACE inhibitor causes cough).", "Blocks the AT1 receptor, so angiotensin II cannot constrict vessels or release aldosterone.", ["High potassium", "Kidney injury in bilateral renal artery stenosis or dehydration", "Dizziness", "Angioedema (rare)"], "Pregnancy, bilateral renal artery stenosis, high potassium.", "50–100 mg once daily.", "Stop in pregnancy. Follow “sick-day rules”: pause during vomiting, diarrhoea or dehydration."),
  p(CV, "bisoprolol", "Bisoprolol", "Beta-1-selective blocker", "Heart failure with reduced ejection fraction, atrial fibrillation rate control, angina, after a heart attack.", "Blocks beta-1 receptors in the heart, slowing the rate and reducing the force of contraction and oxygen demand.", ["Slow heart rate and fatigue", "Cold hands and feet", "Bronchospasm (less than non-selective drugs)", "Hides the warning signs of hypoglycaemia"], "Asthma, heart block, acute decompensated heart failure, severe peripheral vascular disease.", "1.25–10 mg once daily; start low and titrate in heart failure.", "Never stop suddenly. Take care in asthma."),
  p(CV, "atorvastatin", "Atorvastatin", "Statin (HMG-CoA reductase inhibitor)", "Lowers LDL cholesterol and reduces heart attack and stroke after ASCVD or in diabetes.", "Blocks HMG-CoA reductase, the rate-limiting step in liver cholesterol production, so the liver takes up more LDL.", ["Muscle pain, rarely rhabdomyolysis", "Raised liver enzymes", "Slightly higher blood sugar"], "Pregnancy, active liver disease; interactions with clarithromycin, azole antifungals and fibrates raise the risk of muscle damage.", "10–80 mg once daily.", "No kidney dose adjustment needed. Stop in pregnancy."),
  p(CV, "digoxin", "Digoxin", "Cardiac glycoside", "Slows the heart rate in atrial fibrillation, especially with heart failure.", "Blocks the sodium–potassium pump, raising intracellular calcium (stronger beats) and increasing vagal tone (slower AV conduction).", ["Nausea, vomiting and yellow-tinged vision", "Arrhythmias in toxicity", "Confusion in the elderly"], "Low potassium or magnesium and high calcium make toxicity likelier; heart block; interactions with amiodarone, verapamil and clarithromycin raise levels.", "62.5–250 µg once daily after loading, guided by levels.", "Narrow therapeutic index: reduce the dose in renal impairment and in the elderly."),
  p(CV, "amiodarone", "Amiodarone", "Class III antiarrhythmic", "Ventricular and atrial arrhythmias; given in cardiac arrest for VF.", "Blocks potassium channels (prolonging repolarisation) and also sodium, calcium and beta receptors.", ["Thyroid disease (too much or too little)", "Lung fibrosis", "Liver damage", "Corneal deposits, blue-grey skin and light sensitivity", "Slow rate and QT prolongation"], "Thyroid disease, iodine allergy, heart block; it raises warfarin and digoxin levels.", "300 mg IV in cardiac arrest; oral loading 200 mg three times daily, then 100–200 mg daily.", "Very long half-life: effects and side effects persist for months."),
  p(BLOOD, "warfarin", "Warfarin", "Vitamin K antagonist", "Anticoagulation for mechanical heart valves, mitral stenosis with AF, and long-term venous thromboembolism.", "Blocks vitamin K epoxide reductase, so clotting factors II, VII, IX and X (and proteins C and S) are not activated.", ["Bleeding", "Skin necrosis at the start", "Teratogenic (embryopathy)", "Bruising"], "Pregnancy, bleeding, severe liver disease; many interactions: fluconazole, metronidazole, cotrimoxazole and amiodarone raise the INR, while rifampicin and carbamazepine lower it.", "Dose adjusted to the INR (target 2–3; mechanical mitral valve 2.5–3.5).", "Avoid in pregnancy (use LMWH). Reverse with vitamin K ± prothrombin complex."),
  p(BLOOD, "rivaroxaban", "Rivaroxaban", "Direct oral anticoagulant (factor Xa inhibitor)", "Stroke prevention in atrial fibrillation and treatment and prevention of venous thromboembolism.", "Directly inhibits factor Xa, so thrombin is not generated.", ["Bleeding", "Raised liver enzymes", "Anaemia"], "Mechanical valves, severe mitral stenosis, antiphospholipid syndrome, very low creatinine clearance; rifampicin and carbamazepine reduce its effect.", "AF: 20 mg once daily with food. VTE: 15 mg twice daily for 21 days, then 20 mg daily.", "Avoid if creatinine clearance is below 15. No routine monitoring is needed."),
  p(BLOOD, "clopidogrel", "Clopidogrel", "Antiplatelet (P2Y12 inhibitor)", "After heart attack or stent, and after stroke or TIA.", "Irreversibly blocks the P2Y12 ADP receptor on platelets for their whole life span.", ["Bleeding", "Bruising", "Rarely thrombotic thrombocytopenic purpura"], "Active bleeding; omeprazole reduces its activation (CYP2C19).", "75 mg once daily after a 300–600 mg loading dose.", "Stop 5–7 days before elective surgery unless the cardiologist advises otherwise."),
  p(BLOOD, "ferrous-sulfate", "Ferrous sulfate", "Iron replacement", "Iron-deficiency anaemia.", "Provides iron for haemoglobin synthesis.", ["Constipation or diarrhoea", "Black stools", "Stomach upset"], "Haemochromatosis; it binds levothyroxine, quinolones and tetracyclines in the gut; tea and calcium reduce absorption.", "200 mg (65 mg of elemental iron) once to three times daily; continue 3 months after the haemoglobin normalises.", "In pregnancy 60 mg of elemental iron daily with folic acid."),
  p(BLOOD, "folic-acid", "Folic acid", "Vitamin B9", "Prevents neural tube defects, treats megaloblastic anaemia, and is given with methotrexate and in haemolytic anaemias such as sickle cell disease.", "A cofactor for the synthesis of purines and thymidine, needed for DNA.", ["Very safe at usual doses", "Can mask vitamin B12 deficiency while nerve damage progresses"], "Treat vitamin B12 deficiency first or at the same time, because folic acid alone can mask it while nerve damage progresses.", "400 µg daily before and in early pregnancy (5 mg if high risk); 5 mg daily for treatment.", "Higher doses are used in women who previously had an affected baby or who take antiepileptics."),
  p(BLOOD, "vitamin-k", "Vitamin K (phytomenadione)", "Vitamin", "Prevents bleeding in newborns and reverses warfarin and cholestatic coagulopathy.", "A cofactor to carboxylate clotting factors II, VII, IX and X.", ["Rare anaphylaxis with IV use", "Pain or bruising at the injection site"], "Give IV slowly.", "Newborn 1 mg IM at birth; warfarin reversal 1–5 mg IV.", "Every newborn should receive it."),
  // ---- diabetes and endocrine
  p(ENDO, "gliclazide", "Gliclazide (and glibenclamide)", "Sulfonylurea", "Type 2 diabetes when metformin is not enough.", "Closes ATP-sensitive potassium channels in beta cells so they release insulin.", ["Hypoglycaemia", "Weight gain", "Nausea"], "Elderly and kidney disease (glibenclamide is long-acting and dangerous), skipping meals, alcohol, pregnancy.", "Gliclazide 40–320 mg daily with meals.", "Gliclazide is safer than glibenclamide in the elderly and in renal impairment."),
  p(ENDO, "empagliflozin", "Empagliflozin", "SGLT2 inhibitor", "Type 2 diabetes with heart failure or chronic kidney disease: it protects the heart and kidneys.", "Blocks glucose reabsorption in the proximal tubule so glucose is lost in the urine.", ["Genital fungal infections and UTIs", "Euglycaemic diabetic ketoacidosis", "Dehydration and low blood pressure", "Fournier gangrene (rare)"], "Type 1 diabetes, ketosis risk, severe dehydration; stop during acute illness and before surgery.", "10–25 mg once daily.", "Works less for glucose when eGFR is low but still protects the kidney."),
  p(ENDO, "insulin-basal", "Basal insulin (NPH or glargine)", "Intermediate or long-acting insulin", "Background insulin for type 1 and for type 2 diabetes when tablets fail.", "Binds the insulin receptor: glucose uptake, glycogen storage and suppressed liver glucose output.", ["Hypoglycaemia", "Weight gain", "Lipohypertrophy at injection sites"], "Hypoglycaemia risk with missed meals, exercise or alcohol; reduce when the kidneys fail.", "Start about 0.1–0.2 units/kg once daily (at night for NPH) and titrate to fasting glucose.", "Safe in pregnancy. Rotate injection sites."),
  p(ENDO, "levothyroxine", "Levothyroxine", "Thyroid hormone replacement", "Hypothyroidism.", "Replaces T4, which is converted to the active T3.", ["Palpitations, tremor and weight loss if the dose is too high", "Atrial fibrillation and bone loss from long-term over-replacement"], "Untreated adrenal insufficiency (give steroid first); start low in the elderly or with heart disease; iron and calcium reduce absorption.", "About 1.6 µg/kg once daily on an empty stomach; check TSH after 6–8 weeks.", "Needs are higher in pregnancy: increase the dose and check TSH early."),
  p(ENDO, "carbimazole", "Carbimazole", "Antithyroid drug", "Hyperthyroidism (Graves’ disease).", "Blocks thyroid peroxidase, so iodine is not incorporated into thyroid hormone.", ["Agranulocytosis — a sore throat means stop the drug and check the count", "Rash", "Teratogenic in early pregnancy"], "Pregnancy (use propylthiouracil in the first trimester).", "20–40 mg daily, then titrated down.", "Tell patients to report fever or sore throat at once."),
  // ---- lungs
  p(RESP, "beclometasone", "Beclometasone", "Inhaled corticosteroid", "Preventer treatment in asthma.", "Reduces airway inflammation and over-reactivity.", ["Oral thrush and hoarse voice", "Slight growth slowing in children at high doses"], "Poor technique wastes the dose; rinse the mouth after use.", "100–400 µg twice daily by inhaler with a spacer.", "Safe in pregnancy. Check inhaler technique every visit."),
  // ---- antibacterials / antifungals
  p(INF, "co-amoxiclav", "Co-amoxiclav", "Penicillin plus beta-lactamase inhibitor", "Chest, urinary, skin, dental and abdominal infections where plain amoxicillin may fail.", "Amoxicillin blocks cell-wall synthesis; clavulanic acid protects it from beta-lactamase enzymes.", ["Diarrhoea", "Cholestatic jaundice (more with prolonged courses)", "Rash and allergy"], "Penicillin allergy, previous co-amoxiclav liver injury.", "625 mg three times daily orally; 1.2 g IV three times daily.", "Adjust for kidney function. Safe in pregnancy."),
  p(INF, "azithromycin", "Azithromycin", "Macrolide", "Atypical pneumonia, chlamydia, typhoid and traveller’s diarrhoea; an alternative in penicillin allergy.", "Binds the 50S ribosome and blocks protein synthesis.", ["Nausea and diarrhoea", "QT prolongation", "Liver enzyme rise"], "Other QT-prolonging drugs, long QT.", "500 mg once daily for 3 days; 1 g single dose for chlamydia.", "Safe in pregnancy and breast-feeding."),
  p(INF, "ciprofloxacin", "Ciprofloxacin", "Fluoroquinolone", "Complicated UTI and pyelonephritis, typhoid, travellers’ diarrhoea and some bone infections.", "Inhibits bacterial DNA gyrase and topoisomerase IV.", ["Tendon inflammation and rupture", "QT prolongation", "Seizures and confusion", "Low or high blood sugar", "C. difficile"], "Children and pregnancy (cartilage), epilepsy, myasthenia, steroids; chelates with antacids, iron and calcium.", "500 mg twice daily orally.", "Reduce the dose in renal impairment. Avoid in a patient who might have TB (it can mask it)."),
  p(INF, "nitrofurantoin", "Nitrofurantoin", "Urinary antiseptic", "Uncomplicated cystitis.", "Reduced inside bacteria to compounds that damage DNA and ribosomes; reaches high levels only in urine.", ["Nausea", "Lung reactions or fibrosis with long use", "Nerve damage", "Haemolysis in G6PD deficiency"], "eGFR below 45 (ineffective, more toxic), G6PD deficiency, near term in pregnancy.", "100 mg twice daily (modified release) for 3–5 days.", "Not for pyelonephritis, because it does not reach tissue."),
  p(INF, "cotrimoxazole", "Cotrimoxazole", "Sulfonamide plus trimethoprim", "Prevents and treats Pneumocystis pneumonia in HIV, and treats some UTIs.", "Sequentially blocks bacterial folate synthesis (sulfamethoxazole and trimethoprim).", ["Rash, rarely Stevens–Johnson syndrome", "High potassium", "Low blood counts and folate deficiency"], "Sulfa allergy, G6PD deficiency, neonates (kernicterus), first trimester; raises methotrexate and warfarin effects.", "960 mg daily for prophylaxis; treatment of PCP 120 mg/kg/day in divided doses.", "Reduce in renal impairment."),
  p(INF, "vancomycin", "Vancomycin", "Glycopeptide", "MRSA and serious Gram-positive infections; oral for C. difficile colitis.", "Binds D-Ala–D-Ala so the cell wall cannot be built.", ["Kidney damage", "Hearing loss", "“Red man” flushing if infused too fast"], "Kidney disease; give slowly over at least 1 hour.", "15–20 mg/kg IV every 8–12 hours guided by levels.", "Not absorbed orally, so oral vancomycin works only in the gut."),
  p(INF, "meropenem", "Meropenem", "Carbapenem", "Severe hospital infections, sepsis and meningitis resistant to other drugs.", "A broad-spectrum beta-lactam that blocks cell-wall synthesis and resists most beta-lactamases.", ["Diarrhoea and C. difficile", "Seizures at high dose or in renal failure", "Rash"], "It sharply lowers valproate levels; reserve for serious infection to avoid resistance.", "1 g every 8 hours IV (2 g for meningitis).", "Adjust for renal function."),
  p(INF, "fluconazole", "Fluconazole", "Azole antifungal", "Candida infections and consolidation or maintenance therapy for cryptococcal meningitis.", "Inhibits fungal CYP51 so ergosterol is not made.", ["Liver injury", "QT prolongation", "Interactions: raises warfarin, phenytoin and statin levels"], "Pregnancy (high doses are teratogenic), liver disease, QT drugs.", "150 mg single dose for vaginal thrush; 400–800 mg daily for cryptococcus.", "Reduce in renal impairment."),
  p(INF, "amphotericin-b", "Amphotericin B", "Polyene antifungal", "Cryptococcal meningitis and severe systemic fungal infections.", "Binds ergosterol in the fungal membrane and makes pores that leak.", ["Kidney damage", "Low potassium and magnesium", "Fever, chills and rigors during infusion", "Anaemia"], "Pre-existing kidney disease; liposomal forms are less toxic.", "Conventional 0.7–1 mg/kg daily with flucytosine; liposomal forms use higher doses.", "Pre-hydrate with saline and replace potassium and magnesium."),
  p(INF, "acyclovir", "Acyclovir", "Nucleoside analogue antiviral", "Herpes simplex (including encephalitis), chickenpox and shingles.", "Activated only in infected cells to a false nucleotide that terminates viral DNA synthesis.", ["Kidney crystal injury if dehydrated", "Confusion in high doses", "Nausea"], "Dehydration and renal impairment.", "10 mg/kg IV every 8 hours for encephalitis; 400–800 mg orally for herpes or zoster.", "Reduce the dose in renal impairment and ensure hydration."),
  // ---- HIV, TB, malaria, worms
  p(VIRAL, "tld", "TLD (tenofovir + lamivudine + dolutegravir)", "NRTI backbone plus integrase inhibitor", "First-line HIV treatment in Kenya.", "Tenofovir and lamivudine are chain terminators for reverse transcriptase; dolutegravir blocks the integrase enzyme that inserts viral DNA into the host genome.", ["Insomnia, headache and weight gain (dolutegravir)", "Kidney tubular damage and bone loss (tenofovir)", "Flare of hepatitis B if stopped suddenly"], "Tenofovir is avoided when eGFR is below 50; polyvalent cations (iron, calcium, antacids) reduce dolutegravir absorption; rifampicin lowers dolutegravir so it is doubled.", "One tablet (300/300/50 mg) once daily.", "Preferred in pregnancy. Check viral load at 6 and 12 months."),
  p(VIRAL, "artemether-lumefantrine", "Artemether–lumefantrine", "Artemisinin combination therapy (ACT)", "First-line treatment of uncomplicated Plasmodium falciparum malaria.", "Artemether makes free radicals that kill parasites quickly; lumefantrine blocks haem detoxification and clears the remainder.", ["Headache and dizziness", "Nausea and abdominal pain", "QT prolongation (uncommon)"], "Severe malaria (use IV artesunate), other QT-prolonging drugs.", "Six doses over three days (adult: 4 tablets twice daily) with fatty food or milk.", "Absorption depends on fat in the meal. Test with a rapid test before treating."),
  p(VIRAL, "albendazole", "Albendazole", "Benzimidazole anthelmintic", "Hookworm, roundworm, whipworm, and as part of mass deworming.", "Blocks tubulin polymerisation in the worm, starving it of glucose.", ["Abdominal pain and nausea", "Liver enzyme rise with long courses", "Low blood counts in prolonged use"], "First trimester of pregnancy.", "400 mg as a single dose (longer courses for tissue infections).", "Take with a fatty meal for tissue parasites."),
  p(VIRAL, "praziquantel", "Praziquantel", "Anthelmintic", "Schistosomiasis (common around Lake Victoria), tapeworms and liver flukes.", "Raises calcium permeability in the worm’s tegument, causing paralysis and breakdown.", ["Dizziness and drowsiness", "Abdominal pain", "Headache"], "Ocular cysticercosis (inflammation can blind).", "40 mg/kg once for Schistosoma mansoni and haematobium.", "Safe in pregnancy after counselling."),
  // ---- brain, mood, seizures
  p(CNS, "carbamazepine", "Carbamazepine", "Sodium-channel blocking antiepileptic", "Focal seizures, trigeminal neuralgia and bipolar disorder.", "Blocks voltage-gated sodium channels and so limits repetitive neuronal firing.", ["Dizziness, double vision and ataxia", "Low sodium (SIADH)", "Stevens–Johnson syndrome (HLA-B*1502)", "Aplastic anaemia or agranulocytosis"], "Heart block; absence and myoclonic seizures (can worsen them); strong enzyme inducer, so it lowers levels of the contraceptive pill, warfarin and some HIV drugs.", "200 mg twice daily, titrated to 800–1200 mg daily.", "Neural-tube risk in pregnancy. Monitor sodium and blood count."),
  p(CNS, "phenytoin", "Phenytoin", "Sodium-channel blocking antiepileptic", "Status epilepticus and focal or tonic–clonic seizures.", "Slows recovery of sodium channels so repetitive firing is limited.", ["Gum overgrowth, excess hair and acne", "Ataxia and nystagmus in toxicity", "Folate deficiency", "Low blood pressure and arrhythmia if infused fast"], "Heart block; saturable (zero-order) kinetics mean small dose changes cause large level changes.", "20 mg/kg IV at no more than 50 mg/min with ECG monitoring; maintenance about 300 mg daily.", "Teratogenic (fetal hydantoin syndrome)."),
  p(CNS, "valproate", "Sodium valproate", "Broad-spectrum antiepileptic and mood stabiliser", "Generalised epilepsies, absence seizures, bipolar disorder and migraine prevention.", "Raises GABA, blocks sodium channels and T-type calcium channels.", ["Weight gain, hair loss and tremor", "Liver toxicity and pancreatitis", "Low platelets", "Teratogenic: neural-tube defects and developmental delay"], "Girls and women of child-bearing potential unless on reliable contraception and a pregnancy prevention programme; liver disease.", "500–2000 mg daily in divided doses.", "Meropenem lowers its levels; check LFTs and platelets."),
  p(CNS, "levetiracetam", "Levetiracetam", "Antiepileptic (SV2A binder)", "Focal and generalised seizures; a safer choice in women of child-bearing age.", "Binds synaptic vesicle protein SV2A and dampens neurotransmitter release.", ["Irritability, mood change", "Sleepiness", "Dizziness"], "Reduce the dose in renal impairment.", "500 mg twice daily, increased to 1–1.5 g twice daily.", "Preferred over valproate in pregnancy planning."),
  p(CNS, "levodopa-carbidopa", "Levodopa–carbidopa", "Dopamine precursor plus decarboxylase inhibitor", "Parkinson disease.", "Levodopa is converted to dopamine in the brain; carbidopa stops its breakdown outside the brain so less causes nausea.", ["Nausea", "Involuntary movements (dyskinesias) and “on–off” fluctuations", "Low blood pressure on standing", "Hallucinations"], "Psychosis, narrow-angle glaucoma; high-protein meals reduce absorption.", "100/25 mg three times daily, titrated.", "Do not stop suddenly."),
  p(CNS, "amitriptyline", "Amitriptyline", "Tricyclic antidepressant", "Neuropathic pain, migraine prevention, and depression when other drugs fail.", "Blocks reuptake of serotonin and noradrenaline and also blocks muscarinic, histamine and alpha receptors.", ["Dry mouth, constipation and urine retention", "Drowsiness", "Low blood pressure on standing", "Arrhythmias; very dangerous in overdose"], "Recent heart attack, arrhythmia, glaucoma, suicide risk (a week’s supply can be lethal).", "10–75 mg at night; start 10 mg in the elderly.", "Prescribe small quantities in depression."),
  p(CNS, "olanzapine", "Olanzapine", "Atypical antipsychotic", "Schizophrenia, mania and agitation.", "Blocks dopamine D2 and serotonin 5-HT2A receptors.", ["Weight gain and diabetes", "Sedation", "Raised lipids", "Dry mouth"], "Diabetes, obesity; avoid IM olanzapine within an hour of IM benzodiazepine.", "5–20 mg once daily.", "Monitor weight, glucose and lipids."),
  // ---- pain
  p(PAIN, "ibuprofen", "Ibuprofen (and diclofenac)", "NSAID", "Pain, fever and inflammation.", "Blocks cyclo-oxygenase (COX-1 and COX-2), lowering prostaglandins.", ["Stomach ulcers and bleeding", "Kidney injury", "Raised blood pressure and fluid retention", "Wheeze in aspirin-sensitive asthma"], "Peptic ulcer, kidney disease, heart failure, dehydration, third trimester of pregnancy, with an ACE inhibitor and diuretic (“triple whammy”).", "Ibuprofen 400 mg three times daily with food; diclofenac 50 mg three times daily.", "Avoid in the elderly where possible, or give with a proton pump inhibitor."),
  p(PAIN, "tramadol", "Tramadol", "Weak opioid with serotonin effects", "Moderate pain (step 2 of the pain ladder).", "Acts on opioid receptors and blocks reuptake of serotonin and noradrenaline.", ["Nausea, dizziness and constipation", "Seizures", "Serotonin syndrome with SSRIs"], "Epilepsy, SSRIs or MAOIs, children under 12.", "50–100 mg every 6 hours (maximum 400 mg).", "Reduce in renal impairment."),
  // ---- stomach and gut
  p(GI, "omeprazole", "Omeprazole", "Proton pump inhibitor", "Peptic ulcer, reflux, H. pylori eradication and stomach protection with NSAIDs.", "Irreversibly blocks the H⁺/K⁺-ATPase pump in stomach parietal cells.", ["Headache and diarrhoea", "Low magnesium and vitamin B12 with long-term use", "C. difficile infection", "Fractures with long-term use"], "Reduces clopidogrel activation; review the need for long-term use.", "20–40 mg once daily; 80 mg IV bolus in upper GI bleeding.", "Safe in pregnancy."),
  p(GI, "metoclopramide", "Metoclopramide", "Dopamine antagonist prokinetic", "Nausea, vomiting and gastric emptying problems.", "Blocks D2 receptors in the vomiting centre and speeds stomach emptying.", ["Acute dystonia (especially in young women and children)", "Tardive dyskinesia", "Drowsiness and restlessness"], "Bowel obstruction, phaeochromocytoma, Parkinson disease; short courses only (maximum 5 days).", "10 mg three times daily.", "Avoid in children and adolescents where possible."),
  p(GI, "loperamide", "Loperamide", "Opioid-receptor antidiarrhoeal", "Non-infective diarrhoea in adults.", "Acts on gut opioid receptors to slow motility and increase absorption.", ["Constipation", "Bloating", "Cardiac toxicity in overdose"], "Bloody diarrhoea, fever, colitis, and all children with acute diarrhoea.", "4 mg then 2 mg after each loose stool (maximum 16 mg).", "Never use in children or in infective dysentery."),
  p(GI, "lactulose", "Lactulose", "Osmotic laxative", "Constipation and hepatic encephalopathy.", "An unabsorbed sugar that draws water into the bowel; gut bacteria turn it into acids that trap ammonia in the colon.", ["Bloating and flatulence", "Diarrhoea if the dose is too high"], "Bowel obstruction, galactosaemia.", "For encephalopathy 30–60 mL three times daily, titrated to 2–3 soft stools a day.", "Safe in pregnancy."),
  // ---- pregnancy and contraception
  p(WOMEN, "methyldopa", "Methyldopa", "Centrally acting alpha-2 agonist", "Hypertension in pregnancy.", "Becomes a false transmitter that stimulates central alpha-2 receptors, lowering sympathetic outflow.", ["Drowsiness and depression", "Haemolytic anaemia (positive Coombs test)", "Liver injury", "Dry mouth"], "Depression, liver disease.", "250–500 mg two to three times daily.", "Long safety record in pregnancy."),
  p(WOMEN, "ergometrine", "Ergometrine", "Ergot alkaloid uterotonic", "Treatment of postpartum haemorrhage.", "Stimulates uterine smooth muscle and constricts blood vessels.", ["High blood pressure", "Vomiting", "Chest pain from coronary spasm"], "Hypertension, pre-eclampsia, heart disease; not before delivery of the placenta.", "0.2 mg IM or slow IV.", "Contraindicated in hypertensive disorders."),
  p(WOMEN, "depo-provera", "Medroxyprogesterone (Depo-Provera)", "Injectable progestogen contraceptive", "Long-acting reversible contraception.", "Stops ovulation and thickens cervical mucus.", ["Irregular bleeding then no periods", "Weight gain", "Bone density loss", "Delayed return of fertility"], "Breast cancer, undiagnosed vaginal bleeding, severe liver disease.", "150 mg IM every 12–13 weeks.", "Safe in breast-feeding after 6 weeks and in HIV."),
  p(WOMEN, "combined-pill", "Combined oral contraceptive pill", "Oestrogen plus progestogen", "Contraception and cycle control.", "Suppresses ovulation and thickens cervical mucus.", ["Clots (venous thromboembolism)", "Raised blood pressure", "Stroke in migraine with aura", "Breast tenderness and nausea"], "Smokers over 35, migraine with aura, previous clot, hypertension, breast-feeding under 6 weeks, enzyme inducers (rifampicin, carbamazepine).", "One tablet daily for 21 days, then a 7-day break.", "Check blood pressure before and during use."),
  p(WOMEN, "levonorgestrel-ec", "Levonorgestrel emergency contraception", "Progestogen", "Emergency contraception after unprotected sex.", "Delays ovulation.", ["Nausea", "Irregular bleeding", "Headache"], "Less effective with higher body weight and after ovulation.", "1.5 mg once, as soon as possible (best within 72 hours, usable up to 120 hours).", "Double the dose with enzyme inducers such as rifampicin or efavirenz."),
  // ---- emergency and antidotes
  p(EMERG, "adrenaline", "Adrenaline (epinephrine)", "Alpha and beta agonist", "Anaphylaxis, cardiac arrest and severe croup.", "Stimulates alpha receptors (vasoconstriction), beta-1 (heart) and beta-2 (bronchodilation).", ["Fast heart rate and arrhythmia", "High blood pressure", "Tremor and anxiety"], "None absolute in anaphylaxis; never give the 1:1000 strength by IV push.", "Anaphylaxis: 0.5 mg IM adult (0.5 mL of 1:1000), repeat after 5 minutes. Cardiac arrest: 1 mg IV (1:10,000) every 3–5 minutes.", "Child dose 0.01 mg/kg IM (0.15 mg if under 6, 0.3 mg for 6–12 years)."),
  p(EMERG, "atropine", "Atropine", "Antimuscarinic", "Symptomatic slow heart rate and organophosphate poisoning.", "Blocks muscarinic receptors so the vagus nerve loses its brake on the heart.", ["Dry mouth and blurred vision", "Fast heart rate", "Urine retention", "Confusion"], "Glaucoma, urinary obstruction.", "0.5–1 mg IV for bradycardia (maximum 3 mg); large repeated doses in organophosphate poisoning.", "Be careful in the elderly (delirium)."),
  p(EMERG, "naloxone", "Naloxone", "Opioid antagonist", "Reverses opioid overdose and respiratory depression.", "Competes with opioids at mu receptors.", ["Sudden withdrawal with agitation", "Short action means the patient can slip back into respiratory depression"], "Opioid-dependent patients (start with small doses).", "0.4–2 mg IV, IM or SC; repeat, then consider an infusion.", "Its effect lasts shorter than many opioids, so observe."),
  p(EMERG, "n-acetylcysteine", "N-acetylcysteine", "Antidote for paracetamol", "Paracetamol overdose.", "Replenishes glutathione so the toxic metabolite NAPQI is neutralised.", ["Rash and anaphylactoid reaction", "Nausea"], "Give early; effective if started within 8 hours.", "150 mg/kg over 1 hour, then 50 mg/kg over 4 hours, then 100 mg/kg over 16 hours.", "Use the treatment nomogram and send levels at 4 hours."),
  p(EMERG, "iv-fluids", "Intravenous crystalloids (Ringer’s lactate, saline)", "Intravenous fluids", "Resuscitation in shock, dehydration and sepsis.", "Expand the intravascular volume.", ["Fluid overload and pulmonary oedema", "High chloride acidosis (large volumes of saline)", "Low sodium with dextrose"], "Heart failure, kidney failure and severe malnutrition (risk of overload).", "Adult 500 mL bolus then reassess; child 10–20 mL/kg (10 mL/kg in severe malnutrition).", "Always reassess after each bolus."),
];
