// Reference material for pharmacology: cancer-drug classes and regimens, oncology emergencies, interactions, name suffixes, adverse-effect links.
import type { AeLink, Interaction, Regimen, Suffix } from "./types";

export const CELL_CYCLE = [
  { phase: "G1", what: "Cell grows and prepares", drugs: "Corticosteroids, asparaginase (cell-cycle specific)" },
  { phase: "S", what: "DNA is copied", drugs: "Antimetabolites: methotrexate, 5-FU, cytarabine, 6-mercaptopurine, hydroxyurea" },
  { phase: "G2", what: "Checks before division", drugs: "Bleomycin, topoisomerase inhibitors (etoposide)" },
  { phase: "M", what: "Cell divides (mitosis)", drugs: "Vinca alkaloids (vincristine) and taxanes (paclitaxel) — they act on the spindle" },
  { phase: "Any", what: "Cell-cycle non-specific", drugs: "Alkylating agents, platinum compounds, anthracyclines" },
];

export const ONC_CLASSES: { cls: string; drugs: string; mech: string; signature: string }[] = [
  { cls: "Alkylating agents", drugs: "Cyclophosphamide, ifosfamide, chlorambucil, melphalan, dacarbazine", mech: "Cross-link DNA", signature: "Haemorrhagic cystitis (cyclophosphamide, ifosfamide) · secondary leukaemia · marrow suppression" },
  { cls: "Platinum compounds", drugs: "Cisplatin, carboplatin, oxaliplatin", mech: "Cross-link DNA", signature: "Cisplatin: kidney, ears, nerves, vomiting · carboplatin: platelets · oxaliplatin: cold-triggered neuropathy" },
  { cls: "Antimetabolites", drugs: "Methotrexate, 5-FU, capecitabine, cytarabine, gemcitabine, 6-MP", mech: "Fake building blocks or block folate and nucleotide enzymes (S phase)", signature: "Mouth ulcers, diarrhoea, marrow suppression · methotrexate: liver, lung, kidney · 5-FU: hand–foot syndrome" },
  { cls: "Anthracyclines", drugs: "Doxorubicin, daunorubicin, epirubicin", mech: "Intercalate DNA, topoisomerase II inhibition, free radicals", signature: "Cardiomyopathy (cumulative dose) · red urine · tissue necrosis if extravasated" },
  { cls: "Topoisomerase inhibitors", drugs: "Etoposide (II), irinotecan and topotecan (I)", mech: "Cause DNA breaks", signature: "Irinotecan: early and late diarrhoea · etoposide: secondary leukaemia" },
  { cls: "Vinca alkaloids", drugs: "Vincristine, vinblastine, vinorelbine", mech: "Block microtubule assembly (M phase)", signature: "Neuropathy and constipation (vincristine) · marrow suppression (vinblastine) · NEVER intrathecal" },
  { cls: "Taxanes", drugs: "Paclitaxel, docetaxel", mech: "Stabilise microtubules (M phase)", signature: "Hypersensitivity · neuropathy · neutropenia · docetaxel: fluid retention" },
  { cls: "Cytotoxic antibiotics", drugs: "Bleomycin, dactinomycin, mitomycin", mech: "DNA strand breaks", signature: "Bleomycin: pulmonary fibrosis and skin pigmentation, little marrow suppression" },
  { cls: "Hormonal agents", drugs: "Tamoxifen, letrozole/anastrozole, leuprorelin/goserelin, bicalutamide", mech: "Block or lower the hormones that drive the tumour", signature: "Hot flushes · tamoxifen: clots and endometrial cancer · aromatase inhibitors: bone loss" },
  { cls: "Kinase inhibitors (-nib)", drugs: "Imatinib, erlotinib, sunitinib", mech: "Block signalling enzymes the cancer depends on", signature: "Imatinib: fluid retention and cramps · others: rash, hypertension, diarrhoea" },
  { cls: "Monoclonal antibodies (-mab)", drugs: "Rituximab, trastuzumab, bevacizumab", mech: "Bind a surface target and recruit the immune system", signature: "Infusion reactions · trastuzumab: heart · rituximab: hepatitis B reactivation" },
];

export const REGIMENS: Regimen[] = [
  { cancer: "Breast cancer (early, hormone-positive)", regimen: "AC → T, then endocrine therapy", drugs: "Doxorubicin + cyclophosphamide, then paclitaxel; tamoxifen or an aromatase inhibitor for 5–10 years (add trastuzumab if HER2-positive)", watch: "Heart (anthracycline, trastuzumab), neuropathy, bone loss, womb lining on tamoxifen", note: "Receptor status decides the drugs." },
  { cancer: "Hodgkin lymphoma", regimen: "ABVD", drugs: "Doxorubicin, bleomycin, vinblastine, dacarbazine", watch: "Lungs (bleomycin), heart (doxorubicin), neutropenia", note: "Avoid high-concentration oxygen after bleomycin." },
  { cancer: "Diffuse large B-cell lymphoma", regimen: "R-CHOP", drugs: "Rituximab, cyclophosphamide, doxorubicin, vincristine, prednisolone", watch: "Hepatitis B reactivation, neuropathy, cystitis, heart, infections", note: "Check hepatitis B before rituximab." },
  { cancer: "Burkitt lymphoma", regimen: "Intensive cyclophosphamide-based regimens", drugs: "Cyclophosphamide, vincristine, doxorubicin, high-dose methotrexate with folinic acid rescue, intrathecal methotrexate or cytarabine", watch: "Tumour lysis syndrome, mucositis, neutropenia, kidney function", note: "Hydrate and give allopurinol or rasburicase before starting." },
  { cancer: "Acute lymphoblastic leukaemia", regimen: "Induction, consolidation, maintenance", drugs: "Vincristine, prednisolone, asparaginase, an anthracycline, then methotrexate and mercaptopurine; intrathecal chemotherapy", watch: "Infections, tumour lysis, neuropathy, pancreatitis (asparaginase)", note: "Allopurinol reduces mercaptopurine clearance: lower its dose." },
  { cancer: "Chronic myeloid leukaemia", regimen: "Targeted tablet", drugs: "Imatinib 400 mg daily", watch: "Fluid retention, blood counts, BCR-ABL levels", note: "Rifampicin lowers imatinib levels." },
  { cancer: "Cervical cancer (locally advanced)", regimen: "Chemoradiation", drugs: "Weekly cisplatin with pelvic radiotherapy, then brachytherapy", watch: "Kidney function, magnesium, hearing, blood counts", note: "Carboplatin if the kidneys are poor." },
  { cancer: "Kaposi sarcoma (HIV)", regimen: "ART ± chemotherapy", drugs: "Antiretroviral therapy; paclitaxel or doxorubicin–bleomycin–vincristine for advanced disease", watch: "Blood counts, IRIS after ART, neuropathy", note: "Avoid steroids." },
  { cancer: "Colorectal cancer (stage III)", regimen: "FOLFOX or CAPOX", drugs: "5-FU, folinic acid and oxaliplatin (or capecitabine plus oxaliplatin)", watch: "Cold-triggered neuropathy, diarrhoea, hand–foot syndrome, neutropenia", note: "No cold drinks or cold exposure during oxaliplatin." },
  { cancer: "Testicular germ-cell tumour", regimen: "BEP", drugs: "Bleomycin, etoposide, cisplatin", watch: "Lungs, kidneys, ears, fertility", note: "Highly curable even when metastatic." },
  { cancer: "Osteosarcoma", regimen: "MAP", drugs: "High-dose methotrexate with folinic rescue, doxorubicin, cisplatin, plus surgery", watch: "Methotrexate levels, kidney, heart, hearing", note: "Needs facilities to measure methotrexate levels." },
  { cancer: "Prostate cancer (advanced)", regimen: "Androgen deprivation", drugs: "Leuprorelin or goserelin ± bicalutamide, or bilateral orchidectomy", watch: "Bone density, metabolic effects, hot flushes", note: "Cover the testosterone flare with an anti-androgen." },
];

export const ONC_EMERGENCIES: { name: string; recognise: string; act: string }[] = [
  { name: "Febrile neutropenia", recognise: "Temperature 38 °C or above in the days after chemotherapy, neutrophils below 1.0 (often unwell without focal signs).", act: "Treat as sepsis: cultures, then IV broad-spectrum antibiotic (piperacillin–tazobactam or meropenem) within an hour, fluids, source search. Do not wait for the count." },
  { name: "Tumour lysis syndrome", recognise: "After chemotherapy in a bulky, fast tumour (Burkitt, leukaemia): high potassium, phosphate and urate, low calcium, kidney injury, arrhythmia.", act: "Aggressive hydration, allopurinol or rasburicase, treat hyperkalaemia, monitor every 4–6 hours, dialyse if refractory." },
  { name: "Hypercalcaemia of malignancy", recognise: "Thirst, constipation, confusion, vomiting, short QT; bone metastases or myeloma.", act: "IV saline rehydration first, then zoledronic acid; consider calcitonin; treat the cancer." },
  { name: "Spinal cord compression", recognise: "Back pain in a cancer patient, leg weakness, sensory level, urinary retention.", act: "Lie flat, dexamethasone 16 mg, urgent MRI whole spine, radiotherapy or surgery within 24 hours." },
  { name: "Superior vena cava obstruction", recognise: "Facial swelling, distended neck veins, breathlessness, worse on lying or bending.", act: "Dexamethasone, sit up, oxygen, urgent imaging, stent or radiotherapy; biopsy before steroids only if lymphoma is likely and stable." },
  { name: "Extravasation", recognise: "Pain, swelling or burning at the infusion site during a vesicant drug (doxorubicin, vincristine).", act: "Stop the infusion, aspirate the drug, then cold compress (warm for vinca alkaloids); dexrazoxane for anthracyclines; hyaluronidase for vinca." },
  { name: "Chemotherapy hypersensitivity", recognise: "Flushing, wheeze, back pain, hypotension during paclitaxel, rituximab or platinum infusions.", act: "Stop the infusion, give adrenaline for anaphylaxis, steroid and antihistamine; premedicate and slow the rate next time." },
];

export const INTERACTIONS: Interaction[] = [
  { a: "Rifampicin", b: "Dolutegravir, the contraceptive pill, warfarin, antiepileptics", effect: "Rifampicin is a strong enzyme inducer: the other drug’s levels fall", why: "CYP450 induction. Double the dolutegravir dose, use another contraceptive method, recheck the INR." },
  { a: "Warfarin", b: "NSAIDs or aspirin", effect: "Bleeding risk rises", why: "Platelet inhibition and stomach ulceration add to the anticoagulant effect." },
  { a: "Warfarin", b: "Fluconazole, metronidazole, cotrimoxazole, amiodarone", effect: "INR rises, bleeding", why: "These inhibit warfarin metabolism." },
  { a: "ACE inhibitor", b: "Spironolactone, potassium supplements or trimethoprim", effect: "Dangerous hyperkalaemia", why: "All reduce potassium excretion." },
  { a: "ACE inhibitor + diuretic", b: "NSAID", effect: "Acute kidney injury (“triple whammy”)", why: "The NSAID constricts the afferent arteriole while the ACE inhibitor relaxes the efferent one, and the diuretic lowers volume." },
  { a: "Methotrexate", b: "Cotrimoxazole, trimethoprim, NSAIDs", effect: "Methotrexate toxicity: severe marrow suppression", why: "Added folate antagonism and reduced kidney clearance." },
  { a: "Lithium", b: "NSAIDs, ACE inhibitors, thiazides, dehydration", effect: "Lithium toxicity", why: "Less lithium is excreted by the kidney." },
  { a: "Clarithromycin or erythromycin", b: "Simvastatin or atorvastatin", effect: "Rhabdomyolysis", why: "CYP3A4 inhibition raises the statin level." },
  { a: "Sildenafil", b: "Nitrates (GTN, isosorbide)", effect: "Profound hypotension", why: "Both raise cyclic GMP, relaxing blood vessels." },
  { a: "SSRI", b: "Tramadol, linezolid, MAOI or triptan", effect: "Serotonin syndrome", why: "Excess serotonin: agitation, sweating, tremor, high temperature, clonus." },
  { a: "Fluoroquinolone", b: "Steroids or NSAIDs", effect: "Tendon rupture and seizures", why: "Additive tendon toxicity; NSAIDs lower the seizure threshold." },
  { a: "Iron, calcium or antacids", b: "Levothyroxine, quinolones, tetracyclines or dolutegravir", effect: "Reduced absorption", why: "They chelate in the gut: separate doses by 2–4 hours." },
  { a: "Digoxin", b: "Amiodarone, verapamil or clarithromycin", effect: "Digoxin toxicity", why: "Reduced clearance: halve the dose and check levels." },
  { a: "Allopurinol", b: "Azathioprine or mercaptopurine", effect: "Severe marrow suppression", why: "Allopurinol blocks their breakdown by xanthine oxidase: reduce the dose to about a quarter." },
  { a: "Beta-blocker", b: "Verapamil or diltiazem", effect: "Heart block and profound bradycardia", why: "Both slow the AV node." },
  { a: "Metronidazole", b: "Alcohol", effect: "Disulfiram-like reaction (flushing, vomiting)", why: "Acetaldehyde accumulates." },
  { a: "Opioids", b: "Benzodiazepines or alcohol", effect: "Respiratory depression", why: "Additive central depression." },
  { a: "Valproate", b: "Meropenem", effect: "Valproate levels fall and seizures return", why: "Carbapenems drastically reduce valproate levels." },
  { a: "Cisplatin", b: "Aminoglycosides or loop diuretics", effect: "Kidney damage and deafness", why: "Additive nephrotoxicity and ototoxicity." },
  { a: "Imatinib", b: "Rifampicin", effect: "Imatinib levels fall", why: "Enzyme induction: increase the dose and monitor the response." },
  { a: "Tamoxifen", b: "Fluoxetine or paroxetine", effect: "Tamoxifen is less effective", why: "CYP2D6 inhibition prevents its activation." },
  { a: "Clopidogrel", b: "Omeprazole", effect: "Weaker antiplatelet effect", why: "CYP2C19 inhibition reduces its activation; use pantoprazole." },
  { a: "Metformin", b: "Iodinated contrast or AKI", effect: "Lactic acidosis", why: "Reduced clearance of metformin: hold it around contrast and in AKI." },
  { a: "Carbamazepine", b: "The contraceptive pill, warfarin or dolutegravir", effect: "Reduced levels of the other drug", why: "Strong enzyme induction." },
];

export const SUFFIXES: Suffix[] = [
  { stem: "-pril", meaning: "ACE inhibitor", example: "enalapril, lisinopril" },
  { stem: "-sartan", meaning: "Angiotensin receptor blocker", example: "losartan, valsartan" },
  { stem: "-olol", meaning: "Beta-blocker", example: "bisoprolol, atenolol, propranolol" },
  { stem: "-dipine", meaning: "Dihydropyridine calcium-channel blocker", example: "amlodipine, nifedipine" },
  { stem: "-statin", meaning: "HMG-CoA reductase inhibitor", example: "atorvastatin, simvastatin" },
  { stem: "-thiazide", meaning: "Thiazide diuretic", example: "hydrochlorothiazide, bendroflumethiazide" },
  { stem: "-gliflozin", meaning: "SGLT2 inhibitor", example: "empagliflozin, dapagliflozin" },
  { stem: "-gliptin", meaning: "DPP-4 inhibitor", example: "sitagliptin, linagliptin" },
  { stem: "-glutide", meaning: "GLP-1 agonist", example: "semaglutide, liraglutide" },
  { stem: "-xaban", meaning: "Factor Xa inhibitor (DOAC)", example: "rivaroxaban, apixaban" },
  { stem: "-gatran", meaning: "Direct thrombin inhibitor", example: "dabigatran" },
  { stem: "-parin", meaning: "Heparin", example: "enoxaparin, dalteparin" },
  { stem: "-plase", meaning: "Thrombolytic", example: "alteplase, tenecteplase" },
  { stem: "-prazole", meaning: "Proton pump inhibitor", example: "omeprazole, pantoprazole" },
  { stem: "-tidine", meaning: "H2 blocker", example: "ranitidine, famotidine" },
  { stem: "-setron", meaning: "5-HT3 antagonist (antiemetic)", example: "ondansetron, granisetron" },
  { stem: "-cillin", meaning: "Penicillin", example: "amoxicillin, flucloxacillin" },
  { stem: "-floxacin", meaning: "Fluoroquinolone", example: "ciprofloxacin, levofloxacin" },
  { stem: "-thromycin", meaning: "Macrolide", example: "azithromycin, clarithromycin" },
  { stem: "-micin / -mycin", meaning: "Aminoglycoside (-micin) or macrolide/other (-mycin)", example: "gentamicin, vancomycin" },
  { stem: "-cycline", meaning: "Tetracycline", example: "doxycycline" },
  { stem: "-azole", meaning: "Azole antifungal (or nitroimidazole)", example: "fluconazole, metronidazole" },
  { stem: "-vir", meaning: "Antiviral", example: "acyclovir, dolutegravir (-tegravir integrase), lopinavir (-navir protease)" },
  { stem: "-mab", meaning: "Monoclonal antibody", example: "rituximab, trastuzumab" },
  { stem: "-nib", meaning: "Kinase inhibitor", example: "imatinib" },
  { stem: "-platin", meaning: "Platinum compound", example: "cisplatin, carboplatin" },
  { stem: "-rubicin", meaning: "Anthracycline", example: "doxorubicin, epirubicin" },
  { stem: "-taxel", meaning: "Taxane", example: "paclitaxel, docetaxel" },
  { stem: "-relin", meaning: "GnRH agonist or analogue", example: "leuprorelin, goserelin" },
  { stem: "-dronate", meaning: "Bisphosphonate", example: "alendronate, zoledronate" },
  { stem: "-sone / -solone", meaning: "Corticosteroid", example: "prednisolone, dexamethasone, hydrocortisone" },
  { stem: "-terol", meaning: "Beta-2 agonist", example: "salbutamol (albuterol), formoterol" },
  { stem: "-tropium", meaning: "Antimuscarinic bronchodilator", example: "ipratropium, tiotropium" },
  { stem: "-lukast", meaning: "Leukotriene antagonist", example: "montelukast" },
  { stem: "-azepam / -azolam", meaning: "Benzodiazepine", example: "diazepam, lorazepam, midazolam" },
  { stem: "-oxetine", meaning: "SSRI", example: "fluoxetine, paroxetine" },
  { stem: "-triptyline", meaning: "Tricyclic antidepressant", example: "amitriptyline" },
  { stem: "-idone / -apine", meaning: "Antipsychotic", example: "risperidone, olanzapine, quetiapine" },
  { stem: "-triptan", meaning: "5-HT1 agonist for migraine", example: "sumatriptan" },
  { stem: "-caine", meaning: "Local anaesthetic", example: "lidocaine, bupivacaine" },
  { stem: "-profen / -fenac / -coxib", meaning: "NSAID", example: "ibuprofen, diclofenac, celecoxib" },
  { stem: "-afil", meaning: "PDE-5 inhibitor", example: "sildenafil" },
];

export const AE_LINKS: AeLink[] = [
  { effect: "Dry cough and angioedema", drugs: ["ACE inhibitors (enalapril, lisinopril)"], note: "Bradykinin build-up; switch to an ARB." },
  { effect: "Gum overgrowth", drugs: ["Phenytoin", "Amlodipine and other calcium-channel blockers", "Ciclosporin"], note: "Good oral hygiene helps." },
  { effect: "Ototoxicity (hearing loss, tinnitus)", drugs: ["Aminoglycosides (gentamicin)", "Loop diuretics (high-dose furosemide)", "Cisplatin"], note: "Avoid combining these." },
  { effect: "Orange-red body fluids", drugs: ["Rifampicin"], note: "Harmless; warn the patient. Contact lenses stain." },
  { effect: "Optic neuritis (colour vision loss)", drugs: ["Ethambutol"], note: "Check colour vision and acuity." },
  { effect: "Peripheral neuropathy", drugs: ["Isoniazid", "Vincristine", "Cisplatin and paclitaxel", "Metronidazole (long course)"], note: "Pyridoxine prevents isoniazid neuropathy." },
  { effect: "Pulmonary fibrosis", drugs: ["Bleomycin", "Amiodarone", "Methotrexate", "Nitrofurantoin (long term)"], note: "Baseline and follow-up lung function." },
  { effect: "Cardiomyopathy", drugs: ["Doxorubicin (anthracyclines)", "Trastuzumab"], note: "Echo before and during treatment." },
  { effect: "Haemorrhagic cystitis", drugs: ["Cyclophosphamide", "Ifosfamide"], note: "Prevent with fluids and mesna." },
  { effect: "Agranulocytosis", drugs: ["Carbimazole", "Clozapine", "Carbamazepine"], note: "A sore throat or fever means check the blood count." },
  { effect: "Tendon rupture", drugs: ["Fluoroquinolones (ciprofloxacin)"], note: "Higher risk with steroids and in the elderly." },
  { effect: "Hypothyroidism", drugs: ["Lithium", "Amiodarone"], note: "Check TSH every 6 months." },
  { effect: "Gynaecomastia", drugs: ["Spironolactone", "Digoxin", "Cimetidine", "Bicalutamide"], note: "Eplerenone avoids it." },
  { effect: "Tardive dyskinesia and acute dystonia", drugs: ["Antipsychotics (haloperidol)", "Metoclopramide"], note: "Dopamine receptor blockade in the nigrostriatal pathway." },
  { effect: "Stevens–Johnson syndrome", drugs: ["Carbamazepine", "Allopurinol", "Phenytoin", "Cotrimoxazole", "Nevirapine"], note: "Stop the drug at the first mouth ulcers or skin blistering." },
  { effect: "Hepatotoxicity", drugs: ["Paracetamol overdose", "Isoniazid, rifampicin and pyrazinamide", "Valproate", "Methotrexate"], note: "Check liver tests." },
  { effect: "QT prolongation", drugs: ["Macrolides (azithromycin)", "Haloperidol", "Ondansetron", "Fluoroquinolones", "Artemether–lumefantrine"], note: "Check ECG and electrolytes; avoid combining." },
  { effect: "Hyperkalaemia", drugs: ["ACE inhibitors and ARBs", "Spironolactone", "Trimethoprim", "Heparin"], note: "Particularly in kidney disease." },
  { effect: "“Red man” flushing", drugs: ["Vancomycin"], note: "Slow the infusion; it is not a true allergy." },
  { effect: "Disulfiram-like reaction with alcohol", drugs: ["Metronidazole"], note: "Avoid alcohol during and 48 hours after." },
  { effect: "Drug-induced lupus", drugs: ["Hydralazine", "Procainamide", "Isoniazid"], note: "Anti-histone antibodies." },
  { effect: "Photosensitivity", drugs: ["Doxycycline", "Amiodarone", "Thiazides"], note: "Advise sun protection." },
  { effect: "Tooth discolouration and bone effects in children", drugs: ["Tetracyclines (doxycycline)"], note: "Avoid in pregnancy and under 8 years." },
  { effect: "Kidney tubular damage and bone loss", drugs: ["Tenofovir"], note: "Check creatinine and avoid when eGFR is below 50." },
  { effect: "Osteonecrosis of the jaw", drugs: ["Bisphosphonates (zoledronic acid)", "Denosumab"], note: "Dental check before starting." },
  { effect: "Hand–foot syndrome", drugs: ["Capecitabine", "5-fluorouracil"], note: "Painful red palms and soles." },
  { effect: "Hypoglycaemia", drugs: ["Insulin", "Sulfonylureas (glibenclamide)", "Quinine"], note: "Particularly dangerous in the elderly and in kidney disease." },
  { effect: "Hyperprolactinaemia", drugs: ["Risperidone and other antipsychotics", "Metoclopramide"], note: "Galactorrhoea and amenorrhoea." },
  { effect: "Serotonin syndrome", drugs: ["SSRIs combined with tramadol, linezolid or MAOIs"], note: "Clonus, sweating, hyperthermia." },
];

export const PREGNANCY_AVOID: { drug: string; harm: string }[] = [
  { drug: "ACE inhibitors and ARBs", harm: "Fetal kidney failure, oligohydramnios and skull defects" },
  { drug: "Warfarin", harm: "Embryopathy and bleeding (use LMWH instead)" },
  { drug: "Valproate", harm: "Neural-tube defects and developmental delay" },
  { drug: "Phenytoin and carbamazepine", harm: "Fetal hydantoin syndrome; neural-tube defects" },
  { drug: "Lithium", harm: "Cardiac malformation (Ebstein anomaly)" },
  { drug: "Methotrexate", harm: "Miscarriage and malformations" },
  { drug: "Tetracyclines (doxycycline)", harm: "Tooth discolouration and bone growth effects" },
  { drug: "Aminoglycosides", harm: "Fetal deafness" },
  { drug: "Fluoroquinolones", harm: "Cartilage damage (avoid unless essential)" },
  { drug: "Cotrimoxazole (first trimester and near term)", harm: "Folate antagonism; kernicterus near term" },
  { drug: "Statins", harm: "Possible congenital malformations (stop in pregnancy)" },
  { drug: "NSAIDs in the third trimester", harm: "Early closure of the ductus arteriosus and oligohydramnios" },
  { drug: "Carbimazole (first trimester)", harm: "Aplasia cutis (use propylthiouracil in the first trimester)" },
  { drug: "Misoprostol and thalidomide", harm: "Abortion and limb defects" },
];
export const PREGNANCY_SAFE = ["Methyldopa, labetalol and nifedipine", "Penicillins and cephalosporins", "Paracetamol", "Low-molecular-weight heparin", "Insulin", "Levothyroxine", "Folic acid and iron", "Antiretroviral therapy (TLD) — preferred in pregnancy"];

export const RENAL_CAUTION: { drug: string; action: string }[] = [
  { drug: "Metformin", action: "Stop if eGFR below 30 or during AKI, sepsis or contrast" },
  { drug: "NSAIDs", action: "Avoid in CKD, AKI and with ACE inhibitor plus diuretic" },
  { drug: "Gentamicin and vancomycin", action: "Adjust the interval and monitor levels" },
  { drug: "Tenofovir", action: "Avoid if eGFR below 50" },
  { drug: "Nitrofurantoin", action: "Ineffective and more toxic below eGFR 45" },
  { drug: "Digoxin", action: "Reduce the dose and monitor levels" },
  { drug: "Enoxaparin and DOACs", action: "Accumulate: reduce or choose unfractionated heparin when eGFR is below 30" },
  { drug: "Morphine", action: "Active metabolite accumulates; use a smaller dose or an alternative opioid" },
  { drug: "Lithium", action: "Toxicity risk; avoid in significant CKD" },
  { drug: "Methotrexate", action: "Accumulates: avoid in significant renal impairment" },
  { drug: "Glibenclamide", action: "Long-acting active metabolites cause prolonged hypoglycaemia; use gliclazide" },
  { drug: "Cisplatin", action: "Avoid if eGFR low; use carboplatin with a dose based on GFR" },
];

export const ENZYME_MNEMONICS = {
  inducers: { title: "Enzyme INDUCERS (drug levels fall)", words: "Phenytoin · Carbamazepine · Barbiturates · Rifampicin · chronic Alcohol · Sulfonylureas · St John’s wort", mnemonic: "“PC BRAS”" },
  inhibitors: { title: "Enzyme INHIBITORS (drug levels rise)", words: "Sodium valproate · Isoniazid · Cimetidine · Ketoconazole and other azoles · acute Alcohol · Chloramphenicol · Erythromycin and clarithromycin · Sulfonamides · Ciprofloxacin · Omeprazole · Metronidazole · Amiodarone · grapefruit juice", mnemonic: "“SICKFACES.COM”" },
};
